### ISSUE TITLE
Sound issue

### ISSUE THREAD

**Issue by hdamico** [profzei/Matebook-X-Pro-2018#1]
Hi! I am having problem with the sound output device. When I plug a headset I have two headphones entries on System Preferences -> Sound, and after some random time, the sound switches between these outputs automaticaly. So I need to switch between these to get sound. I don´t if it there is any error on the sound kexts or what.

**Comment by profzei** [comment]
I'm sorry: at the moment my sound output device's configuration is just a cut&paste from gnodipac886's one.
Now (see https://github.com/profzei/Matebook-X-Pro-2018/blob/master/Changelog.md) I have almost fixed/improved Intel(R) UHD 620 Graphics card config: I need to fix/improve clamshell sleep (but I think the solution is quite standard) and DisplayVendorID config.
Then I will focus my attention to sound device!

**Comment by hdamico** [comment]
Wow nice, that will be great, and thanks for your work! Keep it on!
