### ISSUE TITLE
10.15.5 Supplemental Update

### ISSUE THREAD

**Issue by AshleyMiller9696** [profzei/Matebook-X-Pro-2018#10]
After the supplement update which released yesterday I can‘t get MacOS to boot
Is anyone having the same problems?

**Comment by profzei** [comment]
Honestly, I don't yet update...
When you say that the machine didn't boot, you mean:
1. boot hangs -> in such case, could you upload a screenshot?
2. machine automatically reboots by itself...

Try to replace your drivers/UEFI folder with this one and let me know if there are any significant changes, please:
[UEFI.zip](https://github.com/profzei/Matebook-X-Pro-2018/files/4717812/UEFI.zip)

**Comment by AshleyMiller9696** [comment]
don't know why the System Update in MacOS didn't work
boot hang // -v showed something like kext couldn't load but forgot to make a screenshot

-> installed a fresh installation of MacOS Catalina 10.15.5 Supplemental & now everything is up to date & works

maybe i did something wrong with my installation but since it runs now,
i close the issue
