### ISSUE TITLE
Huawei Share on MacOS

### ISSUE THREAD

**Issue by samwzlim** [profzei/Matebook-X-Pro-2018#100]
Not an issue, rather, just a question. Are we able to run Huawei PC Manager on MacOS? I would love to use Huawei Share between my Huawei phone and Hackintosh

**Comment by profzei** [comment]
@samwzlim ...Nope!
May be with Crossover, but I honestly don't think so

**Comment by samwzlim** [comment]
@profzei So sorry, didn't see your reply earlier. I tried Crossover and it didn't work for Pc Manager unfortunately. The closest alternative I found was scrcpy, which is basically multi screen collaboration
