### ISSUE TITLE
Thunderbolt power on failed (Big Sur)

### ISSUE THREAD

**Issue by samwzlim** [profzei/Matebook-X-Pro-2018#102]
![image](https://user-images.githubusercontent.com/74489037/101116011-3ff77480-361f-11eb-9bf4-f15a7f48c864.png)

I am facing this issue on my MBXP 2018 running Big Sur (when I charge my laptop with the lid closed). I'm running MateBook X Pro EFI v1.7.0. Laptop will restart and show this error message randomly, unable to predict when this error will repeat again. I have already disabled all the hibernation related features as mentioned under power management. Prefer not to undervolt as I have no experience in doing so and wouldn't want to take the risk.

**Comment by JonnIEnglish** [comment]
Hi @samwzlim, 

Did you try and disable 'other wake up sources' in BIOS?

That worked for my battery drain while sleeping.

**Comment by samwzlim** [comment]
@JonnIEnglish Yeah, I did that, but I run into this issue now and then. Don't know what's causing it

**Comment by samwzlim** [comment]
![Uploading image.png…]()
still having issues till this day

**Comment by samwzlim** [comment]
![image](https://user-images.githubusercontent.com/74489037/102583856-5a157480-4140-11eb-94d7-d3c5a2f7e1c1.png)
still having issues till this day

**Comment by profzei** [comment]
@samwzlim  Have you tried [release v. 1.9.0](https://github.com/profzei/Matebook-X-Pro-2018/releases) with improved support for power management for Thunderbolt?

Honestly, I cannot do anything more: I do not have any Thunderbolt device...
