### ISSUE TITLE
Headphone Jack not working

### ISSUE THREAD

**Issue by samwzlim** [profzei/Matebook-X-Pro-2018#103]
When I connect my 3.5mm earphones, there is sound, but it's like distorted. It was working fine but now it's acting weirdly again. Running latest EFIs and Big Sur

**Comment by juicypop** [comment]
This is no solution but could you try other earphones? I know from experience that some jacks aren't made well and kind of tend to have distortions if they don't plug 100%. Only solution is to wiggle them left right until the distortion is gone.
Currently i have a bad jack on my USB-C adaptor that I also have to wiggle around until it plays fine, so you're not alone.

**Comment by Vatri91** [comment]
Click on sound icon on tray in right top corner and change music device on headphones

**Comment by samwzlim** [comment]
> Click on sound icon on tray in right top corner and change music device on headphones

Yep, I've done that already, and it gives me that distorted sound

**Comment by Vatri91** [comment]
So click on soudflower and set on None (off) and back on previous option. Sound will be back to normal

**Comment by samwzlim** [comment]
Nvm, I solved it myself. For anyone who is suffering from the same issue, what I did to solve this problem was to change input device to in-line mic (earphones) instead of built-in mic (laptop). Idk how this affected the sound output but it did work. Also, previously, I had the same problem when I first installed MacOS but overtime, the sound recovered on its own.
