### ISSUE TITLE
Need help with wifi

### ISSUE THREAD

**Issue by g0r3** [profzei/Matebook-X-Pro-2018#104]
Hi,

I'm in progress of collecting my first experiences with an Hackintosh. So far I'm already failing on getting it installed. I used this [1] how to to create a bootable USB stick until just before the 'Method 1" headline, choosing MacOS Big Sur.

From there on I tried to use this repo to move on. As far as I have understood it, I have to copy the BOOT and OC folder from this repo into the EFI folder of the boot stick? OpenCore already seems to be present, so I guess I don't have to install it manually? Right now I'm struggling, that no matter what I try, sometimes the touchpad doesn't work. And no matter what I do (using itlwm.kext from this repo or download it myself from [2]), Wifi never works. And since the installation requires internet, I obviously cannot proceed. A heads up for what I am doing wrong would be greatly appreciated.

[1]: https://github.com/Broly1/Hackintosh-linux-Installer
[2]: https://github.com/OpenIntelWireless/itlwm/releases

**Comment by AshleyMiller9696** [comment]
use the files in #release 
& wifi should work fine with the latest macOS version

**Comment by g0r3** [comment]
> installation is here:
> https://github.com/profzei/Matebook-X-Pro-2018/wiki/Upgrade-to-macOS-Big-Sur
> 
> use the files in #releases
> & wifi should work fine with the latest macOS version

Thanks. But I don't have a working MacOSX yet. I am trying to create a working installer stick on Linux. But so far i am failing the get past the installation from the recovery, since I never have working wifi there.

**Comment by profzei** [comment]
@g0r3 My suggestion is creating (in some way depending on your starting OS...) a USB installer stick for a full offline installation without the need of a working Wi-Fi during installation process
