### ISSUE TITLE
VoltageShift not working

### ISSUE THREAD

**Issue by hdamico** [profzei/Matebook-X-Pro-2018#105]
Hello,
I'm trying to run VoltageShift using `./voltageshift info` but gives me `-bash: ./voltageshift: Permission denied` does anyone know why?
Thanks,
Hernan D'Amico.

**Comment by dgtvc** [comment]
@hdamico 
Try to do it with `sudo` like sudo `sudo ./voltageshift info` or check for me permissions of that file with `ls -la` it will show you something like this:
> -rwxr-xr-x@  1 dgtvc  wheel  78496 12 paź 00:11 voltageshift

**Comment by hdamico** [comment]
I tried with sudo but says that the command does not exist, so I tried with root user, but I receive the same error. My permissions file are `-rw-rw-rw-@ `.

**Comment by hdamico** [comment]
Solve using `chmod 755`.
