### ISSUE TITLE
Mic not working (Hangs on itself and goes mute)

### ISSUE THREAD

**Issue by samwzlim** [profzei/Matebook-X-Pro-2018#106]
Hi! So my mic has not been working as expected, and it always goes mute by itself and also hangs (plays the last recorded sound from the mic over and over repeatedly). This is very annoying for online meetings because I have to constantly switch the input device from Internal microphone/Line in (both have the same issue) to something else, and then switch it back to get it working again temporarily. This issue is very recurrent for me. Running Big Sur and latest EFIs.

**Comment by profzei** [comment]
@samwzlim I used yesterday microphone without any issues as those you are describing...
Since you are reporting a lot of issues, maybe you could try a clean install for Big Sur... atm I need my machine in a working status so I'll do a clean install for myself only during Christmas holidays

**Comment by samwzlim** [comment]
@profzei alright, will do! Do i just boot into recovery and select reinstall MacOS? Do I have to do anything else considering this is a hackintosh? I wish it is as simple as pressing a reset button because atm I don't have time to start from step 1 :(

**Comment by samwzlim** [comment]
@profzei just wanted to confirm that a clean install is the same as just booting into recovery and reinstalling macos amiright? if i reinstall from recovery, will it have the same effect as doing a clean install? and will the system files still be there? i dont have the time to fresh install from step 1
