### ISSUE TITLE
Battery draining super fast (Big Sur)

### ISSUE THREAD

**Issue by mmenendezg** [profzei/Matebook-X-Pro-2018#107]
Hello, I wanted to know if I am the only one who is suffering the short duration of the battery. In my MBP the battery lasts Max 4 hours 30 minutes. I disabled the touchscreen as suggested in other thread, but the battery do not last more than that. I wanted to know if I am the only one or there are others with the same problem.

**Comment by dgtvc** [comment]
Hi!
From first install i can have max like 4 hours, every time ;) Now I am on big sur, but didn't notice any changes on battery life.

**Comment by profzei** [comment]
@mmenendezg @dgtvc My experience is quite different:
- my battery is only at 88% of its designed capacity... 2 years old... and used too much during last 9 months for obvious pandemic reasons...
- my battery lasts till 7 - 8 hours with light work i.e. code programming or light web surfing (**no video**) even if Safari sucks a lot imho...
- I'm using my display with the option **Automatically adjust brightness** set to `ON` (in my case this means with only two, three or four ticks in brightness level bar)
- I'm continuously monitoring `CPU Package` drain with iStats menubar and I don't see significant changes from Catalina
- I'm using my latest release v. 1.7.0 with undervolting settings... nothing more!
- but during first days after upgrading to Big Sur I too noticed fast draining... and there are **some/many** reports by Mac users (not Hackintosh...) 
[https://macreports.com/how-to-fix-big-sur-battery-drain-issues/](https://macreports.com/how-to-fix-big-sur-battery-drain-issues/)
[https://discussions.apple.com/thread/252033589](https://discussions.apple.com/thread/252033589)
...some Mac users are also suggesting to untick **Optimised battery charging** option in `Battery` tab... but I didn't notice any change for my situation...

**Comment by dgtvc** [comment]
One thing that I notice sometime ago was that soundflower take a lot power, so i changed it to SoundControl.
I can make PR with instruction for this if U want @profzei

**Comment by profzei** [comment]
> One thing that I notice sometime ago was that soundflower take a lot power, so i changed it to SoundControl.
> I can make PR with instruction for this if U want @profzei 

@dgtvc Sure! Great news! I'm using **SoundFlower** app since @huotarih suggested it... but I really like software with a very low impact on battery so **your contribution is very welcomed** (as everyone's contribution)!

During Christmas holidays I'll make a complete restructuring for this repo (atm I'm too busy...)
However, I'll make a **maintenance release** in a few days with Acidanthera team's latest updates

**Comment by mmenendezg** [comment]
@profzei I tried to do the undervolting with the tutorial you made (Thanks by the way for explaining and simplifying everything to us) but after rebooting I found in terminal the message _Command not found_. I thought it was zsh and changed to bash, sh and nothing. 

Here's the screenshot of my terminal (I am using Terminus, great terminal emulator btw):

<img width="664" alt="Screen Shot 2020-12-08 at 12 33 11" src="https://user-images.githubusercontent.com/44656927/101525932-9af7d700-3951-11eb-8ab8-4c90a53fa592.png">

I already verified in config.plist and the VoltageShift.kext is enabled (enabled = 1). I don't know if I am missing one step, or configuration in any possible file.

**Comment by profzei** [comment]
@mmenendezg ...I really need to update my guide!
Please, try the following steps:
1- `cd /Applications/Utilities`
2- `sudo chmod 755 voltageshift` 
3- `sudo ./voltageshift info`

The **second step is needed** since downloading the file `voltageshift` from my repo is resetting its attributes

**Comment by mmenendezg** [comment]
You were right! Thanks so much for the update and the support. You are the best!

**Comment by dgtvc** [comment]
@profzei i made clean install yesterday of big sur, I finally have same results on benchmark like yours :D But my battery on iStats still shows like 4-5 hours, even my battery life is 92% :D Something is wrong but for now i don't know what :D

**Comment by profzei** [comment]
@dgtvc ...honestly I really don't know!
These are some screenshots I took yesterday afternoon and this morning at different battery levels in idle conditions...
![Screenshot01](https://user-images.githubusercontent.com/47076961/101611285-9bec3f80-3a09-11eb-9922-b761b3fa542b.png)
![Screenshot02](https://user-images.githubusercontent.com/47076961/101611316-a4dd1100-3a09-11eb-85d0-656439416feb.png)
![Screenshot03](https://user-images.githubusercontent.com/47076961/101611330-a9a1c500-3a09-11eb-80b1-0a83f5ea9f4a.png)

**Comment by dgtvc** [comment]
@profzei could U tell me how u get battery with 2 decimal places and percentages per hour?

**Comment by profzei** [comment]
It's a paid app: Wattagio
