### ISSUE TITLE
Catalina running hot

### ISSUE THREAD

**Issue by rohirrim27** [profzei/Matebook-X-Pro-2018#109]
First off thank you for your work - I've starred and donated to this great project!

I installed Catalina 10.15.7 on an external SSD (Windows on my internal SSD) as it's more stable than Big Sur. Everything works great and I've managed to undervolt using Voltageshift as per your instructions. However, I'm finding that the system typically runs hotter than Windows by almost 10 degrees. Avg temp on throttlestop on windows would be between 45C-50C but on Catalina it's 55C-65C with light use.

I'm using the i5 2018 MBXP and your latest (1.70) release.

Let me know if you have any suggestions? Thanks!

**Comment by profzei** [comment]
@rohirrim27 Thank you very much for your appreciation for this repo!

I agree with you on the greater stability of a system, Catalina, that has reached version xx.7 compared to the present, Big Sur, at its xx.0.1

Unfortunately I don't have much experience on the power management of a macOS system residing on an external SSD... the only thing that comes to mind is whether the SSD is SATA or NVMe: in the first case it is essential to enable the trim for the unit using the following command in Terminal:
```
sudo trimforce enable
```

**Comment by rohirrim27** [comment]
Got it! Would love to hear if others are also facing this problem. I'm thinking of doing a fresh install later, maybe once there's a new release. Currently it gets really hot after 3-5 tabs on Chrome after 15 mins.

**Comment by profzei** [comment]
@rohirrim27 My latest [release v.1.8.0](https://github.com/profzei/Matebook-X-Pro-2018/releases) is already available, but it's only a maintenance release with support for latest OpenCore 0.6.4 and latest kexts...
The next one, not before Christmas holidays, should, instead, introduce a lot of modifications in ACPI!

**Comment by profzei** [comment]
@rohirrim27 If it could help, I released [v. 1.9.0](https://github.com/profzei/Matebook-X-Pro-2018/releases) last week...
