### ISSUE TITLE
How to upgrade this latest version from hackintosh(gnodipac886)1.1.20.1

### ISSUE THREAD

**Issue by jeffreyouni** [profzei/Matebook-X-Pro-2018#110]
Can I just simply copy the CLOVER from the latest release of this repo instead of 1.1.20.1?
And which release I need to download, the OC zip or the regular one?
What's the difference between unlocking and lock Mojave?
I don't see any guide to lead me to upgrade. I used gnodipac886's package because there is an onekey.sh can let me install easily, but I am considering upgrading.
My system version is 10.14.5 (18F132) now.
Thank you very much for helping!

**Comment by profzei** [comment]
Atm, Clover is not supported in this repo... you could only see a very very old and no longer maintained version!
Honestly I could not promise anything but perhaps, during Christmas holidays, I could give a try to actual Clover release, but not before...
