### ISSUE TITLE
Wifi auto disconnects after wakeup 

### ISSUE THREAD

**Issue by samwzlim** [profzei/Matebook-X-Pro-2018#111]
Whenever my wifi is turned on and my mbxp goes to sleep, it will auto disconnect everytime i wake it up. Wifi will still be on but no networks will be present in the connection list. A quick off and on toggle of the wifi will do the trick, but over time, that becomes really annoying fast. Any solution for this? tcpkeepalive is set to 1 and I have activated wake for network access.

**Comment by profzei** [comment]
@samwzlim What you report didn't occur every time to me... but it occurred and it is/was due to the fact that AirportItlwm is a project in its **alpha** stage (I prefer say _beta_). This means that it may be unstable as clearly stated [here](https://github.com/OpenIntelWireless/itlwm/releases)

In my latest [release v. 1.8.0](https://github.com/profzei/Matebook-X-Pro-2018/releases) (published during last night) I included the latest commit for AirportItlwm.kext... and this is only what I could do since I'm not the developer of this software... Probably, if the "issue" keeps persisting, we could figure out to create a little script for automatically re-enabling Wi-Fi, but I'm more confident that it should be already fixed! XD

**Comment by samwzlim** [comment]
@profzei just checked out v1.8.0 and had it installed into my system before posting this, but unfortunately, the issue is still persistent :( However, I understand that Airportitlwm.kext is still under beta, and is bound to run into errors, but oddly enough, this never happened until recently. I would really appreciate if you could make a script for automatically re-enabling WI-FI, but I don't need it urgently. So take your time on that :)

**Comment by samwzlim** [comment]
Update: Iinstalled the app 'Control Plane' which auto turns off wifi when the laptop is put to sleep and auto turns on wifi when the laptop wakes from sleep. Works flawlessly

**Comment by JonnIEnglish** [comment]
@samwzlim This sounds like a great solution. I can't seem to find the app though. Do you think you could link it here?

**Comment by samwzlim** [comment]
@JonnIEnglish [Here](https://github.com/dustinrue/ControlPlane/releases/download/1.6.7/ControlPlane-1.6.7.dmg)

**Comment by JonnIEnglish** [comment]
Thank you so much!

**Comment by JonnIEnglish** [comment]
@samwzlim Would it also be possible for you to share your settings for Control Plane as I am struggling to figure out how to set it up correctly?

**Comment by profzei** [comment]
@samwzlim  Thank you very much for your contribution! Great!

@JonnIEnglish @samwzlim Do you think this app could also be used for monitoring the status of Soundflowerbed? i.e. if no there is no output from Soundflowerbed for (for example) 20 minutes, then put Soundflowerbed to None status so that auto sleep could work!

**Comment by JonnIEnglish** [comment]
@profzei I have found that 'SoundSource' works much better than Sunflowerbed for volume control. I got the newest version off Allmacworld and it works very well.

**Comment by jonescamilla** [comment]
> I have found that 'SoundSource' works much better than Sunflowerbed for volume control.

I've been using Sound Source since like week 1 of me making my matebook run mac os. Just never was sure where to comment this on GitHub.

**Comment by samwzlim** [comment]
@JonnIEnglish ngl, the app was super confusing to me at first because there was almost no documentation for it, but I got it to work nevertheless.

<img width="389" alt="2021-01-06_23-07-54 846" src="https://user-images.githubusercontent.com/74489037/103784253-b0594180-5074-11eb-9e44-efd6b66048b7.png">
For evidence sources, you want to pick sleep/wake event as we want wifi to be toggled on/off during those events.

<img width="494" alt="2021-01-06_23-08-15 037" src="https://user-images.githubusercontent.com/74489037/103784293-bc450380-5074-11eb-9f45-c27e6a3a7de4.png">
For rules, just refer to the picture above.

<img width="498" alt="2021-01-06_23-08-25 475" src="https://user-images.githubusercontent.com/74489037/103784308-c0712100-5074-11eb-8dc8-6a01fa09715a.png">
<img width="498" alt="2021-01-06_23-08-28 291" src="https://user-images.githubusercontent.com/74489037/103784447-eac2de80-5074-11eb-8d8a-4e9fa36c35a2.png">
In actions, we finally pick toggle wifi on/off (I also set an action to auto reconnect my bluetooth speaker everytime mac wakes).

Have also been a user of SoundSource and only have positive comments for it. It has replaced sunflower bed as it even gives you an option to control MBXP's speakers natively (super volume feature). 

Since we are on the topic of discussing mac apps, there is 1 I've been using called Turbo Switcher Pro, which turns allows you to toggle intel turbo boost on/off. With this turned off, the performance drop isn't that significant and I actually got our mbxp to run even cooler than windows. I've set the turbo boost to disable at 65-70 celcius, and it has never exceeded that.

**Comment by JonnIEnglish** [comment]
@samwzlim Thank you for these instructions. I am having trouble with the context only showing 'Automatic' as an option and I am wondering if you also had this issue?

<img width="710" alt="Screenshot 2021-01-06 at 18 23 46" src="https://user-images.githubusercontent.com/24739247/103792453-53e22c00-504c-11eb-91e4-0673b8838fe8.png">


@jonescamilla I believe you introduced me to SoundSource quite a while back and it has been working magnificently. So thank you very much! 
But has anyone had the problem with sound cutting out and having to click on soundSource in the taskbar to reenable it?

**Comment by jonescamilla** [comment]
> But has anyone had the problem with sound cutting out and having to click on soundSource in the taskbar to reenable it? 

I can't say I've ever experienced that issue. The only issues I've experience with sound or SoundSource specifically has been with my Bluetooth headphones and the inability for them to switch between speakers (just headphones) or headset (using the microphone and the speakers).

**Comment by samwzlim** [comment]
@JonnIEnglish Have you created the contexts like I told you to? If you have, then have no idea why it doesn't show up, it does for mine. But honestly give automatic a try, I'm not 100% certain if creating new contexts are necessary

**Comment by profzei** [comment]
@samwzlim Have you seen (i.e. measured) any benefit in reduced power drain during sleep phase deactivating WiFi before sleep?

**Comment by samwzlim** [comment]
@profzei Unfortunately I can't say as I didn't measure, but if you are thinking if implementing into the next update, there's some minor annoyance such as google calendar, gmail showing the not connected error message for a few seconds right after waking from sleep

**Comment by profzei** [comment]
> Unfortunately I can't say as I didn't measure, but if you are thinking if implementing into the next update, there's some minor annoyance such as google calendar, gmail showing the not connected error message for a few seconds right after waking from sleep

I'm thinking in writing a small guide (after next release...) so that all users can use it... the purpose of this repo is not to replace that of a forum in the search for help (which remains the appropriate place for that purpose), but to create the best MBXP user experience (obviously within the limits what a hackintosh can do !!!)
