### ISSUE TITLE
Screen recording with audio

### ISSUE THREAD

**Issue by samwzlim** [profzei/Matebook-X-Pro-2018#114]
Is there any way to get screen recording with audio working for our MBXP running hackintosh? I followed youtube guides on how to record with screen audio using soundflower as well as blackhole, but for some reason it's not working. Sound can only be recorded thru the laptop's mic input, whereas what I want is to be able to screen record with internal audio, and not through the mic. When I select internal audio, no sound is recorded

**Comment by jonescamilla** [comment]
I've found success with sunflower.

The trick with it is to:
- set up a multi-output device including soundflower 2ch through midi.
- selecting that created device as your output.
- selecting that created device in your capture software of choice. (I've only used QuickTime)

**Comment by samwzlim** [comment]
@jonescamilla for the multi-output device, do i have to select any other audio device other than soundflower 2ch?

**Comment by jonescamilla** [comment]
> @jonescamilla for the multi-output device, do i have to select any other audio device other than soundflower 2ch?

Yes. I selected my Bluetooth headphones more often than anything. But I've also used the speakers and other audio devices with success.

**Comment by huotarih** [comment]
https://github.com/profzei/Matebook-X-Pro-2018/wiki/Activate-Surround-Sound-via-MIDI-on-internal-speakers check this =)

**Comment by samwzlim** [comment]
@jonescamilla I've tried what you suggested but it doesn't work :( I found out that I can only record with audio if it's played through the speakers (then the mic can pick it up with built in mic selected in input). If I use bluetooth earphones then there won't be any sound because the mic won't pick it up

**Comment by samwzlim** [comment]
@huotarih Thanks for your suggestion but that's unrelated to my question. I have already activated surround sound with no issues but am now looking to screen record with audio

**Comment by samwzlim** [comment]
@jonescamilla 
![image](https://user-images.githubusercontent.com/74489037/102313667-04a85e80-3fac-11eb-96ed-7b7f7838c964.png)
MIcrophone selected to none in Quicktime.
No audio was recorded during screen recording

**Comment by jonescamilla** [comment]
**Here's a step by step example:**

Create a Multi-Output device:
![Screen Shot 2020-12-15 at 11 47 50 PM](https://user-images.githubusercontent.com/61066815/102319844-54494480-3f30-11eb-95bc-40f24d85fdd0.png)

Add the device in which you want to listen from (your speakers, your headphones, a monitor, whatever you would like. I am using my bluetooth headphones in this scenario. I've done this not using my bluetooth headphones) and Soundflower (2ch):
![Screen Shot 2020-12-15 at 11 52 36 PM](https://user-images.githubusercontent.com/61066815/102320048-a2f6de80-3f30-11eb-9c73-11605fe788fa.png)

Name it something you'll remember:
![Screen Shot 2020-12-15 at 11 53 51 PM](https://user-images.githubusercontent.com/61066815/102320165-c91c7e80-3f30-11eb-89d8-5ece4b059394.png)

Set the output of your device to the device you just created:
![Screen Shot 2020-12-15 at 11 49 08 PM](https://user-images.githubusercontent.com/61066815/102320221-d9ccf480-3f30-11eb-8ada-be843fe78114.png)

Now set the Microphone in the options section of QuickTime to Soundflower:
![image](https://user-images.githubusercontent.com/61066815/102320307-f9641d00-3f30-11eb-8e03-8fd3cc5143b8.png)

Next time you play media through your output (in this case `example`) two things will happen. Your audio device will output the sound as normal and Quicktime will be capturing the audio.

**Comment by samwzlim** [comment]
It worked for me!! TQSM! Selecting Soundflower 2ch in the microphone input solved it for me
