### ISSUE TITLE
How to disable internal Intel Bluetooth?

### ISSUE THREAD

**Issue by t0mm4rx** [profzei/Matebook-X-Pro-2018#117]
Hello,
I have some BT 4.0 devices to pair with my hackintosh.
I bought a BT 4.0 compatible bluetooth dongle but the system is still on the internal bluetooth.
I removed the IntelBluetoothFirmware kext but the Bluetooth is still on the internal card.
Do you know how to disable this card ?
Thanks !

**Comment by profzei** [comment]
You need to disable related entry in `SSDT-UIAC`

**Comment by t0mm4rx** [comment]
I've removed the HS05 entry and recompiled but the bluetooth is still active. Thanks for your help!

**Comment by profzei** [comment]
@t0mm4rx I don't know whether you are still interested in this feature... If answer is affermative then:
- download [release v. 1.9.1](https://github.com/profzei/Matebook-X-Pro-2018/releases/tag/v1.9.1) and update your `EFI`
- reboot your system checking all is right
- then replace standard `SSDT-XHC.aml` file with the following version where I disabled both internal port `HS05` and `BT01` device
- reboot your system and check in `About this Mac -> System Report -> Bluetooth`: **No information found** is the standard message
- Then you could use your external BT 4.0 compatible bluetooth dongle!

[SSDT-XHC.aml.zip](https://github.com/profzei/Matebook-X-Pro-2018/files/5899933/SSDT-XHC.aml.zip)

Let me know if it works (if still interested) on your side, so I could close this issue!
Sorry for late reply... but I tried to fix/improve/enhance general performance and honestly I forgot this particular case!

**Comment by t0mm4rx** [comment]
Thank you for your time ! I'll try this next week and tell here the result.
