### ISSUE TITLE
Support for Samgsung PM981 SSDs

### ISSUE THREAD

**Issue by raveltan** [profzei/Matebook-X-Pro-2018#118]
I know that this project is partially based on https://github.com/gnodipac886/MatebookXPro-hackintosh hackintosh project, but do this build also has the same problem for Samgsung PM981 SSDs?

**Comment by profzei** [comment]
Hi @raveltan 
The problem for Samsung PM981 SSD is not related to this config but it's a compatibility issue for all the hackintoshes... or could you address me to any improvements about this general issue?
The common advice is replacing SSD...

**Comment by raveltan** [comment]
Ah i see, thanks for the explanation, i thought it is a config related problem
