### ISSUE TITLE
Stuck on apple logo at boot after I updated from Catalina to Big Sur 11.1 (Solved)

### ISSUE THREAD

**Issue by barbarou** [profzei/Matebook-X-Pro-2018#119]
Hello,
Stuck on apple logo at boot after I updated from catalina to Big Sur 11.1
I have tested the new release, MateBook X Pro EFI v1.8.0 but still does not work. I did everything but I still have the same problem . Any help plz.

**Comment by profzei** [comment]
What I could suggest is to go back in your Catalina system resetting NVRAM
Then install release v. 1.7.0 + reboot + another reboot where you choose to reset NVRAM
Then, if all is ok, you could try to re-update your system...

**Comment by barbarou** [comment]
> What I could suggest is to go back in your Catalina system resetting NVRAM
> Then install release v. 1.7.0 + reboot + another reboot where you choose to reset NVRAM
> Then, if all is ok, you could try to re-update your system...

I can now boot normally and it seems that everything works fine again, I just changed:
**- DmgLoading set to Signed
- SecureBootModel set to Default**

**AirportItlwm** it seems not working for me. 
Do I have to change somwthing for now bcoz I saw that you added update for 11.1:  
**Checking/rewriting some ACPI SSDTs: wip...
Restructuring repository: wip...
Re-enabling [kext] SMCBatteryManager for testing purpouses
Disabling [kext] ACPIBatteryManager**

But I do not know what I have to change? Do I have to delete ACPIBatteryManager ?
I just noticed that the laptop is getting very hot now after updating to 11,1

**Comment by profzei** [comment]
Hi @barbarou 
...ok now you followed the instructions for release v. 1.7.0
Have you also disabled loading for **HeliPort** App?

For the next two weeks, please, do not care for any changes in Changelog file: I need to restructure all the repo AND still tracking my work and tests (which will be uploaded only at the end of the process)... only in January I will re-synchronize online repo with the files (I working on) in my local repo

Please, atm, refer only to "raccomendations" on release page associated to each release version!

**Comment by barbarou** [comment]
Thank you so much @profzei 
Everything is working like before. I forgot to disable HeliPort App and I also disabled AirportItlwmCatalina. Now the 11.1 version works great without any issue after 5h using.
