### ISSUE TITLE
Log output on startup and shutdown

### ISSUE THREAD

**Issue by Roshaanv** [profzei/Matebook-X-Pro-2018#12]
Hi,

Thank you for the update. Everything seems to work fine for now, but i get log output on startup and shutdown. I have found some failed operations in the log files, but don't know if that's normal or not. I've attached the log file.

[sys_log_roshaanv.txt](https://github.com/profzei/Matebook-X-Pro-2018/files/4726026/sys_log_roshaanv.txt)

**Comment by profzei** [comment]
The failed operations you addressed to our attention seem quite usual... but I'll try to analyse them more carefully in next weeks: machine is very stable and runs very smoothly, imho.
If you don't like verbose logs you could download the following config:
[config.zip](https://github.com/profzei/Matebook-X-Pro-2018/files/4730575/config.zip)

For enabling (disabling) verbose logs you need to go in "Boot" section and add (remove) "-v" (without quotes) option in boot-arguments!
