### ISSUE TITLE
Use USB type C port, system is lagging

### ISSUE THREAD

**Issue by Tabgach** [profzei/Matebook-X-Pro-2018#121]
Hi, 

I just upgraded to big sur today, I realised that when I connect MBXP to my monitor with USB type C cable, monitor desktop is lagging,but laptop monitor is not. Please advise if there is any solution for this.

Thank you and best regards 
TabGach

**Comment by BigEmperor26** [comment]
Are you also using an external mouse? 
If so, the problem could be caused by a bug in Big Sur. It does not act nicely with high polling rate mice.
 
https://discussions.apple.com/thread/252047056?answerId=253919378022#253919378022
