### ISSUE TITLE
facetime and messages not working after updating to Big Sur

### ISSUE THREAD

**Issue by kilgil27** [profzei/Matebook-X-Pro-2018#125]
I am unable to log into FaceTime or Messages after updating from Catalina to Big Sur. Anyone else have this issue?

**Comment by profzei** [comment]
@kilgil27 Have you cloned your previous values for `MLB`, `SystemSerialNumber` and `SystemUUID` into new/updated `config.plist`? If the answer is yes, then this is not an issue for MBXP but only an issue for BS and forums are plenty of these issues... for example see [here](https://www.reddit.com/r/hackintosh/search?q=iMessage&restrict_sr=1&sort=new)

**Comment by androidek** [comment]
does Appstore work for you?

**Comment by profzei** [comment]
@profzei Yeah! No problem!

**Comment by kilgil27** [comment]
@profzei  I did not copy my previous values, no

App store is working fine for me

**Comment by profzei** [comment]
> @profzei I did not copy my previous values, no

@kilgil27 Then, please, try doing it: please, follow carefully [Dortania's guide steps](https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html) for fixing iServices

What I could add is this is not a issue due this configuration...

**Comment by kilgil27** [comment]
@profzei well I already overwrote the old config file so I guess I'm out of luck. Have been trying to generate a new serial but no luck so far. Will keep trying

**Comment by kilgil27** [comment]
Figured out what I was doing wrong. Wasn't using the generated board serial number. Everything is working correctly now!
