### ISSUE TITLE
Computer sound can be heard when I use headphones

### ISSUE THREAD

**Issue by hdamico** [profzei/Matebook-X-Pro-2018#126]
Hello,
I am having a trouble with the headphones where everything that I reproduce on my laptop can be heard on the microphone having headphones as default output device. This is really annoying specially when I have meetings because it generates an echo.
I have SoundFlowerBed installed.

Did anyone have the same problem?

Thanks in advance!

**Comment by profzei** [comment]
Honestly, I don't use much audio... but I don't have this issue... after next release I concentrate to audio section since it seems there are some changes in actual AppleALC in use...

Btw, have you seen [this](https://github.com/profzei/Matebook-X-Pro-2018/issues/111#issuecomment-755258668)?

**Comment by hdamico** [comment]
@profzei ! No I did not see that, will check now. Thank you for all the help out here!!

**Comment by hdamico** [comment]
Will close since there is no solution at the moment
