### ISSUE TITLE
Will the repository still be updated for ACPI/config.plist changes?

### ISSUE THREAD

**Issue by qosmio** [profzei/Matebook-X-Pro-2018#128]
I've been following the changes closely in the changelog for some time, and I see that you're moving towards just pushing log changes, with what I'm assuming, a final release? (1.8.0,1.7.0)

I was hoping perhaps you could still push ACPI/*.aml and config.plist changes, so I could test a long side it on my system.

Thanks!

**Comment by profzei** [comment]
@qosmio Yes! For sure... I’ll update all the repo after next release! Then I’ll be more consistent with incremental upgrades
