### ISSUE TITLE
Hot patch correction of SSDT-DDGPU

### ISSUE THREAD

**Issue by bingzujia** [profzei/Matebook-X-Pro-2018#129]
When I use ACPIDebug for correcting my hot patch of magicbook 2018 which is similar with yours. I notice that there is an ACPI Error when searching for the method of `\_SB.PCI0.RP01._OFF`. I notice that the `_OFF` method of `\_SB.PCI0.RP01` device is in the `PowerResource (PC01, 0x00, 0x0000)` section that the path of above should be `\_SB.PCI0.RP01.PC01._OFF`. After correcting this, then calling the `\_SB.PCI0.RP01.PC01._OFF()`, the status of `\_SB.PCI0.RP01` is 0.
Which may be same useful for your matebook x pro.

**Comment by profzei** [comment]
@bingzujia Thank you very much for your suggestion: **you are right**! In my `SSDT-13-KBL-ULT.aml` the `_OFF` method for `\_SB.PCI0.RP01` device is inside `PowerResource (PC01, 0x00, 0x0000)` also for Matebook X Pro.
I fix this issue!
