### ISSUE TITLE
Thunderbolt Port

### ISSUE THREAD

**Issue by Fearlesslove** [profzei/Matebook-X-Pro-2018#13]
Goodwork man! I have a question about your update, can the thunderbolt port work with eGPU?

**Comment by profzei** [comment]
Hi, honestly I don't have an eGPU for extensive tests... what I can say is: it should work... I don't know with which kind of benchmarks...
Thunderbolt ports in macOS need a different version of firmware so I need to "study" more extensively if this can be done!
