### ISSUE TITLE
Opening files in apps is painfully slow

### ISSUE THREAD

**Issue by huotarih** [profzei/Matebook-X-Pro-2018#130]
Hey :)
Just wondering if anyone else has this issue, or had, and if fixed, how.

I've been lately experiencing a ridiculous amount of lag/freezing when another app opens finder to locate a file. 
After it finally gets finder open, every single click or drag takes atleast 10 seconds to work.

Any tips are welcome. You can try by double clicking the attach files in the issue comment box, if it takes under 10 seconds, you don't have this problem :D

**Comment by profzei** [comment]
@huotarih Here no issues!

Are you using Big Sur on an external drive? Maybe an SSD and not a NVMe drive? In such case, probably, you need to enable/force trim on your external device with the following command in Terminal app: `sudo trimforce enable`

**Comment by huotarih** [comment]
I am not, I have split my internal SSD to double boot windows (which won't boot right now for some reason, goes straight to blue screen). I'll try that anyways and report back.

**Comment by profzei** [comment]
@huotarih What I suggested could be useful only for the scenario I described i.e. for installation on external disk... otherwise it is totally unuseful...
I'm sorry but I have no idea...

**Comment by eesa** [comment]
> I am not, I have split my internal SSD to double boot windows (which won't boot right now for some reason, goes straight to blue screen). I'll try that anyways and report back.

check key "bootprotect" in the config.plist, and set string value to "disabled", then you can boot to windows.

**Comment by huotarih** [comment]
Any idea how I could boot in safe mode? Holding shift doesn't seem to work.

**Comment by profzei** [comment]
@huotarih I'm not sure since I never need this feature before... but I guess you need to enable macOS hot keys during OpenCanopy picker boot menu... therefore, probably, you need to set `Misc -> Boot -> PollAppleHotKeys` entry to `true` value in `config.plist`

**Comment by huotarih** [comment]
Both of your suggestions worked, but the problem still endures. I know I seem to be alone with this problem, but this is something i really need to solvtried sudo fs_usage -f pathname -w com.apple.IconServicesAgent | grep open e.
I found out that it doesn't occur in guest account. So something with my account is broken.
I've
