### ISSUE TITLE
Unable to update to release `v1.9.0`

### ISSUE THREAD

**Issue by jonescamilla** [profzei/Matebook-X-Pro-2018#131]
**The issue:** 
- I am unable to update to the latest release of this repository.
    - When replacing the folders `BOOT` & `OC` from the previous `v1.8.0` release with the new `BOOT` & `OC` folders from release `v1.9.0` the system no longer normally boots.
    - The computer crashes when the progress bar under the apple logo reaches about 2%.
<br/>

**Attempted solutions:**
- Clearing the nvram
- Setting `csrutil` to `disabled` through recovery (this has solved an issue for me in the past)
- Adding the "Battery Manager for macOS" ![image](https://user-images.githubusercontent.com/61066815/104642879-59e59780-5660-11eb-9eca-8bad70c1998f.png)
<br/>

**What I made this issue for:**
- I would love any help as to what I may have missed when trying to update.
- Any comments on other's successful updates and what they did differently than myself.
- Open a discussion in the situation that this failed update attempt isn't isolated to myself.
<br/>
<br/>

_**If you need any additional information please feel free to ask.**_

**Comment by Trader05** [comment]
I am having the same issue on my 2018.

**Comment by profzei** [comment]
@Trader05 @jonescamilla 
What I could suggest is
- trying a real clean install
- trying to add/modify the content of one folder at time during update process (i.e. debugging carefully your particular situation)

Mine is very stable and [same here](https://github.com/profzei/Matebook-X-Pro-2018/issues/135#issuecomment-765357290)!

**Comment by jonescamilla** [comment]
> I am having the same issue on my 2018.

Would you describe the result of an attempted update to be similar to mine? Or different? (Unable to boot, with crashes 2 seconds in)

Did you approach updating your system any different than how I did? (Replacing folders in `EFI`)

**Comment by profzei** [comment]
@jonescamilla 
1. Have you tried to install a **debug** version for **OpenCore** and see what are the results go the crash?
2. Have you tried to update just old version files with their newer version and only after adding one by one other files?
You need to find what is the offending file or patch inside `config.plist` applying one change at a time...

**Comment by Trader05** [comment]
Since upgrading to Big Sur I have no issues with 1.9.1.

**Comment by jonescamilla** [comment]
At least for my specific situation, I am running Big Sur. I may get to debugging the issue sometime next week.

**Comment by jonescamilla** [comment]
Clean wipe allowed for install :/

**Comment by profzei** [comment]
Good to know
