### ISSUE TITLE
Matebook X Pro 2019 support

### ISSUE THREAD

**Issue by cnpog** [profzei/Matebook-X-Pro-2018#132]
Computer model | Huawei Matebook X Pro 2019 (MACHR-WX9) Space Gray
-- | --
Processor | Intel Core i5-8265U Processor @ 1.6 GHz
Memory | 8 GB LPDDR3 2133 MHz
Hard Disk | Samsung PM981(MZVLB512HAJQ-00000 Firmware: EXA7301Q)
Integrated Graphics | NVIDIA GeForce MX250 / Intel(R) UHD Graphics 620
Screen | JDI 3k Display @ 3000 x 2000 (13.9 inch)
Sound Card | Realtek ALC256
Wireless Card | Intel(R) Wireless-AC 9560 160MHz
Bluetooth Card | Bluetooth 9460/9560 Jefferson Peak (JfP)

Hi,
I was wondering if there is any chance of getting a working Hackintosh for the 2019 Model.
Almost all the information I found was about the 2018 Model and the few things I found seemed to be outdated for a long time.
I would be happy to test anything you got but since the hardware is quite a bit different I don't think I can just take the release from this repo to try it out.
Thank you

**Comment by profzei** [comment]
@cnpog You are right: you cannot just take the release from this repo because there are many differences in our DSDTs.

However, in late November I helped a guy to install Catalina to a Matebook X Pro 2019. I share with you the EFI I created for him after a lot of efforts for USB-install.
[Efi for MBXP 2019](https://drive.google.com/file/d/13MSVMXSyLqG7Bj27p2ygz3OG5GZ_B7XC/view?usp=sharing)
Then this guy updated flawlessly to Big Sur.

IMHO, however, you could have a big problem: your SSD is a Samsung PM981 and, if I remember well, it could/should be not compatible with macOS. You need to dig more before attempting the install.
Good luck!

**Comment by cnpog** [comment]
@profzei Thank you so much for this. I guess I will just buy an additional nvme then to save the hassle. Is there any trouble free and fast nvme that you could recommend?

**Comment by profzei** [comment]
@cnpog I'm not an expert... I would only suggest you to take into account not only speed but also thickness i.e. a single-sided or a double-sided m2 ssd.
You should find some useful info in subreddit [**r/MatebookXPro**](https://www.reddit.com/r/MatebookXPro/) for example:
[https://www.reddit.com/r/MatebookXPro/comments/ba7j17/doble_sided_ssd_fits_m2_slot/](https://www.reddit.com/r/MatebookXPro/comments/ba7j17/doble_sided_ssd_fits_m2_slot/)
[https://www.reddit.com/r/MatebookXPro/comments/e33frw/ssd_replacement/](https://www.reddit.com/r/MatebookXPro/comments/e33frw/ssd_replacement/)
[https://www.reddit.com/r/MatebookXPro/comments/efvdd6/replacement_ssd_thickness/](https://www.reddit.com/r/MatebookXPro/comments/efvdd6/replacement_ssd_thickness/)
and [https://dortania.github.io/Anti-Hackintosh-Buyers-Guide/Storage.html](https://dortania.github.io/Anti-Hackintosh-Buyers-Guide/Storage.html)

**Comment by cnpog** [comment]
@profzei I ended up buying this one ADATA SX8200PNP.
Everything worked without me needing to do anything. (I don't know yet if I can use hibernation or if I can undervolt, I need to check that. I just did the base installation using the files you provided, nothing else)
Model identifier for SMBIOS: MacBookPro15,4

**Comment by profzei** [comment]
@cnpog Great news! ;-)

**Comment by cnpog** [comment]
@profzei I got anoher question regarding SSDTs. I read the OpenCore guide multiple times but I still do not really understand where all the 31 SSDTs are coming from in your release while in the EFI you provided for the 2019 model, there is one DSDT only. Did you extract them all from your system, if so, how? (SSDTTime also gave me 1 file only) Or are these mostly prebuilt and if so, do they need modification? I would like to be able to update the EFI you provided / make your releases compatible to the 2019 version.

**Comment by profzei** [comment]
> I got anoher question regarding SSDTs. I read the OpenCore guide multiple times but I still do not really understand where all the 31 SSDTs are coming from in your release while in the EFI you provided for the 2019 model, there is one DSDT only.

I learned a lot reading OpenCore guide... but then I digged more and more analyzing (perhaps) more than twenty DSDTs coming from machines similar to Matebook X Pro 2018, finding similarities and differences with MacBookPro 14,1 which is my reference since it has the same architecture... and then I created my SSDTs which in many parts are very similar to those you could find suggested on OpenCore guide!

If you analyze my Changelog you could see that I worked a lot during last nine months to learn more and more improving and changing the same files many and many times!

For your unique DSDT the answer is different: when I helped the guy I mentioned above I didn't have a lot of time so I found/modified an old patch, made probably by the author/maintainer of the repo about Matebook 2019 which I forked, adapting it for OpenCore purpouses!

The first step for getting a copy of your DSDT + original SSDTs is... [reading OpenCore guide](https://dortania.github.io/Getting-Started-With-ACPI/Manual/dump.html#from-windows)! XDXDXD

**Comment by cnpog** [comment]
I followed the guide step by step and then I tried to boot with the created SSDTs instead of that one DSDT that you provided. It is not as of yet, trying to resolve it since then but I do not really know if I am missing any files, since I did everything that the guide said. Could you please take a look at my repo it and give me some hints?

**Comment by mtimms1980** [comment]
> @cnpog You are right: you cannot just take the release from this repo because there are many differences in our DSDTs.
> 
> However, in late November I helped a guy to install Catalina to a Matebook X Pro 2019. I share with you the EFI I created for him after a lot of efforts for USB-install.
> [Efi for MBXP 2019](https://drive.google.com/file/d/13MSVMXSyLqG7Bj27p2ygz3OG5GZ_B7XC/view?usp=sharing)
> Then this guy updated flawlessly to Big Sur.
> 
> IMHO, however, you could have a big problem: your SSD is a Samsung PM981 and, if I remember well, it could/should be not compatible with macOS. You need to dig more before attempting the install.
> Good luck!

I stumbled upon this after having some success with EFI from another repo, but this one works so much better on my 2019 i5, thank you! 

The only real issue for me is the lack of working camera. Is this something I would need to create my own SSDTs to fix do you think? Currently I am using just the EFI you provided in this post.

**Comment by profzei** [comment]
@mtimms1980 Thank you for your appreciation...
Honestly it's quite weird aht you reported since internal camera is on HS07 and this port should be set as active (I just checked it)... I didn't make any other changes in my case for getting my camera as working...

**Comment by mtimms1980** [comment]
> @mtimms1980 Thank you for your appreciation...
> Honestly it's quite weird aht you reported since internal camera is on HS07 and this port should be set as active (I just checked it)... I didn't make any other changes in my case for getting my camera as working...

It looks like the OS recognises a device, system information shows a device with Model ID and Unique ID and applications such as Teams show "HD Camera" as a device but there is no image, and no LED to tell me the camera is active when it is open and an app is using it...

**Comment by profzei** [comment]
For example, have you tried Google Meet, just for excluding an issue due to Teams support?

**Comment by mtimms1980** [comment]
Same with Google Meet, camera is detected but just black. 
<img width="791" alt="Screenshot 2021-02-09 at 20 24 47" src="https://user-images.githubusercontent.com/44544927/107424039-1114e780-6b15-11eb-9ec3-4ad97326d155.png">

**Comment by profzei** [comment]
@mtimms1980 
Your camera specifications are different from ours: `2b7e:128f` vs `03c0:05c8`. Your model vendor seems to be **Kingcome** while ours is **Foxlink**; therefore your issue could be due to a macOS driver support...

**Comment by mtimms1980** [comment]
Ah! Quite possibly out of luck then! Shame, that is the only thing that visibly does not work... other than that macOS runs GREAT on this laptop with your EFI files! Even battery life is good!

**Comment by cnpog** [comment]
@mtimms1980 Are you running a 4k external display? I just can't get it to work. 1080p 120Hz is working but not 4k, does not make any sense.
How did you fix that for the 2018 Model @profzei ?

**Comment by mtimms1980** [comment]
Not running 4K display I am afraid, worked fine on an external 1080p display but haven't tried anything else yet. I can try my TV I guess, that is 4K. I'll get back to you.

Do you occasionally have the trackpad not working after resuming from sleep?

**Comment by profzei** [comment]
@cnpog 
Default settings for
```
<key>framebuffer-con1-enable</key>
<data>AQAAAA==</data>
<key>framebuffer-con1-flags</key>
<data>xwMAAA==</data>
<key>framebuffer-con1-has-lspcon</key>
<data>AQAAAA==</data>
```
worked fine!

**Comment by cnpog** [comment]
@mtimms1980 Yes sometimes the touchpad freezes. But I did not have it for a long time. You can look at here for possible fixes https://dortania.github.io/OpenCore-Post-Install/universal/sleep.html
@profzei Unfortunately those settings did not do anything for me :(

**Comment by cnpog** [comment]
If anyone got 4k output working please let me know how. I am losing my mind over this

**Comment by hehuichao** [comment]
set dvmt=64M already？

**Comment by cnpog** [comment]
@hehuichao how?

**Comment by hehuichao** [comment]
> @hehuichao how?

Follow Laozhiang's tutorial

https://github.com/laozhiang/MateBook_13_14_XPro-Hackintosh/tree/master/bios%E8%AE%BE%E7%BD%AE%E5%B7%A5%E5%85%B7%E5%8C%85

**Comment by hehuichao** [comment]
> @hehuichao how?

4K 30Hz output perfect on my computer

**Comment by cnpog** [comment]
@hehuichao only 30Hz, not 60Hz?

**Comment by hehuichao** [comment]
> @hehuichao only 30Hz, not 60Hz?

Yes，work only 30Hz on my display device（AOC U2879VF）

**Comment by hehuichao** [comment]
> @hehuichao only 30Hz, not 60Hz?

Yes，work only 30Hz on my display device（AOC U2879VF）
