### ISSUE TITLE
Soundflower audio crackling

### ISSUE THREAD

**Issue by KristianUSN** [profzei/Matebook-X-Pro-2018#134]
Not sure if this is the right place to report this but following your guide to activate surround sound and using SoundFlowerBed to use volume keys, I experience sound crackling/pops. They're not _severe_ and the frequency varies but it's enough to be very annoying. This happens whether I'm watching a movie, youtube or listening to music. It happens whether I'm using the built in laptop speakers, audio through HDMI or Bluetooth headphones. It does _not_ happen when I'm using the normal audio options in MacOS, only when using SoundFlower as the audio output.  I've tried adjusting the buffer size and sample rate but nothing fixes it. Any ideas? Again, just not using SoundFlower fixes it but then I'm stuck with no audio keys.

Also thanks for you phenomenal work on this, it's running like a dream 😄

**Comment by profzei** [comment]
@KristianUSN Honestly not many ideas about that!
Following [these suggestions](https://github.com/profzei/Matebook-X-Pro-2018/issues/111#issuecomment-755343219) I switched to SoundSource which is not a free app! ...which is working really great!

**Comment by KristianUSN** [comment]
Just tried out SoundSource and yes it seems to fix my issues while also being a pretty great app on its own. Thank you!
