### ISSUE TITLE
Hotkey functions for F7, F9 and F10 keys

### ISSUE THREAD

**Issue by R-Teer** [profzei/Matebook-X-Pro-2018#135]
Hey Prof, hope you are well!

I'm looking to implement hotkey support for the mute key, wifi key and huawei manager keys on Mac os, from my understanding these keys do not have scancodes as they require EC queries to operate. Is there any way to implement a function to route these to f16, f17 and f18 for example thus allowing custom shortcuts using something like bettertouch tool?

I currently have my FN lock enabled and have those keys routed to F7 (Siri) F8 (Mission Control) F9 (Open Browser) and F10 (Open Mail.app). The issue with this is that I can route all keys on the top row to their respective functions however it disables the keyboard backlight key and I can no longer use the actual F key shortcuts as they have been remapped, which is not really an issue for me as I rarely use them.

If we could implement a better solution we could allow people to use these for custom shortcuts such as media keys for example?

**Comment by profzei** [comment]
Hi @R-Teer hope you are ok and well too!

> I'm looking to implement hotkey support for the mute key, wifi key and huawei manager keys on Mac os, from my understanding these keys do not have scancodes as they require EC queries to operate. 

I agree with you...

> Is there any way to implement a function to route these to f16, f17 and f18 for example thus allowing custom shortcuts using something like tool?

Probably, we need to remap those default keys with SSDT-PS2K using ADB code? I've seen some examples in past but I didn't study them 😅 

I need to find them... and I'll try!

Btw, have you tried last release?

Could you check if my "fix" to your theme is ok i.e. consistent?

**Comment by R-Teer** [comment]
I've been using the latest release for the past 12 days and its performing wonderfully @profzei 

Excellent work, the bootloader is still working great and I've seen a dramatic increase on battery performance personally.

No crashes or issues as of yet but I will keep you posted!

**Comment by profzei** [comment]
@R-Teer Thank you for your feedback!

**Comment by profzei** [comment]
@R-Teer Maybe I figure out how to remap F7, F9, F10 keys to F16, F17 F18... but I probably won't have the chance to dedicate myself to testing before next Thursday.

Btw, could you check my new update in [release section](https://github.com/profzei/Matebook-X-Pro-2018/releases/tag/v1.9.1)? It should improve just a little more battery life...

**Comment by R-Teer** [comment]
updating to latest release as I write this! Amazing work bud! Do you have a copy of the updated SSDT file I can test it for you in the meantime and provide feedback?

**Comment by profzei** [comment]
@R-Teer Here updated `SSDT-KBD` file: not yet tested!
[SSDT-KBD.aml.zip](https://github.com/profzei/Matebook-X-Pro-2018/files/5868664/SSDT-KBD.aml.zip)
You also need to add the following ACPI patches:
```
<dict>
        <key>Comment</key>
	<string>Rename EC0._Q10,0,N to XQ10</string>
	<key>Count</key>
	<integer>0</integer>
	<key>Enabled</key>
	<true/>
	<key>Find</key>
	<data>X1ExMAA=</data>
	<key>Limit</key>
	<integer>0</integer>
	<key>Mask</key>
	<data></data>
	<key>OemTableId</key>
	<data></data>
	<key>Replace</key>
	<data>WFExMAA=</data>
	<key>ReplaceMask</key>
	<data></data>
	<key>Skip</key>
	<integer>0</integer>
	<key>TableLength</key>
	<integer>0</integer>
	<key>TableSignature</key>
	<data></data>
</dict>

<dict>
        <key>Comment</key>
	<string>Rename EC0._Q12,0,N to XQ12</string>
	<key>Count</key>
	<integer>0</integer>
	<key>Enabled</key>
	<true/>
	<key>Find</key>
	<data>X1ExMgA=</data>
	<key>Limit</key>
	<integer>0</integer>
	<key>Mask</key>
	<data></data>
	<key>OemTableId</key>
	<data></data>
	<key>Replace</key>
	<data>WFExMgA=</data>
	<key>ReplaceMask</key>
	<data></data>
	<key>Skip</key>
	<integer>0</integer>
	<key>TableLength</key>
	<integer>0</integer>
	<key>TableSignature</key>
	<data></data>
</dict>

<dict>
        <key>Comment</key>
	<string>Rename EC0._Q13,0,N to XQ13</string>
	<key>Count</key>
	<integer>0</integer>
	<key>Enabled</key>
	<true/>
	<key>Find</key>
	<data>X1ExMwA=</data>
	<key>Limit</key>
	<integer>0</integer>
	<key>Mask</key>
	<data></data>
	<key>OemTableId</key>
	<data></data>
	<key>Replace</key>
	<data>WFExMwA=</data>
	<key>ReplaceMask</key>
	<data></data>
	<key>Skip</key>
	<integer>0</integer>
	<key>TableLength</key>
	<integer>0</integer>
	<key>TableSignature</key>
	<data></data>
</dict>
```
If it works, then, please, share how (for example a link to a valuable guide you followed) you add custom shortcuts (I never configured them before... XD).

**Comment by R-Teer** [comment]
This is working brilliantly man.  Ill write up a guide for the hotkey assignment later today for you and post it.

Great work!!! The new release is working perfectly on my end, no issues so far what-so-ever!

**Comment by profzei** [comment]
@R-Teer Very good news! Thank you very much!

**Comment by profzei** [comment]
@R-Teer Would you like to submit a PR for your guide?

**Comment by R-Teer** [comment]
Sorry dude, been super busy the past week with work. Adding to a PR now

**Comment by profzei** [comment]
@R-Teer Thank you very much! `Readme` updated with your hints!

**Comment by profzei** [comment]
@R-Teer I updated yesterday [your guide](https://github.com/profzei/Matebook-X-Pro-2018#optional) adding a more native approach using **Automator** for [mimic original](https://github.com/profzei/Matebook-X-Pro-2018/wiki/Add-custom-shortcuts-to-Fn-hotkeys) (apart from `F10`) Matebook X Pro hotkeys...

**Comment by profzei** [comment]
@R-Teer I updated yesterday [your guide](https://github.com/profzei/Matebook-X-Pro-2018#optional) adding a more native approach using **Automator** for [mimic original](url) (apart from `F10`) Matebook X Pro hotkeys...

...now I need to find an `EC` call for power on/off microphone led when pressed! XDXD
