### ISSUE TITLE
MBXP 2018 won't sleep when selecting sleep from menu bar

### ISSUE THREAD

**Issue by sigma941** [profzei/Matebook-X-Pro-2018#136]
I have a 2018 MBXP i7. just did a fresh install of Big Sur 11.0.1 with 1.9.0. Whenever I try selecting Sleep from the menu bar, the screen will go black, the keyboard with then shut off, then 1 second after, the laptop will wake itself back up. the computer does seem to sleep when the lid is closed. This is an issue I've been having on past versions of the distro. and I've tried to both using and not using your sleep/hibernate settings. Currently, I am not using them.   Any Ideas? Thanks in advance!!

**Comment by profzei** [comment]
@sigma941 Yeah: yesterday I updated sleep settings... try the following commands:
1. `sudo pmset -a restoredefaults`
2. `sudo pmset -a standby 0`
3. `sudo pmset -a powernap 0 `
4. `sudo pmset -a proximitywake 0`
5. `sudo pmset -a tcpkeepalive 0`
6. `sudo pmset -a womp 0`

Then go to `System Preferences` -> `Bluetooth` -> `Advanced` and untick ALL options

Let me know if this fix your machine!

**Comment by sigma941** [comment]
Apologies for not responding sooner! Still having that issue. Part of me wonders if it might be with the MBXP or something? I have this issue in windows as well. is there a way to reset everything to stock, or if it has some kind of eeprom issue? I'm also on the most current BIOS.

**Comment by leffz** [comment]
Hi! i have completely the same problem with my matebook, did u find any solution? i checked everything i can, applied all the settings above, but nothing helped. Despite everything else is working fine i can't use my laptop without sleep function.

**Comment by leffz** [comment]
Here is what i got yesterday! I made my MBXP go to sleep by setting Other Wakeup Source to DISABLE in BIOS.
![image](https://user-images.githubusercontent.com/18469512/118225799-6fdc5b00-b48e-11eb-8f87-3d7a71d2e10d.png)

After that sleep mode began to work, but u can wakeup your mac only with power button. If i set it to enable again, i can't use sleep function again.

@profzei do u have the same behavior? what's your settings?

**Comment by profzei** [comment]
@leffz If you disable in BIOS `Other Wakeup Source` then your machine could wakeup **only** with power button: this is the intended behaviour...
I didn't disable that BIOS entry
My settings are reported in homepage: with those settings sleep is working fine for me
