### ISSUE TITLE
Catalina 10.5.7, wifi and bluetooth not working  on 1.9.1

### ISSUE THREAD

**Issue by robvalca** [profzei/Matebook-X-Pro-2018#138]
Hi! thanks a lot for this great work.
Tried today to upgrade from version 1.8.0 to 1.9.1 and after boot I have no wifi nor bluetooth.
I have the exact model as the one specified on the README (but Toshiba ssd)
Reverted to 1.8.0 and worked fine. 
I'm happy to help debugging this.
Best

**Comment by profzei** [comment]
This seems not an issue but maybe an oversight!

If you use macOS Catalina you need to make the following changes in the `config.plist` to make `AirportItlwm` support active:
- `DmgLoading` set to `Signed`
- `SecureBootModel` set to `Default`

At the moment, most users use Big Sur so default settings are meant for that version. The instructions I have reported above are present in the [1.7.0 release](https://github.com/profzei/Matebook-X-Pro-2018/releases/tag/v1.7.0).

Please, let me know your feedback!

**Comment by Kokkolabs** [comment]
Yes, with Bigsur all working fine, just updating.
So do these changes in config.plist.

**Comment by robvalca** [comment]
> This seems not an issue but maybe an oversight!
> 
> If you use macOS Catalina you need to make the following changes in the `config.plist` to make `AirportItlwm` support active:
> 
> * `DmgLoading` set to `Signed`
> * `SecureBootModel` set to `Default`
> 
> At the moment, most users use Big Sur so default settings are meant for that version. The instructions I have reported above are present in the [1.7.0 release](https://github.com/profzei/Matebook-X-Pro-2018/releases/tag/v1.7.0).
> 
> Please, let me know your feedback!

oh! sorry, forgot to change that. Did the change, booted on 1.9.1 and now works as expected, thanks !

**Comment by profzei** [comment]
@robvalca Good news!
...and thank you very much for your tip/appreciation!
