### ISSUE TITLE
Airdrop

### ISSUE THREAD

**Issue by jam396** [profzei/Matebook-X-Pro-2018#14]
Would airdrop be possible at all now there is a functioning kext for the Intel WiFi, or is this likely impossible?

**Comment by profzei** [comment]
AFAIK, it isn't yet supported... WiFi kext is still in beta phase: huge progress made in few months... Hope to see the same trend during next months!
I really need native WiFi working so my attention is "daily" focused on keeping updated my repo!

**Comment by jam396** [comment]
Ah yes thought so. It's amazing how much progress has been made, I remember trying hackintosh a year ago and the idea of being able to use the onboard wifi was unheard of. Keep up the good work!
