### ISSUE TITLE
Upgraded to 1.9.1 No Schema Issues on boot

### ISSUE THREAD

**Issue by wiregen** [profzei/Matebook-X-Pro-2018#141]
Hello,

I'm having weird issues with this update. So the only changes I made is I generated a new SMBIOS for macbookpro14,1, I was running a macbookpro15,1 SMBIOS.

Aside from that, I enabled the thunderbolt edits since I use my thunderbolt external NVME drives.

On boot I'm getting these No Schema errors.
No Schema for LauncherOption at 3 index, context <boot>
No Schema for LauncherPath at 4 index, context <boot>
No Schema for MaxBiosVersion at 1 index, context <Generic>
No Schema for UseRawUUidEncoding at 7 index, context <PlatformInfo>
No Schema for SetApfsTrimTimeout at 15 index context <quirks>

**Comment by profzei** [comment]
@wiregen Simple! I do not update my machine and therefore my `config.plist` to OpenCore 0.6.6... 
You are using OpenCore 0.6.6 with a `config.plist` designed for OpenCore 0.6.5

**Comment by wiregen** [comment]
> @wiregen Simple! I do not update my machine and therefore my `config.plist` to OpenCore 0.6.6...
> You are using OpenCore 0.6.6 with a `config.plist` designed for OpenCore 0.6.5

You're correct! Downgraded to Opencore Configurator to the previous version that uses OpenCore 0.6.5 and it's now fully working!

I have some quick questions for you.
1. Enabling Thunderbolt. Is this the correct step?
- Disable SSDT-DTB3.aml
- Enable all SSDT-TB -DSB0 through DSB6 aml

2. SMBIOS ROM Field - So I generated a new SMBIOS. Question about the rom field. It's currently 11 22 33 44 55 66 - I left it as is. Should it be my MateBook's MAC ID or is it safe to leave as is?

**Comment by profzei** [comment]
@wiregen 
For Thunderbolt:
1. Disable SSDT-DTB3.aml
2. Enable all SSDT-TB-DSB*.aml files
3. Enable TB3: _GPE.NTFY,1,S to XTFY binary patch
4. Enable TB3: RP9._INI,0,N to XINI binary patch

For SMBIOS ROM Field: it should be safe to leave it as it is since I didn't have any issues with iServices!
