### ISSUE TITLE
Update to OpenCore 0.6.6 with Big Sur 11.2

### ISSUE THREAD

**Issue by bfrorum10** [profzei/Matebook-X-Pro-2018#143]
Hello together,

did anyone have updated to last version of OC 0.6.6 wit Big Sur 11.2? I like to try it but I read that the change in the OC new version hasn't a Bootstrap folder. is that possible to update it without Bootstrap folder?

**Comment by profzei** [comment]
@bfrorum10 
Honestly, at the moment, I'm very busy with my work... until next weekend! Then I will upgrade present installation to OpenCore v. 0.6.6: however, I do not think there is any new significant feature for our MBXP or any bug fixes relevant to us!
The actual config seems to me quite rock solid!

**Comment by bfrorum10** [comment]
Okey profzei! Thank you very much.

**Comment by bfrorum10** [comment]
Hey profzei! 

The Donate button is don't working. That loaded and loaded always. I think you need a cup of coffee;)

**Comment by profzei** [comment]
@bfrorum10 I really need cup of coffee... I worked too much (in real life)! Ahahah!
However Donate link should work (just checked!) .)

**Comment by bfrorum10** [comment]
I tried it on my IPhone.  but did not work.  now I've tried again with my Matebook.  so it worked.

**Comment by profzei** [comment]
@bfrorum10 Thank you very much for your appreciation! 😁

**Comment by profzei** [comment]
@bfrorum10 
I just released [v. 2.0.0](https://github.com/profzei/Matebook-X-Pro-2018/releases). As said before, `OC v. 0.6.6` didn't introduce any interesting feature for our device... please, if you would like to update your device, pay attention to **Dortania's note** [Updating Bootstrap from 0.6.5 to 0.6.6](https://dortania.github.io/OpenCore-Post-Install/multiboot/bootstrap.html#updating-bootstrap-in-0-6-6) **otherwise you could not boot anymore** (without some efforts) **into your macOS system!**

**Comment by bfrorum10** [comment]
Hey thank you! I want to try it.  if it doesn't work then I leave it with the alteb version :)

**Comment by bfrorum10** [comment]
i installed it. And made two changes.

1- Misc-Boot-HideAuxiliary to YES
better to see only the MacOs logo. You can always open the other menus with the space bar.
2- Update Voodoo.kext to last update.

Thank you again bro!

**Comment by profzei** [comment]
@bfrorum10 

> 2- Update Voodoo.kext to last update.

Please, report here if there were any fallback using `VoodooI2C` latest release: atm I'm not yet interested in updating them since `Multi-GPI0` seems not to be really fixed...

**Comment by bfrorum10** [comment]
okay I'll do. Thanks again.
