### ISSUE TITLE
100% kernel cpu, PerfPowerServices

### ISSUE THREAD

**Issue by unverbraucht** [profzei/Matebook-X-Pro-2018#147]
Hi @profzei,

first thanks for this project, one of the most painless Hackintoshes I ever made.

I've been observing high battery drain after waking up the device from hibernation using 1.9.1. This has happened a few times. One core is running 100% kernel time, and PerfPowerServices use about 15-20% of another core. This looks like this in top:

```
Load Avg: 3.78, 4.13, 6.41  CPU usage: 3.93% user, 18.35% sys, 77.71% idle  SharedLibs: 582M resident, 93M data, 126M linkedit. MemRegions: 77369 total, 4397M resident, 261M private, 2135M shared.
PhysMem: 15G used (3087M wired), 978M unused.  VM: 2838G vsize, 2305M framework vsize, 0(0) swapins, 0(0) swapouts. Networks: packets: 720384/780M in, 65832/54M out.
Disks: 1108030/7725M read, 189134/5638M written.

PID   COMMAND      %CPU      TIME     #TH    #WQ  #PORT MEM    PURG   CMPRS PGRP PPID STATE    BOOSTS         %CPU_ME %CPU_OTHRS UID  FAULTS   COW    MSGSENT   MSGRECV   SYSBSD    SYSMACH   CSW       PAGEI
0     kernel_task  114.4     55:20.20 206/9  0    0     542M-  0B     0B    0    0    running   0[0]          0.00000 0.00000    0    9403491+ 2616   54559081+ 42546402+ 0         0         56795420+ 0
3653  PerfPowerSer 11.7      03:26.41 8      6    271   4804K  256K   0B    3653 1    sleeping *1[9]          0.00000 0.00000    0    7789     256    3259281+  2436901+  6647283+  4856844+  4279124+  9
2155  Terminal     8.9       01:07.00 8      2    333   93M+   21M    0B    2155 1    sleeping *0[1913]       0.18705 0.02892    501  479795+  507+   994583+   172510+   611703+   1879297+  861457+   518
517   Notification 6.3       03:17.40 6      3    322   27M    512K   0B    517  1    sleeping *0[809]        0.00000 0.00000    501  34032    710    5169227+  3757000+  6494480+  19494794+ 4889367+  629
148   WindowServer 6.0       11:03.56 14     5    2316  490M+  14M    0B    148  1    sleeping *0[1]          0.06641 1.08641    88   978084+  52053  25640199+ 8908289+  23189574+ 36208972+ 6969579+  1651
4217  top          4.2       00:06.58 1/1    0    25    6164K  0B     0B    4217 2190 running  *0[1]          0.00000 0.00000    0    49051+   91     1318516+  659153+   191008+   993356+   13200+    0
233 
```

Or in Activity Monitor:
<img width="906" alt="Screenshot 2021-02-13 at 08 48 25" src="https://user-images.githubusercontent.com/1876063/107844971-50bf2600-6dd8-11eb-9df0-ebd47b07b07b.png">

When looking into the console I see it logs a few hundred lines per second:
```
default	08:45:13.373917+0100	kernel	Restarting poll type 2
default	08:45:13.375749+0100	kernel	SmartBattery: notification received in message()
default	08:45:13.375807+0100	kernel	PMRD: clamshell closed 0, disabled 0/0, desktopMode 0, ac 0
default	08:45:13.375910+0100	loginwindow	clamshellStateChanged | Clamshell state changed: closed=0, shouldSleepWhenClosed=2
default	08:45:13.375812+0100	kernel	PMRD: clamshell closed 0, disabled 0/0, desktopMode 0, ac 0
default	08:45:13.375937+0100	kernel	Restarting poll type 2
default	08:45:13.377857+0100	kernel	SmartBattery: notification received in message()
default	08:45:13.377887+0100	kernel	PMRD: clamshell closed 0, disabled 0/0, desktopMode 0, ac 0
default	08:45:13.377891+0100	kernel	PMRD: clamshell closed 0, disabled 0/0, desktopMode 0, ac 0
default	08:45:13.377969+0100	loginwindow	clamshellStateChanged | Clamshell state changed: closed=0, shouldSleepWhenClosed=2
default	08:45:13.378128+0100	kernel	Restarting poll type 2
```
This might explain the usage of PerfPowerServices? I'm running 11.2.1 with your release 1.9.1 and 0.6.6 opencore. Next I'll reboot to see if it is related to the Hibernation.

**Comment by unverbraucht** [comment]
After rebooting the issue went away. I did not close the lid and let the device hibernate automatically. It did not show the issue after waking up.

**Comment by profzei** [comment]
@unverbraucht Thank you!
When you say that the issue you reported has happened a few times could you specify the temporal range, please? One week... one month... after some BS update, after some OC update?

Atm I'm using `hibernatemode 3` and not `hibernatemode 25` and all is working fine: I tested `hibernatemode 25` using BS 11.0.1 and 11.1 not current 11.2.1 but I'll try asap!

Please, report here any update!

**Comment by unverbraucht** [comment]
I installed the Hackintosh about three weeks ago and the issue was there from the start. I have not changed OC version but have updated to 11.2.1, although the issue was there before. I have woken the laptop up a few times recently from hibernation and the issue did not appear, but I have not used the lid for sleep and/or wakeup. I will now try to hibernate it with the lid to see if I can trigger it again.

I'm also using hibernatemode 3.

**Comment by unverbraucht** [comment]
I've observed this over the last few days. One time the perfpowerservices / kernel CPU load appeared again but disappeared after a few minutes of using the device. One time it appeared and ate battery, fans blowing and I rebooted after 30 minutes. Two times I woke it up from hibernation without the issue appearing. All times I hibernated it by closing the lid. I have not observed the issue if I hibernate it via menu instead of closing the lid. My assumption is that it is connected to the lid switch somehow?
A worse issue appeared yesterday:
I heard the laptop fan blowing in the morning. It must have crashed during the night while being plugged in. The screen was black, device did not react to keyboard pressed. The laptop was extremely hot because it was closed, and it smelled of warm plastic. I will not hibernate by closing the lid for now.

**Comment by profzei** [comment]
@unverbraucht Atm I'm using sleep-mode i.e. `hibernatemode 3` on a daily basis (using lid-switch and auto-sleep feature...) without any issue... but I'll keep monitoring the situation...

**Comment by unverbraucht** [comment]
@profzei I have not seen this issue again in the last week, so I hope that it's gone. Maybe it was related to the initial indexing? In any case I have the output of `pmset log` if that is any help?
I'll leave the issue open and observe it a few more days and if I do not see the issue I'll close it.

**Comment by profzei** [comment]
> I have not seen this issue again in the last week, so I hope that it's gone.

@unverbraucht Good news: crossed fingers!

> I have the output of pmset log if that is any help?

@unverbraucht I don't know if it could help, but I'm curious to check if there could be any useful info (...in general the answer is negative...)

**Comment by unverbraucht** [comment]
@profzei sorry for taking so long to get back on this. It has happened again yesterday: I closed the clamshell of the (sleeping) laptop and put it in my backpack. An hour later I hour the fan whistling at full speed and open it to take out a very hot laptop.
Today it has wakened from sleep on it's own and kernel_task is taking 100% cpu again. I've attached pmset.log for you.
[pmset2.log](https://github.com/profzei/Matebook-X-Pro-2018/files/6341022/pmset2.log)

**Comment by unverbraucht** [comment]
I followed the hibernation / pmset settings after doing an upgrade and have only seen the issue once since then. When it happens the only thing that will fix it is a reboot. I have not been able to observe if waking from hibernation causes the issue or not. In any case I'm quite happy with how it's behaving now. I still shut it down instead of hibernating it when I close the lid because it woke up once and got very very hot.

Is it time that we close this issue?

**Comment by rohirrim27** [comment]
Hi @unverbraucht ,

Can I confirm that you're using only the following hibernation/pmset settings?

sudo pmset -a standby 0
sudo pmset -a powernap 0
sudo pmset -a proximitywake 0
sudo pmset -a tcpkeepalive 0
sudo pmset -a womp 0

Also may I ask if you've dual booted your machine with Mac OS and Windows on separate SSD's. I've done that with the original SSD containing Windows and an external SSD with Mac OS and wondering if that might be a cause for the wakeups (don't see why it should be though)
