### ISSUE TITLE
Fake ethernet not visible in hackingtool

### ISSUE THREAD

**Issue by hiyurun** [profzei/Matebook-X-Pro-2018#152]
i can't find it.

**Comment by profzei** [comment]
@hiyurun Why did you care about it when you have a working WiFi card? Please, do not answer that you think it's related to your iMessage issue...

**Comment by hiyurun** [comment]
sorry
i'll try elsewhere. I thought this was the right place because i have a matebook pro x installed with your EFI.

Have a good day.

**Comment by profzei** [comment]
Sorry, I did not want to be so rude, but people are always opening **issues which are not related to the real content of this repo i.e. supporting macOS install on a device not designed/built for it**. For example, Reddit subforum for hackintosh is plenty of such help requests (almost one about every week) and I think you'll find there more than one successful path for resolving your issue...
