### ISSUE TITLE
How to fix DRM .

### ISSUE THREAD

**Issue by LavenderMP** [profzei/Matebook-X-Pro-2018#153]
Currently I couldn't watch movies on netflix any ideal how to fix it?

**Comment by profzei** [comment]
@LavenderMP 
Please, see [https://dortania.github.io/OpenCore-Post-Install/universal/drm.html#testing-hardware-acceleration-and-decoding](https://dortania.github.io/OpenCore-Post-Install/universal/drm.html#testing-hardware-acceleration-and-decoding)

**Comment by huotarih** [comment]
@profzei same problem after updating to newest release. The link above didn't really help me, I feel lost, any idea what to do?

**Comment by huotarih** [comment]
@LavenderMP how did you fix it?

**Comment by profzei** [comment]
@huotarih Hi, I didn't dig too much into the problem since in the Dortania's guide section I linked in my previous reply the following is reported:

> Note: Safari 14 and macOS 11, Big Sur are currently unsupported by WhateverGreen's DRM patches. Safari 13 in Catalina and older are supported just fine however.
> Note 2: Browsers not using hardware based DRM(ie. Chrome), will have working DRM without any work both on iGPUs and dGPUs. The below guide is for Safari and other applications with hardware based DRM

**Comment by huotarih** [comment]
Re-installing chrome fixed it for some reason.
