### ISSUE TITLE
How to disable hyper-threading on an i5 processor

### ISSUE THREAD

**Issue by lq4866** [profzei/Matebook-X-Pro-2018#155]
Hi profzei, 
  Thanks for your great work which help me install Mac ox on my laptop, still there is a problem I can not solve, I am using an i5  version matebook x pro 2018, the hyper-threading is defaultly open in this EFI. For now, this EFI works fine on my laptop, but I do not know if there is any problem since  I just directly copy this EFI.

**Comment by profzei** [comment]
> I do not know if there is any problem since I just directly copy this EFI.

@lq4866 There should be no problem!

**Comment by lq4866** [comment]
I realized this is not a good question.
