### ISSUE TITLE
Wi-Fi don't work after clean install Catalina

### ISSUE THREAD

**Issue by Vatri91** [profzei/Matebook-X-Pro-2018#156]
Hi. Just got back to Catalina. Big Sur is much slower on our computers. When installing I used the latest OC 2.1 release. Earlier 1.9.1 on Big Sur.

Unfortunately, after the installation, Wi-Fi does not work for me. This option is not available in the settings. Only ethernet and Bluetooth are active. There is also no wifi icon in Tray.

What am I doing wrong?

**Comment by profzei** [comment]
Hi @Vatri91 Please see my reply to [#138](https://github.com/profzei/Matebook-X-Pro-2018/issues/138#issuecomment-768574895) and let me know if your issue is fixed

**Comment by Vatri91** [comment]
Thx
