### ISSUE TITLE
Can't boot install USB X Pro 2019 i5 8265u

### ISSUE THREAD

**Issue by mtimms1980** [profzei/Matebook-X-Pro-2018#16]
I am get stuck on "ApplePS2Controller: notification consumer published: ApplePS2Mouse". Researching this now. I need to start from scratch again as if I am being honest, I am not 100% sure what drivers/kexts etc I had copied over when getting the above.

Is it advised to copy only the Boot and Clover folders from this repo to the EFI folder on the usb installer? If so, is choosing the Catalina locked config the correct choice? I am attempting to install Catalina of course! Thanks.

**Comment by profzei** [comment]
Hi,
try to use the following EFI folder for install Catalina from USB:
[EFI_Install_USB_for_MateBook_X_Pro_2019.zip](https://github.com/profzei/Matebook-X-Pro-2018/files/4740607/EFI_Install_USB_for_MateBook_X_Pro_2019.zip)

Honestly I didn't yet "install from scratch" Catalina since I upgraded (as most of users) from Mojave...
If all goes right then you can replace all with CLOVER folders from this repo!

**Comment by mtimms1980** [comment]
Amazing, thank you. I will try this tonight and let you know how it goes. Thank you for the help!

**Comment by mtimms1980** [comment]
And just like that, it booted! I can't thank you enough! Now off to grab a USB mouse to get this setup. I know I have a way to go yet, but thank you again. 
![IMG_20200606_185248](https://user-images.githubusercontent.com/44544927/83951154-72b6e080-a827-11ea-89e0-49079f8afc9b.jpg)

**Comment by mtimms1980** [comment]
Installed without issue. I can't boot once I copy all of the files over form this repo, but can boot into macOS using the USB installer. I've copied just those files over for now so that I can boot and test without needing to boot from USB. If I boot using the config.plist from the USB it boots fine, so I guess I need to figure out what's breaking it and amend the Catalina locked config accordingly...

**Comment by Hernanduno** [comment]
Hey man, could you please provide me a link or a guide  with the steps you followed to make it works  om MBXP 2019? I have i7 versión and I'm always getting  stuck at some point of the process no master what guide I follow  😢 I will really apreciate  if you could help me with this.
