### ISSUE TITLE
The fan is not working

### ISSUE THREAD

**Issue by zxcv-000** [profzei/Matebook-X-Pro-2018#160]
Hello, I am glad that I used your EFI to successfully install macOS and got a good experience, but I found that when the computer temperature is too high, the fan does not work. Have you encountered such a situation? If you know what to do, please tell me how to do it! Or you can update it on the wiki, thank you very much!

**Comment by profzei** [comment]
@zxcv-000
Honestly I didn't stress too much my laptop: in fact I set a balanced energy profile for CPU stepping...
I stressed extensively my MBXP when I tested optimal (for me...) thresholds for undervolting... and in such a case fan worked well!

How do you test the fan is not working for too high laptop's temperature?
