### ISSUE TITLE
Issues with USB-C monitor

### ISSUE THREAD

**Issue by ldan93** [profzei/Matebook-X-Pro-2018#161]
Hi Profzei,

I've just bought a 4K/60hz screen (LG 27UL850). It has HDMI, DisplayPort, and USB-C (also through DisplayPort protocol I think) connectors. I'm using USB-C so I can power the laptop and use the monitor's USB hub. 

I'm having troubles getting it 100% working with MacOS (Big Sur / latest EFI release)
1. When I plug it, the screen wakes up, works as expected for a few seconds, then it turns off for a few seconds, on and on. Eventually, after 1 minute, the screen is working as expected. (Weird, but not such a big deal)
2. The monitor is not detected as an audio device with the USB-C connexion (it works with HDMI, but I really want to use the USB-C), this is really a bummer...

None of these problems occur with Windows 10 or Linux... Do you have any idea how I could investigate / solve these issues ?

Here's what I've investigated :

- I tried adding -cdfon and -igfxnohdmi to boot args (WhateverGreen patches) (no luck...)
- ~~One post I've read suggested increasing graphic memory from 1536mo to 2gb to get more stability with several HighDPI screens. Do you think it could be relevant ?~~ _Edit :_ I've tried this, it doesn't change anything

**Comment by profzei** [comment]
@ldan93 
- You are right: increasing graphic memory up to 2 GB is not relevant and discouraged (if I remember well...) from some old posts in `WhateverGreen` bug tracker

> When I plug it, the screen wakes up, works as expected for a few seconds, then it turns off for a few seconds, on and on. Eventually, after 1 minute, the screen is working as expected. (Weird, but not such a big deal)

- Have you tested both the two USB type-C ports?
- The behavior you describe seems/could to be related to the setting of the chosen resolution for external display... which resolution did you choose? Have you tested whether timing is related to chosen resolution?

> The monitor is not detected as an audio device with the USB-C connexion (it works with HDMI, but I really want to use the USB-C), this is really a bummer...

- Honestly I really don't know... I had never found documentation about audio through "pure" USB type-C port connection...

**Comment by profzei** [comment]
**Update**:

> The monitor is not detected as an audio device with the USB-C connexion (it works with HDMI, but I really want to use the USB-C), this is really a bummer...
> Honestly I really don't know... I had never found documentation about audio through "pure" USB type-C port connection...

Have you tried to set your "**external**" USB type-C port (where you plug in the monitor) as "**internal**"?

**Comment by ldan93** [comment]
Thanks for your help in debugging this issue !

> * Have you tested both the two USB type-C ports?

Yes I have, didn't change anything...

> * The behavior you describe seems/could to be related to the setting of the chosen resolution for external display... which resolution did you choose? Have you tested whether timing is related to chosen resolution?

I chose 4K(3840x2160)/60hz, with a Hidpi scaling factor of 1.5, so the actual screen estate is 2560x1440. 

I tried to choose lower resolutions without Hidpi (1080p), this strange behaviour still happens. One precision : while the external monitor turns off/on, the internal display is also doing the same. Sometimes, the internal and the external monitors won't turn on, so I'm in front of 2 black screens and I have to force reboot the computer.

> * Honestly I really don't know... I had never found documentation about audio through "pure" USB type-C port connection...

Well, I think it's the DisplayPort protocol that is used through USB-C, so audio should also be transmitted through DP...

I just actually managed to get the audio to work but I cannot reliably tell how. I tried to add/remove the following arguments : -igfxnohdmi -igfxtypec -igfxhdmidivs -igfxagdc=0 and -cdfon. From time to time the audio appeared, most of the time after waking up from sleep (not sure this is correlated). But I'm clueless about why, because it's really unpredictable, and right now I cannot get it to work again... 

> * Have you tried to set your "external" USB type-C port (where you plug in the monitor) as "internal"?

What do you mean ? Setting the external monitor as the primary one ?

**Comment by profzei** [comment]
> What do you mean ? Setting the external monitor as the primary one ?

No, what I mean is using connector type 255 (i.e. `internal`) instead of 9 (i.e. `type-C`) in `XHCI` definition...

**Comment by ldan93** [comment]
I have too little spare time at the moment to continue investigating this issue, so I will close it for now. And my setup is too unreliable for a professional use (I have to hard reboot several times a day when the monitor is connected), so I will go back to Windows as a daily driver...
Thank you again for your help and your amazing work. If I manage to find a workaround, I'll let you know !

**Comment by ldan93** [comment]
OK, so, I've tried one last thing before giving up... And I think I found the solution ! 
Here's what I've changed in `config.plist` : 
`framebuffer-con1-type` --> `<00040000>` (00040000 = DisplayPort)
`framebuffer-con2-type` --> `<00040000>`
(both were set to `<00080000>`, that is HDMI)
Now the screen is perfectly working without any extra boot parameters and the sound device is detected.

Then, I've checked with two different docks/adapters if changing these values caused issues with HDMI : I can report that HDMI is still perfectly working !

Maybe you could test it yourself and consider changing these values upstream, so people with Displayport monitors could benefit from this change ? :)

**Comment by profzei** [comment]
Nice shot! Thank you very much! I set those values about a year ago using an hdmi monitor (no dvi connector available)... following WhateverGreen faq but now you found a better global setting! I'll update repo in the weekend.😊👍🏻
