### ISSUE TITLE
Installing Big Sur to External USB Thumb Drive

### ISSUE THREAD

**Issue by Juxtyce** [profzei/Matebook-X-Pro-2018#162]
This worked for Catalina but fails to install for Big Sur. 

I am installing to a Samsung 256GB Fit Plus USB thumb drive.  When installing it goes through the install process but fails when installing.  It get's stuck at 100% complete bar.

I tried a fresh install using this tutorial from here (https://github.com/profzei/Matebook-X-Pro-2018/wiki/Upgrade-to-macOS-Big-Sur), and it worked up to the second phase of installation. After it rebooted to load the OS for the first time, it would get stuck at a full loading bar, and I left it overnight just to see it still stuck.

Once again this worked flawlessly on Catalina but fails on Big Sur.  I've used different EFI releases with the exact same end result.

Willing to try any suggestions

**Comment by Juxtyce** [comment]
@profzei Guess I am the only one that is trying to install Big Sur on an external drive and not on the internal SSD.  If you happen to come across an idea why this worked on Catalina and not Big Sur, let me know.  As mentioned above - willing to try anything ... can also see about providing you with a 128GB Samsung Fit Plus to test .... let me know ...

thanks,

**Comment by AshleyMiller9696** [comment]
did a fresh install - BigSur 11.3.1 and used the efi for the installation on the upgrade wiki - after it worked i switched to version 2.1

dont know why, but installed Big Sur on an Toshiba external hard drive, which worked
not on an sandisk thumb drive
(did a workaround with copycleaner)
