### ISSUE TITLE
Intel WiFi adapter is always En1

### ISSUE THREAD

**Issue by leffz** [profzei/Matebook-X-Pro-2018#163]
cant set wifi to En0 and activate iMessage and FT.

Fixing En0 in OpenCore Post-Install didn't help me. Can you help me?

**Comment by Juxtyce** [comment]
What seems to be the issue when using iMessage and FT with the assigned En# port.  Just checked mine with ifconfig and my wifi is En2.  Do you have Internet access?

**Comment by profzei** [comment]
@leffz 
You **don't need necessarily** your WiFi interface set as `en0` for activating iMessage and FaceTime
As you could see in the attached image, my WiFi is recognized as `en1` and my iMessage is working properly...
<img width="1500" alt="iMessage_Working_Fine_with_WiFi_set_as_en1" src="https://user-images.githubusercontent.com/47076961/115748583-95e27400-a396-11eb-95fd-9af00f501023.png">
Try to follow **Dortania's guide for iMessage** but first I suggest to delete all your previous attempts otherwise your iCloud account could be blacklisted...

**Comment by leffz** [comment]
sorry for late reply! yes i have internet access and it's not 100%. i have nuc8i5 hackintosh and there is no troubles at all. but in matebook i often loose the internet connection despite heliport reports we connected to wifi. sometimes!! heliport shows no wifi in range and no wifi connected, but there was an internet!! in most cases it happens after sleep or display off. do u have such behaviour?

appstore is working. but FT and iMessage can't log in. when i try to log into imessage i see it tries and even show me a windows like on your snapshot(with contacts and dialogs) but there are no conact and conversation, only 1 option create a message. after a few seconds (3-4) this windows closes and i see previous log in window. no errors and no warnings...

**Comment by profzei** [comment]
@leffz 
As you know I'm not using `itlwm.kext` + `HeliPort.app` combo...
Honestly I'm using `AirportItlwm.kext` and I have 0 issues even after sleep or display off... I'm using `AirportItlwm.kext` also in my [NUC7i3BNH](https://github.com/profzei/NUC7i3BNH) without any issues with the same identical approach... In both cases iMessages and FaceTime are working properly... therefore, in case you had followed Dortania's guide as suggested, I'm out of ideas...

**Comment by leffz** [comment]
OK, I made a new clean install and now I have my wifi is En0, I did everything as before but now iMessage and FT is work.

<img width="1446" alt="image" src="https://user-images.githubusercontent.com/18469512/117945266-d76f9a80-b316-11eb-9bf5-55917621f26c.png">

About wifi connection, i think it's because of my kineetic router, I have some troubles in windows also(but only with laptop). I set up new router and now have no issues with airport and itlwm in hackintosh.

The only problem with my hack is it can't sleep. after I select go to sleep it turns off for a 5 second and then comes back with Lock Screen.

**Comment by profzei** [comment]
@leffz 
Have you followed all the steps (even after each macOS upgrade...) mentioned in [homepage](https://github.com/profzei/Matebook-X-Pro-2018#post---install-settings)?

If the answer is affirmative, then probably you installed some app which is conflicting with sleep... there are a lot... just for my experience [Soundflower](https://github.com/profzei/Matebook-X-Pro-2018/wiki/Activate-Surround-Sound-via-MIDI-on-internal-speakers)
