### ISSUE TITLE
(question) Boot Logo change in unlocked Bios

### ISSUE THREAD

**Issue by supremekiind** [profzei/Matebook-X-Pro-2018#166]
Hey Profzei
I see you do a guide about unlocking bios. Is it possible that you can make a little guide to change the Boot logo (Huawei-logo).  You are the best thanks.
~Supremekiind

**Comment by tlefko** [comment]
> Hey Profzei
> I see you do a guide about unlocking bios. Is it possible that you can make a little guide to change the Boot logo (Huawei-logo). You are the best thanks.
> ~Supremekiind

hey, so I actually looked into this and did find the GUID address of the boot file and where to make the change. but I can’t figure out how to actually flash the new modified bios to the machine. if you know anything about this (i’m a little busy to go researching how to properly flash it) do let me know and i’ll send the info how to modify it!
