### ISSUE TITLE
VoodooPS2

### ISSUE THREAD

**Issue by tlefko** [profzei/Matebook-X-Pro-2018#169]
Out of curiosity, why not use a different version of voodoops2? -- I can upload a kext with the version I'm using which (with ur DSDT) disabled touchscreen works without any issues related to the ones you brought up with polling etc, battery.

Further, note: AirportITLWM does not work under macOS catalina with the configuration you have uploaded.

**Comment by rohirrim27** [comment]
Hi, have you tried ProfZei's instructions on v1.7.0 release regarding WiFi on Catalina:

_NOTE

If you use this release in macOS Catalina you need to make the following changes in the config.plist to make AirportItlwm support active:
- DmgLoading set to Signed
- SecureBootModel set to Default_

**Comment by tlefko** [comment]
> Hi, have you tried ProfZei's instructions on v1.7.0 release regarding WiFi on Catalina:
> 
> _NOTE
> 
> If you use this release in macOS Catalina you need to make the following changes in the config.plist to make AirportItlwm support active:
> 
> * DmgLoading set to Signed
> * SecureBootModel set to Default_

yep, tried it -- I think the version of the kext is broken. Also, I have a power management profile option I can upload for the repo if you want to just add it as an option. Essentially, it leaves GPU performance uncaps but keeps CPU performance bottled to the point where it runs completely silent, but smooth running all normal tasks. also improves battery life, but definitely not for performance.

![64262389443__36E0AD66-4F73-41AD-9926-9BD21CFA834C](https://user-images.githubusercontent.com/42879340/118171981-db281d80-b3f9-11eb-8a7d-d9d2a7948ec8.jpeg)

**Comment by profzei** [comment]
> I think the version of the kext is broken

@tlefko Honestly I'm using it currently on macOS Catalina 10.15.7 Security Update 2021-002 (build 19H1030) on my other project which has the same WiFi interface... so I don't know...

> Also, I have a power management profile option I can upload for the repo if you want to just add it as an option.

@tlefko Every contribution is always appreciated! Please, attach the corresponding file here and after testing it I'll upload it giving obviously the right credit!

**Comment by tlefko** [comment]
> > I think the version of the kext is broken
> 
> @tlefko Honestly I'm using it currently on macOS Catalina 10.15.7 Security Update 2021-002 (build 19H1030) on my other project which has the same WiFi interface... so I don't know...
> 
> > Also, I have a power management profile option I can upload for the repo if you want to just add it as an option.
> 
> @tlefko Every contribution is always appreciated! Please, attach the corresponding file here and after testing it I'll upload it giving obviously the right credit!

@profzei hm I must be doing something wrong then with wifi. Sure, here's the files attached below just make sure you're disabling your PM ssdt and enabling this one! also use the provided kexts. These should make the computer essentially silent.
[PM.zip](https://github.com/profzei/Matebook-X-Pro-2018/files/6475762/PM.zip)

**Comment by profzei** [comment]
@tlefk Thank you for your explanation... I'll test it asap (even if I'm a little busy with real work...), but I have one more question:
- are you using **headkaze**'s `HWPenable` fork?
- `CPUFriendDataProvider.kext` and `ssdt_data.aml` are sharing the same data, right?
- your `ssdt_data.aml` is derived from what CPU (8550U or 8250U)?

**Comment by tlefko** [comment]
> @tlefk Thank you for your explanation... I'll test it asap (even if I'm a little busy with real work...), but I have one more question:
> 
> * are you using **headkaze**'s `HWPenable` fork?
> * `CPUFriendDataProvider.kext` and `ssdt_data.aml` are sharing the same data, right?
> * your `ssdt_data.aml` is derived from what CPU (8550U or 8250U)?

ssdt_data should be for the 8550U, however realistically it will work with either. They are sharing the same data, so yes technically it's redundant. However in my experience using the AML made it more reliable, and there's not really a drawback.

It's Goodwin's version of HWP not **headkaze**'s fork

**Comment by profzei** [comment]
> PS, you should also test voltage shift for yourself after hibernation / sleep. It seems to be broken on big sur when using the launchdameon. The settings disable after sleep and you need to reapply them.

@tlefko Just checked it now on Big Sur 11.3.1: it's working flawlessly!

ASAP I'll check the differences from the `ssdt_data.aml` you provided and the frequency vectors I stored probably one year ago in my `SSDT_PM.aml`

**Comment by tlefko** [comment]
@profzei really? that's so unusual. I have to reapply my voltageshift after every sleep. I have it setup in automator because if you run voltageshift ./info afterwards you can see they're all gone after a 45 second sleep... so odd lol

**Comment by profzei** [comment]
@tlefko 
Here in the following there is my IPG graph with Turbo Boost disabled which is my default setting on battery
<img width="512" alt="Turbo Boost disabled" src="https://user-images.githubusercontent.com/47076961/118449773-c1d1ea80-b6f3-11eb-871d-a888f593c44f.png">
while now in the following there is my IPG graph with Turbo Boost enabled on battery
<img width="512" alt="Turbo Boost Enabled" src="https://user-images.githubusercontent.com/47076961/118449953-f6de3d00-b6f3-11eb-8750-bc5546b1e32b.png">

**Comment by tlefko** [comment]
> @tlefko
> Here in the following there is my IPG graph with Turbo Boost disabled which is my default setting on battery
> <img alt="Turbo Boost disabled" width="512" src="https://user-images.githubusercontent.com/47076961/118449773-c1d1ea80-b6f3-11eb-871d-a888f593c44f.png">
> while now in the following there is my IPG graph with Turbo Boost enabled on battery
> <img alt="Turbo Boost Enabled" width="512" src="https://user-images.githubusercontent.com/47076961/118449953-f6de3d00-b6f3-11eb-8750-bc5546b1e32b.png">

hmm, try my ssdt out see what results you get, if you don't mind post some pics under load of both!
