### ISSUE TITLE
[QUESTION] How to use USB bluetooth dongle instead of built-in one?

### ISSUE THREAD

**Issue by hdamico** [profzei/Matebook-X-Pro-2018#170]
Hello!
As you may know, the bluetooth works really bad, so I am trying to replace the built-in bluetooth with an USB bluetooth dongle, but I am not sure where should I start, I found this [repo](https://github.com/acidanthera/BrcmPatchRAM), followed the steps but it's not working, I am guessing that I need to disable the built-in one first, but I don't know how.
Does someone make it work?

The steps that I followed:
- Downloaded the last release.
- Copied `BrcmBluetoothInjector.kext`, `BrcmFirmwareRepo.kext`, `BrcmPatchRAM3.kext` and `BrcmNonPatchRAM2.kext` (this last one just in case) and pasted on `/Library/Extensions`.

**Comment by profzei** [comment]
Hi @hdamico 
- If you want to disable internal Bluetooth you may try [this](https://github.com/profzei/Matebook-X-Pro-2018/issues/117#issuecomment-770393181): I made it for another user but never had feedback...
- As a second step, then you need to check if your external Bluetooth dongle is compatible with the repo you found...
- As a last step you need to be very sure whether it is appropriate to put kexts on `/Library/Extensions` or in `/EFI/OC/Kexts folder`

**Comment by hdamico** [comment]
The approach for disabling the bluetooth works, but my dongle is not working yet, I saw from a [subreddit](https://www.reddit.com/r/hackintosh/comments/4shevu/anyone_know_how_i_can_get_my_insignia_bluetooth/) that my dongle should work with the injector, so I am not sure what to do.

**Comment by profzei** [comment]
- Try to add the following code in your `config.plist` immediately after the (end of the) call for `SMCProcessor` (and before the call for `WhateverGreen`) in `Kernel -> Add` section:
```
<dict>
	<key>Arch</key>
	<string>x86_64</string>
	<key>BundlePath</key>
	<string>BrcmFirmwareData.kext</string>
	<key>Comment</key>
	<string>Bluetooth dongle Firmware</string>
	<key>Enabled</key>
	<true/>
	<key>ExecutablePath</key>
	<string>Contents/MacOS/BrcmFirmwareData</string>
	<key>MaxKernel</key>
	<string></string>
	<key>MinKernel</key>
	<string></string>
	<key>PlistPath</key>
	<string>Contents/Info.plist</string>
</dict>
<dict>
	<key>Arch</key>
	<string>x86_64</string>
	<key>BundlePath</key>
	<string>BrcmBluetoothInjector.kext</string>
	<key>Comment</key>
	<string>Bluetooth dongle Injector</string>
	<key>Enabled</key>
	<true/>
	<key>ExecutablePath</key>
	<string></string>
	<key>MaxKernel</key>
	<string></string>
	<key>MinKernel</key>
	<string></string>
	<key>PlistPath</key>
	<string>Contents/Info.plist</string>
</dict>
<dict>
	<key>Arch</key>
	<string>x86_64</string>
	<key>BundlePath</key>
	<string>BrcmPatchRAM3.kext</string>
	<key>Comment</key>
	<string>Bluetooth dongle Patch</string>
	<key>Enabled</key>
	<true/>
	<key>ExecutablePath</key>
	<string>Contents/MacOS/BrcmPatchRAM3</string>
	<key>MaxKernel</key>
	<string></string>
	<key>MinKernel</key>
	<string></string>
	<key>PlistPath</key>
	<string>Contents/Info.plist</string>
</dict>
```
- (Cross your fingers and ) Reboot your device!

**Comment by hdamico** [comment]
Alright! Now is working, I deleted all the kexts from `/Library/Extensions` and put `BrcmFirmwareData.kext`, `BrcmBluetoothInjector.kext` and `BrcmPatchRAM3.kext` on `/EFI/OC/Kexts`.

So, the steps are:
- Disable built-in bluetooth by doing [this](https://github.com/profzei/Matebook-X-Pro-2018/issues/117#issuecomment-770393181).
- Edit `/EFI/OC/config.plist` and add [these](https://github.com/profzei/Matebook-X-Pro-2018/issues/170#issuecomment-845502385) new lines.
- Download the lastest release from [here](https://github.com/acidanthera/BrcmPatchRAM).
- Copy  `BrcmFirmwareData.kext`, `BrcmBluetoothInjector.kext` and `BrcmPatchRAM3.kext` and paste them on `/EFI/OC/Kexts`.
- Done!

Thanks @profzei you are awsome!!

**Comment by samwzlim** [comment]
@hdamico Hope you don't mind me asking, but which bluetooth usb dongle did you use in particular? I'm also thinking of purchasing one, as the experience with built-in bluetooth is far from great. 

Other than that, does using a Broadcom bluetooth dongle provide more continuity services (e.g. airdrop, apple watch unlock)? Looking forward to hearing from you!

**Comment by hdamico** [comment]
@samwzlim sure! I bought this [dongle](https://www.bestbuy.com/site/insignia-bluetooth-4-0-usb-adapter-black/4884001.p?skuId=4884001&intl=nosplash), it does not provide much improvment but at least it solved my problem of my bluetooth peripherals getting random disconnections. So, in my opinion if you are hoping to get a better experience with apple services, this won't change much.

**Comment by samwzlim** [comment]
> @samwzlim sure! I bought this [dongle](https://www.bestbuy.com/site/insignia-bluetooth-4-0-usb-adapter-black/4884001.p?skuId=4884001&intl=nosplash), it does not provide much improvment but at least it solved my problem of my bluetooth peripherals getting random disconnections. So, in my opinion if you are hoping to get a better experience with apple services, this won't change much.

Oh I see, thanks! I see you got the one with the BCM20702 chip inside. I'm trying to find that exact model, but unfortunately, it isn't sold in my country. The only one I can get my hands on is the CSR8510 A10 chip. Have you had any experience with this specific model, by any chance? Based on my research, it's either hit or miss with this dongle.
