### ISSUE TITLE
macOS 11+ restarts unpredictably 

### ISSUE THREAD

**Issue by samwzlim** [profzei/Matebook-X-Pro-2018#171]
EFI version: 2.3.0 (latest at the time of writing this)
macOS version: 11.5 beta
Occasionally, macOS will restart randomly during usage or idling. This is the error report when macOS restarts:

panic(cpu 0 caller 0xffffff8010cd0860): nvme: "Fatal error occurred. CSTS=0xffffffff US[1]=0x0 US[0]=0xd5 VID=0x1179 DID=0x116
. FW Revision=AAXA4103\n"@/System/Volumes/Data/SWE/macOS/BuildRoots/ad62260af4/Library/Caches/com.apple.xbs/Sources/IONVMeFamily/IONVMeFamily-557.120.1/Common/IONVMeController.cpp:5499
Backtrace (CPU 0), Frame : Return Address
0xffffffb094d8b960 : 0xffffff800e48d04d 
0xffffffb094d8b9b0 : 0xffffff800e5d3f63 
0xffffffb094d8b9f0 : 0xffffff800e5c455a 
0xffffffb094d8ba40 : 0xffffff800e431a2f 
0xffffffb094d8ba60 : 0xffffff800e48c86d 
0xffffffb094d8bb80 : 0xffffff800e48cb63 
0xffffffb094d8bbf0 : 0xffffff800ec9c8fa 
0xffffffb094d8bc60 : 0xffffff8010cd0860 
0xffffffb094d8bc80 : 0xffffff8010cb545b 
0xffffffb094d8bde0 : 0xffffff800ebf34d5 
0xffffffb094d8be50 : 0xffffff800ebf33d6 
0xffffffb094d8be80 : 0xffffff800e4d3675 
0xffffffb094d8bef0 : 0xffffff800e4d45e4 
0xffffffb094d8bfa0 : 0xffffff800e43113e 
      Kernel Extensions in backtrace:
         com.apple.iokit.IONVMeFamily(2.1)[8D47DA90-79B7-33A8-B5C9-DFD9B708CFA4]@0xffffff8010cae000->0xffffff8010cd7fff
            dependency: com.apple.driver.AppleEFINVRAM(2.1)[26D83939-D2C2-3B4E-A268-0DA7B01B187E]@0xffffff800f8fe000->0xffffff800f907fff
            dependency: com.apple.driver.AppleMobileFileIntegrity(1.0.5)[52E40A68-70FA-3782-9595-8D99527B837C]@0xffffff800fac0000->0xffffff800fad5fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[395E932C-57ED-368F-B673-DD261C7761A5]@0xffffff8010f6c000->0xffffff8010f94fff
            dependency: com.apple.iokit.IOReportFamily(47)[A5283FFC-0B0C-3409-A86B-0CBFBF53D863]@0xffffff8010fa3000->0xffffff8010fa5fff
            dependency: com.apple.iokit.IOStorageFamily(2.1)[3DE94082-367D-3255-9BE7-7F5A87838247]@0xffffff801106f000->0xffffff8011080fff

Process name corresponding to current thread: kernel_task
Boot args: igfxrpsc=1

Mac OS version:
20G5033c

Kernel version:
Darwin Kernel Version 20.6.0: Mon May 24 00:50:08 PDT 2021; root:xnu-7195.140.22~21/RELEASE_X86_64
Kernel UUID: 331AAB1E-6B00-3159-B97F-4AD6FE3D7A31
KernelCache slide: 0x000000000e200000
KernelCache base:  0xffffff800e400000
Kernel slide:      0x000000000e210000
Kernel text base:  0xffffff800e410000
__HIB  text base: 0xffffff800e300000
System model name: MacBookPro16,3 (Mac-E7203C0F68AA0004)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 3435443454743
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x0000031fe0630929
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x0000000d9f0bbe24 0x0000000000000000

**Comment by profzei** [comment]
@samwzlim Try to unload `NVMeFix.kext` and check if this mitigate your issues... could they be related to the fact you are running Beta 11.5?

**Comment by samwzlim** [comment]
> @samwzlim Try to unload `NVMeFix.kext` and check if this mitigate your issues... could they be related to the fact you are running Beta 11.5?

Will try the next time I encounter a crash again, macOS is running smoothly at the moment.

**Comment by samwzlim** [comment]
@profzei To unload the kext, I just remove it from the Kexts folder in the EFI right?

**Comment by profzei** [comment]
No, you only need to put value `false` for key `Enabled` in Kernel section in `config.plist`

**Comment by samwzlim** [comment]
@profzei  believe this issue is related to #142. I tried unloading nvmefix.kext, but after doing so, I'm unable to boot into macOS (apple logo present but no loading bar). Referring to #142, OP also experienced bootloop after unloading nvmefix.kext. How do I go about booting into macOS again and loading the nvmefix.kext into the EFI once again? Also, I'm utilising both usb-c ports on the MBXP (2018 i5 version), so would I need to activate thunderbolt specific items as mentioned in the wiki?

**Comment by samwzlim** [comment]
Well, after hours of troubleshooting, I managed to revert the changes to `NVMeFix.kext`. However, I am now introduced to a new issue. My machine will only boot to Windows, bypassing the OpenCore boot picker unless I plug in my USB containing the EFI files. Prior to this, I followed Dortania's OC guide to set up bootcamp, set `showbootpicker` in config.plist to `false` and it worked flawlessly. This issue only started after I ammended `NVMeFix.kext`. It could have been a pure coincidence, or related. I have already reverted `showbootpicker` back to `true`, yet, OC bootpicker doesn't show up unless I plug in my USB. I have already mounted the EFI into the macOS partition.

Steps I have taken to troubleshoot but failed:
1. Set default startup disk in macOS and bootcamp(Windows) to the macOS partition, but machine boots to Windows anwyways
2. Copied EFI files from USB to mounted EFI in macOS partition, but machine boots to Windows anyways

**Comment by samwzlim** [comment]
In the EFI under releases, there is no Microsoft folder. However in mine, there contains one. Is this to be expected?
![Uploading CleanShot 2021-06-06 at 12.14.29@2x.png…]()

**Comment by samwzlim** [comment]
In the EFI under releases, there is no Microsoft folder. However in mine, there contains one. Is this to be expected?
<img width="1032" alt="CleanShot 2021-06-06 at 12 14 29@2x" src="https://user-images.githubusercontent.com/74489037/120912355-e866be00-c6c0-11eb-9217-aa602eda13fc.png">

**Comment by mmenendezg** [comment]
@samwzlim I've had the same issue recently for the last 3 months or so, to the point that I almost considered changing the ssd from my MBXPro to solve this issue. It happened all the time. 

In a desperate move I tried to clean the SSD, meaning opened the MBXPro and cleaned with alcohol the SSD contacts and It has solved the issue for about one week. 

I do not know if you had issues with both Windows and Mac, because in my case I had the issue with both. 

I hope this helps.

**Comment by profzei** [comment]
@mmenendezg 
If the issue occurs with Windows and macOS maybe its nature could be more hardware side than software...

However @mmenendezg @samwzlim 
I suggest to add `forceRenderStandby=0` in boot-args in your `config.plist`
The reference is [here](https://github.com/acidanthera/bugtracker/issues/1193)

...digging a little more this issue seems to be related to some incompatibility with some NVMe SSDs: @mmenendezg could you remember me what's your SSD?

Please report here your feedback!

**Comment by myselfghost** [comment]
I've had the same issue. my ssd is WDS500G3X0C-00SJG0 , SN750。
No such problem happened before。

``` 
panic(cpu 6 caller 0xffffff801d0ce860): nvme: "Fatal error occurred. CSTS=0xffffffff US[1]=0x0 US[0]=0x7b VID=0x15b7 DID=0x5002
. FW Revision=102000WD\n"@/System/Volumes/Data/SWE/macOS/BuildRoots/e90674e518/Library/Caches/com.apple.xbs/Sources/IONVMeFamily/IONVMeFamily-557.120.1/Common/IONVMeController.cpp:5499
Backtrace (CPU 6), Frame : Return Address
0xffffffa06442b960 : 0xffffff801a88e0dd 
0xffffffa06442b9b0 : 0xffffff801a9d4f33 
0xffffffa06442b9f0 : 0xffffff801a9c552a 
0xffffffa06442ba40 : 0xffffff801a832a2f 
0xffffffa06442ba60 : 0xffffff801a88d8fd 
0xffffffa06442bb80 : 0xffffff801a88dbf3 
0xffffffa06442bbf0 : 0xffffff801b09d81a 
0xffffffa06442bc60 : 0xffffff801d0ce860 
0xffffffa06442bc80 : 0xffffff801d0b345b 
0xffffffa06442bde0 : 0xffffff801aff4465 
0xffffffa06442be50 : 0xffffff801aff4366 
0xffffffa06442be80 : 0xffffff801a8d46c5 
0xffffffa06442bef0 : 0xffffff801a8d5634 
0xffffffa06442bfa0 : 0xffffff801a83213e 
      Kernel Extensions in backtrace:
         com.apple.iokit.IONVMeFamily(2.1)[38BC0D0C-B305-30F6-8A8D-6804830F891A]@0xffffff801d0ac000->0xffffff801d0d5fff
            dependency: com.apple.driver.AppleEFINVRAM(2.1)[423BF733-A622-3BC9-8F0F-920A2927CD35]@0xffffff801bcfe000->0xffffff801bd07fff
            dependency: com.apple.driver.AppleMobileFileIntegrity(1.0.5)[366C7BD4-9502-3D1C-ABBE-DE9749913D0C]@0xffffff801bec0000->0xffffff801bed5fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[99A70889-A31C-3B25-8E88-ADD3F317E4E4]@0xffffff801d36a000->0xffffff801d392fff
            dependency: com.apple.iokit.IOReportFamily(47)[367CCAE7-DAB4-3424-B191-44044619D5CB]@0xffffff801d3a1000->0xffffff801d3a3fff
            dependency: com.apple.iokit.IOStorageFamily(2.1)[A0D72FE9-649B-316A-8B5C-934E295FF0B5]@0xffffff801d46d000->0xffffff801d47efff

Process name corresponding to current thread: kernel_task
Boot args: igfxrpsc=1

Mac OS version:
20F71

Kernel version:
Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64
Kernel UUID: 52A1E876-863E-38E3-AC80-09BBAB13B752
KernelCache slide: 0x000000001a600000
KernelCache base:  0xffffff801a800000
Kernel slide:      0x000000001a610000
Kernel text base:  0xffffff801a810000
__HIB  text base: 0xffffff801a700000
System model name: MacBookPro16,3 (Mac-E7203C0F68AA0004)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 530362282431
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x0000007b7c0e4100
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x00000008850c32e4 0x0000000000000000
```

**Comment by myselfghost** [comment]
@profzei 
Boot args: igfxrpsc=1 forceRenderStandby=0
```
panic(cpu 0 caller 0xffffff800e2ce860): nvme: "Fatal error occurred. CSTS=0xffffffff US[1]=0x0 US[0]=0x83 VID=0x15b7 DID=0x5002
. FW Revision=102000WD\n"@/System/Volumes/Data/SWE/macOS/BuildRoots/e90674e518/Library/Caches/com.apple.xbs/Sources/IONVMeFamily/IONVMeFamily-557.120.1/Common/IONVMeController.cpp:5499
Backtrace (CPU 0), Frame : Return Address
0xffffffa055393960 : 0xffffff800ba8e0dd 
0xffffffa0553939b0 : 0xffffff800bbd4f33 
0xffffffa0553939f0 : 0xffffff800bbc552a 
0xffffffa055393a40 : 0xffffff800ba32a2f 
0xffffffa055393a60 : 0xffffff800ba8d8fd 
0xffffffa055393b80 : 0xffffff800ba8dbf3 
0xffffffa055393bf0 : 0xffffff800c29d81a 
0xffffffa055393c60 : 0xffffff800e2ce860 
0xffffffa055393c80 : 0xffffff800e2b345b 
0xffffffa055393de0 : 0xffffff800c1f4465 
0xffffffa055393e50 : 0xffffff800c1f4366 
0xffffffa055393e80 : 0xffffff800bad46c5 
0xffffffa055393ef0 : 0xffffff800bad5634 
0xffffffa055393fa0 : 0xffffff800ba3213e 
      Kernel Extensions in backtrace:
         com.apple.iokit.IONVMeFamily(2.1)[38BC0D0C-B305-30F6-8A8D-6804830F891A]@0xffffff800e2ac000->0xffffff800e2d5fff
            dependency: com.apple.driver.AppleEFINVRAM(2.1)[423BF733-A622-3BC9-8F0F-920A2927CD35]@0xffffff800cefe000->0xffffff800cf07fff
            dependency: com.apple.driver.AppleMobileFileIntegrity(1.0.5)[366C7BD4-9502-3D1C-ABBE-DE9749913D0C]@0xffffff800d0c0000->0xffffff800d0d5fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[99A70889-A31C-3B25-8E88-ADD3F317E4E4]@0xffffff800e56a000->0xffffff800e592fff
            dependency: com.apple.iokit.IOReportFamily(47)[367CCAE7-DAB4-3424-B191-44044619D5CB]@0xffffff800e5a1000->0xffffff800e5a3fff
            dependency: com.apple.iokit.IOStorageFamily(2.1)[A0D72FE9-649B-316A-8B5C-934E295FF0B5]@0xffffff800e66d000->0xffffff800e67efff

Process name corresponding to current thread: kernel_task
Boot args: igfxrpsc=1 forceRenderStandby=0

Mac OS version:
20F71

Kernel version:
Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64
Kernel UUID: 52A1E876-863E-38E3-AC80-09BBAB13B752
KernelCache slide: 0x000000000b800000
KernelCache base:  0xffffff800ba00000
Kernel slide:      0x000000000b810000
Kernel text base:  0xffffff800ba10000
__HIB  text base: 0xffffff800b900000
System model name: MacBookPro16,3 (Mac-E7203C0F68AA0004)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 110340308794
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x00000019b0cb8cf5
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x000000081dde73a0 0x0000000000000000


```

**Comment by profzei** [comment]
@myselfghost 
I'm sorry but I'm not able to reproduce this issue... my NVMe SSD is from LiteOn which is very stable (...since now!)

I found only one reference for this issue (not related to this config...) and I posted it above...

I could only suggest to unload `SSDT-NVME.aml` and/or `NVMeFix.kext`... 

Btw, could you confirm, please, that your installation is on an internal SSD (i.e. no external enclosure was used)?

**Comment by blodt** [comment]
I've had this problem with both Intel 660p (not 600, which is on the possibly problematic list) and in the last few days with a WD SN750 2TB NVMe also.

I've done a new install on a SATA SSD and am running happy again, but I know I'll eventually miss NVMe.

I don't know what model to buy to try again though honestly.

**Comment by myselfghost** [comment]
> I've had this problem with both Intel 660p (not 600, which is on the possibly problematic list) and in the last few days with a WD SN750 2TB NVMe also.
> 
> I've done a new install on a SATA SSD and am running happy again, but I know I'll eventually miss NVMe.
> 
> I don't know what model to buy to try again though honestly.

I also use SN750. The strange thing is that there have been problems recently, and there have been no problems some time ago.

**Comment by myselfghost** [comment]
> @myselfghost
> I'm sorry but I'm not able to reproduce this issue... my NVMe SSD is from LiteOn which is very stable (...since now!)
> 
> I found only one reference for this issue (not related to this config...) and I posted it above...
> 
> I could only suggest to unload `SSDT-NVME.aml` and/or `NVMeFix.kext`...
> 
> Btw, could you confirm, please, that your installation is on an internal SSD (i.e. no external enclosure was used)?

Is internal SSD

**Comment by Kokkolabs** [comment]
I dont have these problems.
I have Samsung Evo Plus ssd and dualboot with Windows 11, all working fine.

**Comment by blodt** [comment]
> > I've had this problem with both Intel 660p (not 600, which is on the possibly problematic list) and in the last few days with a WD SN750 2TB NVMe also.
> > I've done a new install on a SATA SSD and am running happy again, but I know I'll eventually miss NVMe.
> > I don't know what model to buy to try again though honestly.
> 
> I also use SN750. The strange thing is that there have been problems recently, and there have been no problems some time ago.

That's interesting.
So it's almost like something is going wrong "eventually", but a fresh/clean install cures it for a while?

Do we think that might mean it's TRIM related?
Maybe TRIM support is better/worse in macOS on specific models?

**Comment by profzei** [comment]
@blodt 

> Do we think that might mean it's TRIM related?
> Maybe TRIM support is better/worse in macOS on specific models?

If it could be `TRIM` related, then you could try to enable, in your `config.plist` file, `Kernel -> Quirks -> ThirdPartyDrives`

**Comment by blodt** [comment]
> @blodt
> 
> > Do we think that might mean it's TRIM related?
> > Maybe TRIM support is better/worse in macOS on specific models?
> 
> If it could be `TRIM` related, then you could try to enable, in your `config.plist` file, `Kernel -> Quirks -> ThirdPartyDrives`

The note about that feature is turning me off though -- it shouldn't be an issue, right?

_"Note: This option may be avoided on user preference. NVMe SSDs are compatible without the change. For AHCI SSDs on modern macOS version there is a dedicated built-in utility called trimforce. Starting from 10.15 this utility creates EnableTRIM variable in APPLE_BOOT_VARIABLE_GUID namespace with 01 00 00 00 value."_

**Comment by profzei** [comment]
@blodt 

> "Note: This option may be avoided on user preference. NVMe SSDs are compatible without the change. For AHCI SSDs on modern macOS version there is a dedicated built-in utility called trimforce. Starting from 10.15 this utility creates EnableTRIM variable in APPLE_BOOT_VARIABLE_GUID namespace with 01 00 00 00 value."

**It's the reason I never enabled it before**... since we have internal NVMe SSDs, but, in other project, I have turned this quirk on since I have 1 NVMe and 1 AHCI SSD and in the last months I didn't have any issues... (maybe I'm just lucky!)

**Comment by blodt** [comment]
@profzei 

Well I am desperate and will try anything so why not right?
I am doing a fresh install on the NVMe now

**Comment by blodt** [comment]
Is there any chance that PowerTimeoutKernelPanic is related?

That’s also there in Kernel > Quirks

**Comment by profzei** [comment]
@blodt

> Is there any chance that PowerTimeoutKernelPanic is related?

I don't know since the quirk you mentioned should be related to Catalina and not to Catalina+

**Comment by blodt** [comment]
Sounds good - thx

My migration off the SATA SSD is complete and I'm up and running on 11.4 with OC 0.7.1 and both the ThirdPartyDrives quirk enabled as well as the forceRenderStandby=0 boot flag.

Fingers crossed.

**Comment by profzei** [comment]
> Fingers crossed.

@blodt  Ok!

Btw, since you mentioned that you installed Big Sur 11.4, did you use latest EFI (i.e. `v. 2.4.0`) for **USB install**?

**Comment by blodt** [comment]
> > Fingers crossed.
> 
> @blodt Ok!
> 
> Btw, since you mentioned that you installed Big Sur 11.4, did you use latest EFI (i.e. `v. 2.4.0`) for **USB install**?

You mean that latest OpenCore 0.7.1?
Yes I did

Tested out the OC upgrade on my BigSur 11.4 Installation USB Stick first (usual OC update procedure) before copying it over to the EFI on the SATA SSD 11.4 installation...

Then unplugged everything but the NVMe and the USB stick to do a full fresh 11.4 install with OC 0.7.1 that just released.

**Comment by blodt** [comment]
Anyone have any ideas on how to stress test this problem?

Since I did a fresh install, I'm worried I'll think "everything is fine" and then a couple weeks from now...."it will be back..."

It's in my head now.  I just don't trust this NVMe situation anymore.
Really a bummer

**Comment by profzei** [comment]
@blodt Sorry, no I mean if you copied/used my latest [release](https://github.com/profzei/Matebook-X-Pro-2018/releases/tag/v2.4.0) in your Installation USB Stick?

**Comment by blodt** [comment]
> @blodt Sorry, no I mean if you copied/used my latest [release](https://github.com/profzei/Matebook-X-Pro-2018/releases/tag/v2.4.0) in your Installation USB Stick?

Oh - No!
I'm so sorry - I'm not using the same hardware.

I only am here due to the similarity of the NVMe kernel panic
My apologies.  I probably shouldn't even be posting in here.  I'm just desperate for solutions anywhere/everywhere I can hopefully find them.

**Comment by profzei** [comment]
> I only am here due to the similarity of the NVMe kernel panic

@blodt Ok!

**Comment by riletan** [comment]
> @samwzlim I've had the same issue recently for the last 3 months or so, to the point that I almost considered changing the ssd from my MBXPro to solve this issue. It happened all the time.
> 
> In a desperate move I tried to clean the SSD, meaning opened the MBXPro and cleaned with alcohol the SSD contacts and It has solved the issue for about one week.
> 
> I do not know if you had issues with both Windows and Mac, because in my case I had the issue with both.
> 
> I hope this helps.

I face exactly the same issues,  in my case it's is a Samsung 980 NVME ssd running on Z370N-Wifi Hackintosh. 
My previous SSD was WD SN550. When facing panic I thought the SSD was broken so I bought the new 980, but the problem's still there: pannic on macos and bsod on Window. So sad

**Comment by blodt** [comment]
> > @samwzlim I've had the same issue recently for the last 3 months or so, to the point that I almost considered changing the ssd from my MBXPro to solve this issue. It happened all the time.
> > In a desperate move I tried to clean the SSD, meaning opened the MBXPro and cleaned with alcohol the SSD contacts and It has solved the issue for about one week.
> > I do not know if you had issues with both Windows and Mac, because in my case I had the issue with both.
> > I hope this helps.
> 
> I face exactly the same issues, in my case it's is a Samsung 980 NVME ssd running on Z370N-Wifi Hackintosh.
> My previous SSD was WD SN550. When facing panic I thought the SSD was broken so I bought the new 980, but the problem's still there: pannic on macos and bsod on Window. So sad

I have the exact same Motherboard as you. Interesting.
And you've tried yet two more SSD's that supposedly are good to go for macOS hack use.

Something is up for sure.

What BIOS version are you running your MoBo on?

I had always been on F10 forever.
With my fresh install yesterday, I've also moved up to F13 based upon what I've seen at the TM forum.

**Comment by myselfghost** [comment]
Maybe I found a way to circumvent the problem. do not mount windows Volume

**Comment by riletan** [comment]
> > > @samwzlim I've had the same issue recently for the last 3 months or so, to the point that I almost considered changing the ssd from my MBXPro to solve this issue. It happened all the time.
> > > In a desperate move I tried to clean the SSD, meaning opened the MBXPro and cleaned with alcohol the SSD contacts and It has solved the issue for about one week.
> > > I do not know if you had issues with both Windows and Mac, because in my case I had the issue with both.
> > > I hope this helps.
> > 
> > 
> > I face exactly the same issues, in my case it's is a Samsung 980 NVME ssd running on Z370N-Wifi Hackintosh.
> > My previous SSD was WD SN550. When facing panic I thought the SSD was broken so I bought the new 980, but the problem's still there: pannic on macos and bsod on Window. So sad
> 
> I have the exact same Motherboard as you. Interesting.
> And you've tried yet two more SSD's that supposedly are good to go for macOS hack use.
> 
> Something is up for sure.
> 
> What BIOS version are you running your MoBo on?
> 
> I had always been on F10 forever.
> With my fresh install yesterday, I've also moved up to F13 based upon what I've seen at the TM forum.

I am on F14a BIOS firmware. Actually my hack was working very well for a couple of months with WD SN550. Kernel panic happen  after I updated from 11.2.3 to 11.4. First I thought something goes wrong with 11.4 so I decided to downgrade to 11.1, but the panic still there, and as you see. Problems can be solved even when I changed the SSD :(

**Comment by blodt** [comment]
> Maybe I found a way to circumvent the problem. do not mount windows Volume

Please do explain!

I do run dual boot on my Hack (each on its own drive).
My bootcamp/windows install is on a SATA SSD though, not another NVMe

Do you think it's related or part of the issue?

**Comment by riletan** [comment]
> > > @samwzlim I've had the same issue recently for the last 3 months or so, to the point that I almost considered changing the ssd from my MBXPro to solve this issue. It happened all the time.
> > > In a desperate move I tried to clean the SSD, meaning opened the MBXPro and cleaned with alcohol the SSD contacts and It has solved the issue for about one week.
> > > I do not know if you had issues with both Windows and Mac, because in my case I had the issue with both.
> > > I hope this helps.
> > 
> > 
> > I face exactly the same issues, in my case it's is a Samsung 980 NVME ssd running on Z370N-Wifi Hackintosh.
> > My previous SSD was WD SN550. When facing panic I thought the SSD was broken so I bought the new 980, but the problem's still there: pannic on macos and bsod on Window. So sad
> 
> I have the exact same Motherboard as you. Interesting.
> And you've tried yet two more SSD's that supposedly are good to go for macOS hack use.
> 
> Something is up for sure.
> 
> What BIOS version are you running your MoBo on?
> 
> I had always been on F10 forever.
> With my fresh install yesterday, I've also moved up to F13 based upon what I've seen at the TM forum.

Hi, Have you checked "rc6 render standby" option in BIOS settings. I have it enabled, I read from https://dortania.github.io/OpenCore-Post-Install/universal/sleep.html#:~:text=IGP%20causes%20NVMe,opens%20new%20window) 

so I switch it to disabled state. the panic was gone for 2 days, its amazing!

**Comment by blodt** [comment]
> > > > @samwzlim I've had the same issue recently for the last 3 months or so, to the point that I almost considered changing the ssd from my MBXPro to solve this issue. It happened all the time.
> > > > In a desperate move I tried to clean the SSD, meaning opened the MBXPro and cleaned with alcohol the SSD contacts and It has solved the issue for about one week.
> > > > I do not know if you had issues with both Windows and Mac, because in my case I had the issue with both.
> > > > I hope this helps.
> > > 
> > > 
> > > I face exactly the same issues, in my case it's is a Samsung 980 NVME ssd running on Z370N-Wifi Hackintosh.
> > > My previous SSD was WD SN550. When facing panic I thought the SSD was broken so I bought the new 980, but the problem's still there: pannic on macos and bsod on Window. So sad
> > 
> > 
> > I have the exact same Motherboard as you. Interesting.
> > And you've tried yet two more SSD's that supposedly are good to go for macOS hack use.
> > Something is up for sure.
> > What BIOS version are you running your MoBo on?
> > I had always been on F10 forever.
> > With my fresh install yesterday, I've also moved up to F13 based upon what I've seen at the TM forum.
> 
> Hi, Have you checked "rc6 render standby" option in BIOS settings. I have it enabled, I read from https://dortania.github.io/OpenCore-Post-Install/universal/sleep.html#:~:text=IGP%20causes%20NVMe,opens%20new%20window)
> 
> so I switch it to disabled state. the panic was gone for 2 days, its amazing!

Hi

I saw that also, yeah.  It is currently enabled in my BIOS, but I believe the forceRenderStandby=0 boot flag is disabling that on macOS boot up (I am using that boot flag).

Any idea how relevant (or not) rc6 is for the Windows side?

**Comment by riletan** [comment]
@blodt  I think the setting in bios is valid for both window and macos.

**Comment by profzei** [comment]
I consider **closed** this issue...

Official fix is the following: adding `forceRenderStandby=0` boot-args to disable RC6 Render Standby and fix [IGP causes NVMe Kernel Panic CSTS=0xffffffff](https://github.com/acidanthera/bugtracker/issues/1193) after sleep.

Ref: [https://dortania.github.io/OpenCore-Post-Install/universal/sleep.html#fixing-gpus
acidanthera/bugtracker#1193](https://dortania.github.io/OpenCore-Post-Install/universal/sleep.html#fixing-gpus)

If this issue shouldn't be fixed then, please, **refer to** [IGP causes NVMe Kernel Panic CSTS=0xffffffff](https://github.com/acidanthera/bugtracker/issues/1193) **for debugging purposes**.
