### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by KristianUSN** [profzei/Matebook-X-Pro-2018#172]
So in the latest release you mention this: 
`Update SSDT-XHC.aml: using TBTS variable for fixing Windows 10 dual-booting issue`
Does this mean that dual booting from the same SSD is doable now? I've tried to do so several times following reliable guides but each time booting into Windows from OpenCore Windows gives me a blue screen with an error code.

**Comment by KristianUSN** [comment]
Yeah, your latest release seems to make dual booting work flawlessly. Nice, thank you for all your hard work!

Do you have any idea what I should do when installing a third OS? I made another partition and did a custom Fedora install there but it won't show up in OpenCore or in the UEFI boot menu.

**Comment by profzei** [comment]
@KristianUSN I've never done a triple boot, but answer should be in [Dortania's guide](https://github.com/dortania/OpenCore-Multiboot/blob/master/oc/linux.md)

**Comment by KristianUSN** [comment]
Yeah I figured it out, I just did a minor error when installing. It feels nice to have triple boot on this machine
