### ISSUE TITLE
Battery Percentage is inaccurate 

### ISSUE THREAD

**Issue by abraham-berlin** [profzei/Matebook-X-Pro-2018#173]
Hello,

I am currently having an issue where the battery percentage indicator is inaccurate. When I my computer is unpluged it will say the battery is at 100% for like an hour of usage. Eventually it will start to go down, but is still not representitive of what it should be. I also get this "Important Battery Message"
![image](https://user-images.githubusercontent.com/47614908/121051419-0dba0180-c77f-11eb-831c-473fde729ed9.png)

**Comment by abraham-berlin** [comment]
The battery percent issue resolved itself randomly.

**Comment by samwzlim** [comment]
> The battery percent issue resolved itself randomly.

Hi, did you perform any specific action to get the message to go away? I'm facing the exact same issue as you did.
