### ISSUE TITLE
116% cpu usage

### ISSUE THREAD

**Issue by Zephariael** [profzei/Matebook-X-Pro-2018#174]
This task called "kernel_task" is causing the cpu to heat up, the battery to drain, and the fans to spin highly. 

What is the issue that is causing this? Is it a kernel panic?

![Screen Shot 2021-06-07 at 10 26 21 PM](https://user-images.githubusercontent.com/73377258/121118489-894b9b00-c7df-11eb-9858-84467a3d8ee1.png)

**Comment by unverbraucht** [comment]
I think you might be seeing the same issue as I did in #147 . My guess is that it's related to sleep or hibernation in combination with the wifi drivers. I've only seen in occasionally and a reboot always fixes it.

**Comment by steinano** [comment]
I've did the pmset (sleep/hibernate) settings as in the instructions, haven't had the issue after that.

**Comment by Zephariael** [comment]
Steinano had the correct answer. 

For anyone else with this issue, Follow the sleep/hibernate tutorial given by Profzei in the instructions on the main page. Solved the issue.

Huge thanks to steinano!

**Comment by rohirrim27** [comment]
Hi @Zephariael & @steinano! Are the following the only sleep/hibernate instructions you followed? I have the same settings but still running into the issue mentioned by @unverbraucht.

sudo pmset -a standby 0
sudo pmset -a powernap 0 
sudo pmset -a proximitywake 0
sudo pmset -a tcpkeepalive 0
sudo pmset -a womp 0

**Comment by Zephariael** [comment]
> Hi @Zephariael & @steinano! Are the following the only sleep/hibernate instructions you followed? I have the same settings but still running into the issue mentioned by @unverbraucht.
> 
> sudo pmset -a standby 0
> sudo pmset -a powernap 0
> sudo pmset -a proximitywake 0
> sudo pmset -a tcpkeepalive 0
> sudo pmset -a womp 0

@rohirrim27 

Profzei's instructions are to apply the sleep settings after every update. Applying through terminal multiple times still hasn't worked for me however. I've gotten around this issue by either shutting down every time, or enabling hibernate. Both solutions are about the same I've found. 
Maybe this will be magically fixed in MacOS Monteray lol.
