### ISSUE TITLE
Installation tutorial for ppl without working macOS

### ISSUE THREAD

**Issue by ShaggaSonOfDolf** [profzei/Matebook-X-Pro-2018#175]
Hi,

is there a good write up or tutorial for the creation of a Matebook Hackintosh using Big Sur, without already having an operational OSX installation (preferably based on Linux)? The ones I found either don't seem to work for me and/or are pretty old and talk about installing Catalina.

The way I tried was to create the com.apple.recovery (or something like that) folder in the usb stick root, put the recovery files in there and add the files from your repo in the EFI folder also on the usb stick root. The Matebook booted into recovery, I was (with some hassle) able to connect to the wifi - a progress compared to earlier attempts - and start the installation.

It took quite long, after a reboot I could choose a finder icon with the title "macOS installer".  Selecting this showed the apple boot screen with a installation time of about 25 minutes. After another reboot i saw only the apple boot screen but nothing happening for quite some time. After another automatic reboot the Matebook UEFI shows me the message that there is no bootable media connected.  Which means, that not only macOS is not installed but also that I have to recreate the installer stick.

So I am kinda lost now and some help would be greatly appreciated.

Thanks!

**Comment by R-Teer** [comment]
Your best to simply do a clean install of Catalina, with the latest release of the repo. For Catalina, see the readme for getting the wifi to work on first boot.  Once Catalina is installed, open the app store, sign in and search for Big Sur, its a single update to the latest 11.4 update. Just did a full clean install this week everything works great

**Comment by samwzlim** [comment]
@ShaggaSonOfDolf I highly suggest you read through [this guide](https://dortania.github.io/OpenCore-Install-Guide/) to get macOS running on your machine. This is like the holy grail of hackintosh tutorials. Following this guide, I was able to directly install Big Sur. Regarding the gathering of kexts for your machine, assuming that yours is the Matebook X Pro 2018, you can simply ignore that as the owner of this github repo has already done all the hard work of compiling the kexts. You can simply download the latest EFI under releases.

**Comment by ShaggaSonOfDolf** [comment]
@samwzlim Thanks for pointing that out. Now it worked for me. I already tried that guide but I think it didn't work because I choose the wrong recovery in the boot menu when booting the first time.

Now everything works pretty much flawlessly. The only thing is that the sound seems kinda quite. With my headset connected I basically have to listen on max volume to get normal volume. Is there a way to boost this?

And is there a easy to setup way for the keyboard for using Windows/Linux shortcuts? It's kinda painful, when you never used macOS.

**Comment by samwzlim** [comment]
> @samwzlim Thanks for pointing that out. Now it worked for me. I already tried that guide but I think it didn't work because I choose the wrong recovery in the boot menu when booting the first time.
> 
> Now everything works pretty much flawlessly. The only thing is that the sound seems kinda quite. With my headset connected I basically have to listen on max volume to get normal volume. Is there a way to boost this?
> 
> And is there a easy to setup way for the keyboard for using Windows/Linux shortcuts? It's kinda painful, when you never used macOS.

For the sound issue you're facing, firstly, try going into system preferences > sound and ensure that the volume for the individual built-in speakers (both of them) are set to the max. 

Regarding keyboard shortcuts, maybe someone else can chime in as I don't really make use of windows shortcuts.
