### ISSUE TITLE
Can't install MacOS on MateBook X Pro (MACH-WX29)

### ISSUE THREAD

**Issue by AMC-GME** [profzei/Matebook-X-Pro-2018#176]
Hello,

I'm really trying to install macOS Big Sur (or Catalina) on my MateBook X Pro (MACH-WX29). Unfortunately, I can't get it past the installation.  I tried several EFI versions 2.3.0, 2.2.0, 2.1.0, and even older ones like 1.3.0.

What I did:
1. Flashed the USB(16GB) drive with RUFUS (GPT; No Bootable; BIOS or UEFI; FAT32; 8192 Byte).
2. Downloaded the macOS (Big Sur, Catalina) with macrecovery.py from the OpenCore package.
3. Created a folder named Moved it to the "com.apple.recovery.boot" and moved the MacOS files from the "mac recovery" folder to this newly created folder on the USB stick.
4. Copied EFI folder from OpenCore Package (X64) to a USB stick.
5. Downloaded and Copied the Files from profzei/Matebook-X-Pro-2018 with version 2.3.0 and replaced the files and folders BOOT and OC.
6. Changed the config.plist with the data from GenSMBIOS.bat to update the Serial numbers and etc.. (MacBookPro16,3)
6. Unplugged the USB from Windows PC, and plugged it into the MateBook X Pro.
7. Disabled safe boot in the BIOS on MateBook.
8. Booted the macOS installer from a USB stick, erased the SSD to the APFS with GPT.
9. Connected to the Wi-Fi.
10. Clicked on the "Reinstall macOS Big Sur" button and agreed to the Terms, chosen the SSD, and started the installation.
11. MateBook restarts while installing the macOS unexpectedly. After reboot, all is the same and I'm trying steps 9-10 again.

Any idea, why I can't get it past the installation, and why this is happening.

![WhatsApp Image 2021-06-18 at 02 43 23 (2)](https://user-images.githubusercontent.com/86086250/122489100-30e67b80-cfdf-11eb-84ee-4a56568b65fe.jpeg)
![WhatsApp Image 2021-06-18 at 02 43 23](https://user-images.githubusercontent.com/86086250/122489103-317f1200-cfdf-11eb-9372-a98b09befa43.jpeg)
![WhatsApp Image 2021-06-18 at 02 43 24 (1)](https://user-images.githubusercontent.com/86086250/122489105-3217a880-cfdf-11eb-99cf-6bbb4e815f8f.jpeg)
![WhatsApp Image 2021-06-18 at 02 43 24 (2)](https://user-images.githubusercontent.com/86086250/122489106-3217a880-cfdf-11eb-8f4c-1343c47ef450.jpeg)
![WhatsApp Image 2021-06-18 at 02 43 24](https://user-images.githubusercontent.com/86086250/122489107-32b03f00-cfdf-11eb-81b0-99abcc1ec710.jpeg)
![WhatsApp Image 2021-06-18 at 02 43 25 (1)](https://user-images.githubusercontent.com/86086250/122489108-32b03f00-cfdf-11eb-8223-6278dc9d6e57.jpeg)
![WhatsApp Image 2021-06-18 at 02 43 25](https://user-images.githubusercontent.com/86086250/122489109-3348d580-cfdf-11eb-85b0-792aa30f12fd.jpeg)
![WhatsApp Image 2021-06-18 at 02 43 26 (1)](https://user-images.githubusercontent.com/86086250/122489110-3348d580-cfdf-11eb-9af4-50c3a3fb9578.jpeg)
![WhatsApp Image 2021-06-18 at 02 43 26](https://user-images.githubusercontent.com/86086250/122489111-33e16c00-cfdf-11eb-94cf-04bf5af26382.jpeg)
![WhatsApp Image 2021-06-18 at 02 43 23 (1)](https://user-images.githubusercontent.com/86086250/122489113-33e16c00-cfdf-11eb-91a7-8981d81d454f.jpeg)

Unfortunately, I don't have a Mac to create any installation media.

CPU Intel i7-8550u
RAM 16GB
SSD Samsung MZVLB512HAJQ 512GB

Thanks!

**Comment by AshleyMiller9696** [comment]
What did you change so that it installs?
Maybe this will help others
