### ISSUE TITLE
OC stops working with the new bios version: 1.36

### ISSUE THREAD

**Issue by wswn** [profzei/Matebook-X-Pro-2018#178]
I upgrade BIOS to the latest version 1.36 when I upgrade drivers by accident. Then the OC stops working. The problem may be induced by ACPI since the log shows the error as below:

`ACPI Error: [_QBF] Namespace lookup failure, AE_ALREADY_EXISTS`

As stated **MateBook X Pro EFI v1.9.0**, **SSDT-BIOS.aml** defines **_QBF** for testing. Thus, I just disable it in **config.list** and successfully boot into macOS. However, I don't know what consequences this will bring.

Does the disabling of this file cause some terrible effects?

**Comment by profzei** [comment]
> Does the disabling of this file cause some terrible effects?

No, be sure! I've added it to implement method `_QBF` (it is related to battery) into bios versions **< 1.33**
Probably it's better to update homepage to underline this aspect... I'll do it with next release with Monterey support

**Comment by wswn** [comment]
@profzei Get it. Thank you.

**Comment by profzei** [comment]
> paypal says Donations to this recipient aren't supported in this country (China).

@wswn Don't worry (I think it's a Paypal limitation...): I really appreciate your intention!
