### ISSUE TITLE
AirportItlwm,fix DHCP issue

### ISSUE THREAD

**Issue by myselfghost** [profzei/Matebook-X-Pro-2018#179]
https://github.com/OpenIntelWireless/itlwm/commit/3e63230703f11d6daf13f5fa69d6e77a65b8cf3c

AirportItlwm: fix DHCP issue and key update issue. Seems that we have a problem in our entire thread model.

**Comment by ldan93** [comment]
On my setup, this commit greatly improves the stability of the connexion, it's really night and day !

**Comment by profzei** [comment]
@myselfghost @ldan93 Commit for `AirportItlwm` included in [latest release](https://github.com/profzei/Matebook-X-Pro-2018/releases)

**Comment by myselfghost** [comment]
> On my setup, this commit greatly improves the stability of the connexion, it's really night and day !

Thank you very much for your contribution
