### ISSUE TITLE
Won't boot to install. Black Screen after "Boot macOS Install from maxOS Base System"

### ISSUE THREAD

**Issue by slabach** [profzei/Matebook-X-Pro-2018#18]
So, I'm following the instructions from the below guide, but using the BOOT and CLOVER files from this repo instead of those in gnodipac's

https://github.com/gnodipac886/MatebookXPro-hackintosh/blob/master/install-without-windows.md

Spec's
i7-8550u
16GB Ram
Toshiba 512GB M.2

Trying to install Catalina 10.15.4 downloaded using gibMacOS, and using the makeinstall.bat also in gibMacOS. Then swapping the Boot and Clover files from this repo into the EFI folder on the flash drive... If I use gnodipac's files from his repo, it pops the Apple logo and stops. Never shows a loading bar or does anything (left it for like 45 minutes). If I use the one's from this repo, it goes to black screen and wont do anything else (also left for about 45 minutes).

Am I missing something? I've followed the guide to a T to this point.

**Comment by profzei** [comment]
Hi, try to use the instructions at [#16](https://github.com/profzei/Matebook-X-Pro-2018/issues/16). And let me know if that works (it should work!😉)

**Comment by slabach** [comment]
Well, it flashed this, rebooted, but went straight to Windows, I restarted, and now selecting that in Clover, just stops on this screen and freezes

https://imgur.com/a/iwG0BmB

**Comment by slabach** [comment]
@profzei are you saying i should ONLY use the Clover files from https://github.com/profzei/Matebook-X-Pro-2018/issues/16 ? Or use those files in addition to the ones from this repo?

**Comment by slabach** [comment]
@profzei I got it to install, so I'll resolve this one. Appreciate it. Still some things I can't get working like the tochpad, and there's no scaling or resolution change options so everything is tiny.
