### ISSUE TITLE
Variable download speeds

### ISSUE THREAD

**Issue by jdckl** [profzei/Matebook-X-Pro-2018#180]
Hello, first of all - thank you for this project. I successfully installed Mac OS on my Matebook X Pro and I am super grateful for all of the instructions and everything.

I am currently dealing with a peculiar issue. Some downloads take ages. Not all of them, but some. For example downloading an Ubuntu image (for dev purposes) via wget/vagrant takes days and runs at 4kb/s. Same goes for some other services - some brew packages take ages, simple chrome browser download directly from google is running at 10b/s. I am not able to pinpoint this issue at all - tried changing my DNS settings, switching wifi from regular to 5Ghz, restarting, disconnecting, wget/curl, etc.

Same goes for some websites. Some load just fine, some load long. There is nothing wrong with my network otherwise, my desktop (Windows) has everything working correct and for example the same download of the Ubuntu image downloads at 36mb/s. Is there anyone with a similar issue? Or perhaps someone with more knowledge of Mac OS networking who could give me some tips?

Mac OS Big Sur 11.4

Thank you in advance.

**Comment by jdckl** [comment]
After some more testing: 

This issue appears to occur after sleep/hibernation. If I shut down and start the laptop its fine and the mentioned image downloads at top speeds. Also noticed the GUI of Mac OS stutters a little after wake.

**Comment by profzei** [comment]
Maybe it is fixed with commit [itlwm/7e800d8](https://github.com/OpenIntelWireless/itlwm/commit/7e800d8e3f48dd4e1cf1602937455afe785deed8)
