### ISSUE TITLE
Higher power consumption with AirportItlwm.kext version 2.0.0

### ISSUE THREAD

**Issue by espitgn** [profzei/Matebook-X-Pro-2018#181]
Hi,

I noticed this comparating AirportItlwm.kext version 2.0.0 (included since EFI 2.3.0) and version 1.3.0 (I think the last EFI with this version was 1.9.0).

Using Intel power gadget, I saw the value of consumption (IDLE) with AirportItlwm.kext 1.3.0 was about 0,80-0,90 W. With 2.0.0 version, this value rised to 1,50-1,60 W. (using EFI 2.3.0 in both cases).

I know, version 2.0.0 is faster and more stable than 1.3.0, but this power consumption increase are quite bigger and causes a faster battery draining.

Did you experience something similar?

Thks

**Comment by profzei** [comment]
I'll check this asap...

**Comment by espitgn** [comment]
Hi Profzei. Thanks for your answer. 
I didn't report this issue on itlwm Gitter page. I was waiting for your answer ;)
