### ISSUE TITLE
Monterey 12.0 beta 3 - Updated at normal, everything working well

### ISSUE THREAD

**Issue by R-Teer** [profzei/Matebook-X-Pro-2018#182]
Just updates to the 12.0 B3, updated from B2

Will update regarding stability but all seems good for now.

Looking forward to updates!

**Comment by profzei** [comment]
@R-Teer 
Ok! 
I didn’t test too much Monterey since I’m on my holidays till the end of July… I’ll restart working on it in August, but it seems quite stable

**Comment by samwzlim** [comment]
> Just updates to the 12.0 B3, updated from B2
> 
> 
> 
> Will update regarding stability but all seems good for now.
> 
> 
> 
> Looking forward to updates!

That's great to hear. Unfortunately, I wasn't so lucky and my MBXP now refuses to boot past the Huawei logo and is stuck in a bootloop ever since it restarted to install the 12.0 B3 software update. I wonder if this was caused by the software update or the fact that I disabled Windows bootloader using Bootice the night before, as I was having issues where Windows bootloader would interfere with OpenCore. Everything went smoothly after I disabled Windows bootloader and OpenCore was working properly, until the software update happened. Now I'm unable to access the OC boot picker, BIOS, and not even booting from USB helps. Even trying a factory reset by pressing and holding F8/F10 as instructed on Huawei's website on startup didn't help. Any help would be appreciated! At the moment I'm stuck with an expensive brick :(

**Comment by JonnIEnglish** [comment]
Have you tried disabling "secure boot" in BIOS after it reset?

**Comment by samwzlim** [comment]
> Have you tried disabling "secure boot" in BIOS after it reset?

If you're referring to me, then, BIOS can't be accessed at all. My MBXP is still stuck on a bootloop.

**Comment by Kokkolabs** [comment]
> > Just updates to the 12.0 B3, updated from B2
> > Will update regarding stability but all seems good for now.
> > Looking forward to updates!
> 
> That's great to hear. Unfortunately, I wasn't so lucky and my MBXP now refuses to boot past the Huawei logo and is stuck in a bootloop ever since it restarted to install the 12.0 B3 software update. I wonder if this was caused by the software update or the fact that I disabled Windows bootloader using Bootice the night before, as I was having issues where Windows bootloader would interfere with OpenCore. Everything went smoothly after I disabled Windows bootloader and OpenCore was working properly, until the software update happened. Now I'm unable to access the OC boot picker, BIOS, and not even booting from USB helps. Even trying a factory reset by pressing and holding F8/F10 as instructed on Huawei's website on startup didn't help. Any help would be appreciated! At the moment I'm stuck with an expensive brick :(

Have you tried pushing power button long time for shutdown completelety?

**Comment by Kokkolabs** [comment]
I try update beta2 lastweek and it got stuck on boot, i try again tomorrow with -lilubetaall boot option.

**Comment by samwzlim** [comment]
> I try update beta2 lastweek and it got stuck on boot, i try again tomorrow with -lilubetaall boot option.

Pushed the power button until it restarted but it still doesn't boot. Ever since the first developer beta, I've included -lilubetaall in boot arguments.

**Comment by JonnIEnglish** [comment]
> > Have you tried disabling "secure boot" in BIOS after it reset?
> 
> If you're referring to me, then, BIOS can't be accessed at all. My MBXP is still stuck on a bootloop.

I'm sure you can just force shutdown by holding the power button, and then press F12 repeatedly on startup to get into bios?

**Comment by Kokkolabs** [comment]
> 
> I'm sure you can just force shutdown by holding the power button, and then press F12 repeatedly on startup to get into bios?

F2 go bios.

**Comment by samwzlim** [comment]
Apparently my ssd either died or got corrupted because I purchased a new ssd (WD SN750) and my MBXP is able to detect it, whereas it wouldn't on the previous one (Toshiba)

**Comment by Kokkolabs** [comment]
I test again update to Monterey beta and it update well but stuck on first boot halfway.

Latest BigSur beta works well, but not Monterey. I on now clean install with BigSur 11.4.

I add -lilubetaall option, not help.
Any ideas?

**Comment by samwzlim** [comment]
> I test again update to Monterey beta and it update well but stuck on first boot halfway.
> 
> Latest BigSur beta works well, but not Monterey. I on now clean install with BigSur 11.4.
> 
> I add -lilubetaall option, not help.
> Any ideas?

Can you include -v as well in your boot arguments? This will pinpoint what the error exactly is.

**Comment by Kokkolabs** [comment]
> > I test again update to Monterey beta and it update well but stuck on first boot halfway.
> > 
> > Latest BigSur beta works well, but not Monterey. I on now clean install with BigSur 11.4.
> > 
> > I add -lilubetaall option, not help.
> > Any ideas?
> 
> Can you include -v as well in your boot arguments? This will pinpoint what the error exactly is.

Have to add when test again, some Bluetooth related it was first time.

**Comment by Kokkolabs** [comment]
So i testing many times at different config.plist setting and allways end to reboot.
now i get first time booted that i got picture before it reboot itself, this was same config that i use BigSur.
Sorry bad picture.
![PXL_20210801_171751362](https://user-images.githubusercontent.com/48392961/127780486-72256255-0a00-4554-a867-9408d9096a6c.jpg)
But i dont give up, before Monterey is out :) It reboot about three seconds after picture and it was really slow boot eg. 20minutes.

**Comment by bfrorum10** [comment]
> So i testing many times at different config.plist setting and allways end to reboot.
> now i get first time booted that i got picture before it reboot itself, this was same config that i use BigSur.
> Sorry bad picture.
> ![PXL_20210801_171751362](https://user-images.githubusercontent.com/48392961/127780486-72256255-0a00-4554-a867-9408d9096a6c.jpg)
> But i dont give up, before Monterey is out :) It reboot about three seconds after picture and it was really slow boot eg. 20minutes.

Hi Bro,

use the last nightly Kext an is all is good. if that dont work. I here in the German Forums that's work with the OC v6.7 :)

I Updated Monterey into the external driver with this EFI. All just I use the nightly kext for it. if you have any problem use the booting -lilubetaall.  

lets go bro

**Comment by Kokkolabs** [comment]
> > So i testing many times at different config.plist setting and allways end to reboot.
> > now i get first time booted that i got picture before it reboot itself, this was same config that i use BigSur.
> > Sorry bad picture.
> 
> > But i dont give up, before Monterey is out :) It reboot about three seconds after picture and it was really slow boot eg. 20minutes.
> 
> Hi Bro,
> 
> use the last nightly Kext an is all is good. if that dont work. I here in the German Forums that's work with the OC v6.7 :)
> 
> I Updated Monterey into the external driver with this EFI. All just I use the nightly kext for it. if you have any problem use the booting -lilubetaall.
> 
> lets go bro

Thanks, got working :)

**Comment by samwzlim** [comment]
> Just updates to the 12.0 B3, updated from B2
> 
> Will update regarding stability but all seems good for now.
> 
> Looking forward to updates!

Hey @R-Teer, sorry for the mention, but just wondering, how is universal clipboard working for you on Monterey? Do you have other apple devices to test? For me, universal clipboard only works from my other apple devices to the hackintosh, but not the other way around. It's as if the hackintosh isn't sending the clipboard contents to the other devices.

**Comment by profzei** [comment]
**macOS Monterey** is in **Beta phase**: please report any issues **after first official release in autumn**.

I consider **closed** this issue

**Comment by samwzlim** [comment]
> **macOS Monterey** is in **Beta phase**: please report any issues **after first official release in autumn**.
> 
> I consider **closed** this issue

Alright understood, but after updating to macOS 12 Beta 5, bluetooth isn't turning on for me anymore. I injected BlueToolFixup.kext as I did in previous beta versions. I simply updated via system preferences, without changing my configuration. Are you facing the same issue, or is it just me? It's alright if you are unable to find a solution now, just wanted to know because I found out that some people are facing this issue as well, but not all.

**Comment by profzei** [comment]
@samwzlim 
[See for reference this issue](https://github.com/OpenIntelWireless/IntelBluetoothFirmware/issues/332) and add your input please!

**Comment by samwzlim** [comment]
> @samwzlim
> [See for reference this issue](https://github.com/OpenIntelWireless/IntelBluetoothFirmware/issues/332) and add your input please!

I fixed it by changing my SMBIOS from MacbookPro16,3 to MacbookPro15,2. Able to use Bluetooth as usual now but handoff still only works one way (iPhone/iPad to Mac but not the other way around)

**Comment by profzei** [comment]
> I fixed it by changing my SMBIOS from MacbookPro16,3 to MacbookPro15,2.

@samwzlim  You are right! MacBookPro15,2 seems to be the only SMBIOS actually working to activate Bluetooth device on macOS Monterey beta 5 ... honestly, I had not even tried it since its CPU specifics are clearly far from being optimal: for our hardware configuration the best profiles are MacBookPro14, 1 or MacBookPro15.4 or MacBookPro16.3 ... but at present MacBookPro15,4 and MacBookPro16,3 seem to not be suitable, but I don't know / understand the reason!

Macos Monterey Beta 6 came out recently... I'm curious to see whether there have been any improvements in this sense or not... I will update as soon as possible!

**Comment by samwzlim** [comment]
> > I fixed it by changing my SMBIOS from MacbookPro16,3 to MacbookPro15,2.
> 
> @samwzlim You are right! MacBookPro15,2 seems to be the only SMBIOS actually working to activate Bluetooth device on macOS Monterey beta 5 ... honestly, I had not even tried it since its CPU specifics are clearly far from being optimal: for our hardware configuration the best profiles are MacBookPro14, 1 or MacBookPro15.4 or MacBookPro16.3 ... but at present MacBookPro15,4 and MacBookPro16,3 seem to not be suitable, but I don't know / understand the reason!
> 
> Macos Monterey Beta 6 came out recently... I'm curious to see whether there have been any improvements in this sense or not... I will update as soon as possible!

I'm currently on Monterey Beta 6, and on SMBIOS MacbookPro16,3, Bluetooth couldn't be turned on either. So switching to MacBookPro15,2 did the trick for me. Also, which SMBIOS will be the most suitable for my machine? It's the Matebook X Pro 2018 with the i5-8250u and integrated graphics. Based on my understanding, it should be between MacBookPro15,2, MacBookPro15,4 and MacBookPro16,3 since the cpu inside the Matebook X Pro 2018 is the 8th gen variant right? On [dortania's guide](https://dortania.github.io/OpenCore-Install-Guide/extras/smbios-support.html#how-to-decide), it displays these 3 SMBIOS's to be under the cpu family of Coffee Lake(U), which matches the ones in the MBXP. 

Although it is not perfect and turning off bluetooth will result in inability to turn on bluetooth again until a restart.

**Comment by profzei** [comment]
@samwzlim 
I'm testing **MacOS Monterey beta 6**: for getting a working Bluetooth we can use `MacBookPro14,1` (which was our traditional choice) and `MacBookPro15,2` only SMBIOSes... 
From now on I choose to use `MacBookPro15,2` to give our build more longevity for future updates...

> Based on my understanding, it should be between MacBookPro15,2, MacBookPro15,4 and MacBookPro16,3 since the cpu inside the Matebook X Pro 2018 is the 8th gen variant right? On dortania's guide, it displays these 3 SMBIOS's to be under the cpu family of Coffee Lake(U), which matches the ones in the MBXP.

Unfortunately, our processor family is a cross between Kaby-Lake and Coffee-Lake ones: it's a Kaby-Lake **R** where **R** means **Refresh**... we don't have a REAL Coffee-Lake processor nor a REAL Coffee-Lake architecture... our architecture is more similar to a Kaby-Lake one: for this reason `MacBookPro14,1` was my best choice for writing good SSDTs patches!

**Comment by profzei** [comment]
@samwzlim 

> Although it is not perfect and turning off bluetooth will result in inability to turn on bluetooth again until a restart.

It's a known issue mentioned in [acidanthera/BrcmPatchRAM#12](https://github.com/acidanthera/BrcmPatchRAM/pull/12#issue-668963999) (See last item in **Technical Notes**)

**Comment by samwzlim** [comment]
> @samwzlim
> I'm testing **MacOS Monterey beta 6**: for getting a working Bluetooth we can use `MacBookPro14,1` (which was our traditional choice) and `MacBookPro15,2` only SMBIOSes...
> From now on I choose to use `MacBookPro15,2` to give our build more longevity for future updates...
> 
> > Based on my understanding, it should be between MacBookPro15,2, MacBookPro15,4 and MacBookPro16,3 since the cpu inside the Matebook X Pro 2018 is the 8th gen variant right? On dortania's guide, it displays these 3 SMBIOS's to be under the cpu family of Coffee Lake(U), which matches the ones in the MBXP.
> 
> Unfortunately, our processor family is a cross between Kaby-Lake and Coffee-Lake ones: it's a Kaby-Lake **R** where **R** means **Refresh**... we don't have a REAL Coffee-Lake processor nor a REAL Coffee-Lake architecture... our architecture is more similar to a Kaby-Lake one: for this reason `MacBookPro14,1` was my best choice for writing good SSDTs patches!

Oh I see, thanks for the insight. Learning something new everyday :D
