### ISSUE TITLE
Universal clipboard not working reliably on Monterey

### ISSUE THREAD

**Issue by samwzlim** [profzei/Matebook-X-Pro-2018#184]
Hi, ever since I updated to Monterey, universal clipboard has not been working reliably for me. I own an iPad an an iPhone, and universal clipboard works flawlessly from between those 2 devices and from my iPad and iPhone to my hackintosh, but not the other way around, meaning I am able to copy contents from my iPad and iPhone to my hackintosh, but not the other way around. This wasn't the case back in Big Sur. I am using BlueToolFixup.kext and Airportitlwm 2.00 beta for Monterey to enable Bluetooth and wifi. I haven't really tested handoff, but at the time of writing this, my hackintosh is able to pickup where I left off on my other apple devices, but not the other way around. It's as if my other apple devices aren't able to detect the hackintosh. 

Are there anybody else who are running Monterey on their MBXP facing the same issues as me? I've grown reliant to universal clipboard :(

**Comment by samwzlim** [comment]
Hi @profzei, sorry for the ping, but are you facing this on Monterey as well? Universal clipboard has gotten extremely important in my workflow, and the earlier I get to solving it, the better. Once again, thank you for your help!

**Comment by profzei** [comment]
Se: [https://github.com/profzei/Matebook-X-Pro-2018/issues/182#issuecomment-903145870](https://github.com/profzei/Matebook-X-Pro-2018/issues/182#issuecomment-903145870)

**Comment by profzei** [comment]
@samwzlim 
Here it is a **Safari** screenshot taken from my iPhone where `MacBook Pro di xxx` is my MBXP running macOS Monterey beta 6 and `iMac di xxx` is my NUC7 running Catalina.
![IMG_4985](https://user-images.githubusercontent.com/47076961/131922604-520fe544-96f2-4a00-a435-33803284770e.PNG)

**Comment by samwzlim** [comment]
> @samwzlim
> Here it is a **Safari** screenshot taken from my iPhone where `MacBook Pro di xxx` is my MBXP running macOS Monterey beta 6 and `iMac di xxx` is my NUC7 running Catalina.
> ![IMG_4985](https://user-images.githubusercontent.com/47076961/131922604-520fe544-96f2-4a00-a435-33803284770e.PNG)

Safari seems to work only one way for me, although I'm not very sure how Safari functions because I don't use it personally. Can you check if universal clipboard works both ways for you? i.e. from iPhone to Mac and Mac to iPhone
