### ISSUE TITLE
New release ?

### ISSUE THREAD

**Issue by ldan93** [profzei/Matebook-X-Pro-2018#185]
Hi Profzei,

I've seen in the changelog that you've been quite active since the latest release in June. 
Do you plan to publish a new release soon ? I'm quite excited to test some of the change ! Especially the change related to WhateverGreen (I still face some weird glitches with my USB-C/DP monitor, hopefully it might help) and Secure Boot.

**Comment by profzei** [comment]
> Do you plan to publish a new release soon ?

@ldan93 Affermative!
What am I working this weekend on?
- I'm testing a little improvement for sound
- I'm fixing two annoying warnings for `Resources` folder
- I'm testing what `OpenCore` manual suggest for `PlatformInfo` details
Then I need to write a guide for **Secure Boot** (it's not so easy... since I do not like writing guides!)

Updating `kexts` and `OpenCore` release from `DEBUG v. 0.7.2` to `RELEASE v. 0.7.3` is very simple (I've done it for [my other project](https://github.com/profzei/NUC7i3BNH))... what's time consuming is writing related guides...

If I am focused I could publish next release in Sunday evening (in Italy) otherwise for half of next week because I start the courses (I am a teacher...)

**Comment by ldan93** [comment]
Cool ! 
Let me know if I can be of any help for writing the guide. Oh and by the way, would you be interested in me completing the Wiki for the "Unlock 0xE2 MSR" part ? I've done it on several Bios versions, so I definitely feel I can do it :)

**Comment by profzei** [comment]
> would you be interested in me completing the Wiki for the "Unlock 0xE2 MSR" part ?

I'll really appreciate your help!

**Comment by ldan93** [comment]
Hi, please find attached a guide written in Markdown. Feel free to make all the modifications / corrections you wish ! 
[CFG-Guide.zip](https://github.com/profzei/Matebook-X-Pro-2018/files/7149579/CFG-Guide.zip)

**Comment by profzei** [comment]
@ldan93 
Please, be patient! I'm sorry: I'm late in writing the guide, but [I'm writing it](https://github.com/profzei/Matebook-X-Pro-2018/wiki/Enable-BIOS-Secure-Boot-with-OpenCore)! I'm at around 40%... I plan to finish it for the weekend and share it on [Reddit](https://www.reddit.com/r/hackintosh/) as well!

Thank you very for your contribution: I'll update it after publishing my guide!

**Comment by ldan93** [comment]
No problem of course, take all you time, the current release is still very solid 😉
Good luck with the start of the school year !

**Comment by espitgn** [comment]
> Hi, please find attached a guide written in Markdown. Feel free to make all the modifications / corrections you wish !
> [CFG-Guide.zip](https://github.com/profzei/Matebook-X-Pro-2018/files/7149579/CFG-Guide.zip)

Hi! I've followed this guide and It works flawessly in my MBXP (with BIOS version 1.28). I don't detect a big enhancement, but I understand the worth is better global stability, not necessarily better performance...

thks a lot!

**Comment by ldan93** [comment]
> > Hi, please find attached a guide written in Markdown. Feel free to make all the modifications / corrections you wish !
> > [CFG-Guide.zip](https://github.com/profzei/Matebook-X-Pro-2018/files/7149579/CFG-Guide.zip)
> 
> Hi! I've followed this guide and It works flawessly in my MBXP (with BIOS version 1.28). I don't detect a big enhancement, but I understand the worth is better global stability, not necessarily better performance...
> 
> thks a lot!

Thank you for your feedback !! Yeah, this is not supposed to bring very visible change, just a more stable/native approach...

**Comment by profzei** [comment]
@ldan93 Published [guide](https://github.com/profzei/Matebook-X-Pro-2018/wiki/Enable-BIOS-Secure-Boot-with-OpenCore)... I'll finalize next release very soon!

**Comment by profzei** [comment]
@ldan93 Published [new release](https://github.com/profzei/Matebook-X-Pro-2018/releases/tag/v3.0.0)
