### ISSUE TITLE
Press fn key to Show Emoji & Symbols?

### ISSUE THREAD

**Issue by samwzlim** [profzei/Matebook-X-Pro-2018#188]
Not an issue but a question; Are we able to map the Fn key to show emoji & symbols? At the moment, the Fn key is not utilized in macOS.

<img width="668" alt="image" src="https://user-images.githubusercontent.com/74489037/135597025-e780f1f8-e1d4-4e74-a267-f7a5c1c7bc0f.png">

 I've tried to change the option for Press fn key to from 'Do Nothing' to 'Show Emoji & Symbols' but it still doesn't do anything, but on the physical keyboard, I am able to see the light toggling on and off.

**Comment by profzei** [comment]
Honestly, I don't know...
