### ISSUE TITLE
Prohibitory circle after upgrade

### ISSUE THREAD

**Issue by Zephariael** [profzei/Matebook-X-Pro-2018#192]
Hello,

I'm experiencing the prohibitory circle after upgrading to the latest efi. I tried re installing, but the utility only seems to recognize the macos base system partition and not the rest of the SSD, so I can't even reinstall. 

Google-fu is also not helping. My time machine backup also isn't detected. 

Please advice, thanks.

**Comment by Zephariael** [comment]
From EFI ver 2.4.0

**Comment by profzei** [comment]
@Zephariael 
Maybe this could be useful for fixing your issue: [#186](https://github.com/profzei/Matebook-X-Pro-2018/issues/186#issuecomment-946195539)

See also new guide for installing macOS and modifying `config.plist`...

**Comment by profzei** [comment]
@Zephariael 

**Fix seems to be found**: [#186](https://github.com/profzei/Matebook-X-Pro-2018/issues/186#issuecomment-946721892)

I'm waiting for some more tests and then I'll update 3.1.0 release with fixes
