### ISSUE TITLE
Where do I place all the files?

### ISSUE THREAD

**Issue by vblinden** [profzei/Matebook-X-Pro-2018#2]
Hello, 

I have a quick question about where to place the files on the installation USB. I followed the guide of the gnodipac886 repository. Do I need to take the files from gnodipac886 as a basis or can I use this repository as a standalone?

Thanks!

**Comment by profzei** [comment]
If you have Mojave or Catalina already installed with gnodipac886's repository then you could just update properly the various folders present in your EFI install.
If you run Catalina, rename config-catalina.plist in config.plist (and don't use standard config.plist which refers to Mojave which is my main macOS as stated in homepage).
