### ISSUE TITLE
[REQ] Is handoff/universal clipboard working both ways for you?

### ISSUE THREAD

**Issue by samwzlim** [profzei/Matebook-X-Pro-2018#200]
Hi, has anyone here updated to the latest stable release of macOS Monterey 12.0.1? If you have, can you please report whether handoff/universal clipboard works **both ways** (from iOS/iPadOS to hackintosh **AND** hackintosh to iOS/iPadOS)? For me, it only works one way from the very first Monterey beta (from iOS/iPadOS to hackintosh but NOT hackintosh to iOS/iPadOS).

Thanks in advance.

**Comment by meetp13** [comment]
Mine is not working in either direction at the moment
