### ISSUE TITLE
USB-to-Ethernet Hub cannot be detected when I upgrade EFI to v3.1.0

### ISSUE THREAD

**Issue by wswn** [profzei/Matebook-X-Pro-2018#202]
### USB-to-Ethernet Hub cannot be detected when I upgrade EFI to v3.1.0
I have a USB-to-Ethernet hub connected to the right port (type-c) (not Power Source port) by matedock-2. The LAN (labeled as "USB 10/100/1000 LAN" in normal) cannot be detected when I upgrade EFI to v3.1.0. However, the USB ports on the HUB can be recognized, but only usb2.0.
Previous EFI Version: I do not remember which version is used now ...
HUB model: Lenovo USB-C to RJ45 Adapter C506.

### The "USB 10/100/1000 LAN" is recognized as different USB versions.
It is noted that this difference does not affect my daily use, but it does exist.
**When the USB-to-Ethernet Hub is connected to the left type-c port** (close to the 3.5mm earphone jack), "USB 10/100/1000 LAN" works as usb3.0.
<img width="686" alt="image" src="https://user-images.githubusercontent.com/9503473/139582647-0a0ea341-34c5-4e02-8923-ba422a47502d.png">
**When the USB-to-Ethernet Hub is connected to the right type-c port**, "USB 10/100/1000 LAN" works as usb2.0.
<img width="677" alt="image" src="https://user-images.githubusercontent.com/9503473/139582695-fadb427f-d606-49d4-bdcc-d6f34961b4fd.png">

**Comment by profzei** [comment]
@wswn Could you provide your previous working EFI, please?

**Comment by wswn** [comment]
@profzei Sure. The original EFI folder has been compressed and uploaded as the attached file "EFI-Origin". Please check it
[EFI-Origin.zip](https://github.com/profzei/Matebook-X-Pro-2018/files/7454028/EFI-Origin.zip)
.

**Comment by unverbraucht** [comment]
Did you also update to Monterey recently? Monterey has introduced USB problems that sound quite the symptoms you're seeing: https://screenrant.com/macos-monterey-breaking-usb-hubs-user-reports/

**Comment by profzei** [comment]
@wswn 
From a technical point of view there is no difference in USB stuff and support between actual EFI and what you reported: all is unchanged from almost one year!

@unverbraucht Thank you for your report!

Today OpenCore v. 0.7.5 has been released: I'll make very soon a new release for supporting some Bluetooth fixes, but atm nothing else since I'm very busy in real life...

**Comment by wswn** [comment]
@unverbraucht 
Thanks for your advice. It doesn't seem like a problem introduced by the macOS version changing because I keep using Big Sur 11.5.

@profzei 
Thank you, profzei! I re-upgrade EFI to v3.1.0 now and find the hub mentioned above works fine when connected to the left type-c port. But it's still weird that the hub can no longer work as usual (a usb2.0 device as before) when connected to the right port.

I noticed that the USB 3.1 bus disappeared in v3.1.0. Is that related to this problem?
Here are some screenshots:
**When the hub is plugged into the left port.** 
![3451635852649_ pic_hd](https://user-images.githubusercontent.com/9503473/139845025-4d7e33df-aacf-4a73-8f87-5315004d4410.jpg
![3461635852700_ pic](https://user-images.githubusercontent.com/9503473/139845379-5d77479f-70ef-4f1b-b316-c958bbc6e494.jpg)
**When the hub is plugged into the right port.** 
![3481635852771_ pic_hd](https://user-images.githubusercontent.com/9503473/139845613-44e9bb19-3209-4b7f-83f0-5dc1d5846e34.jpg)
![3471635852757_ pic](https://user-images.githubusercontent.com/9503473/139845636-84fb2966-3120-438f-830a-c28fc941c4b2.jpg)

**Comment by wswn** [comment]
@profzei Very thanks for your reply and clarification! I think I get the idea... 

The right type-c port (actually type-A port) supports usb3.0 only if Thunderbolt is enabled.  

I naively think both type-c ports can provide USB3.0 even if Thunderbolt is disabled... But, I'm still confused: Why the USB-Ethernet Hub can no longer work as a USB 2.0 device when plugged into the type-A port? it works fine though it works on USB2.0 protocol in previous EFI.
