### ISSUE TITLE
Apple TV app is opening but video interface not showing up.

### ISSUE THREAD

**Issue by cyberphen** [profzei/Matebook-X-Pro-2018#203]
Hi

Thanx for making our lives a lot easier by providing this amazing guide on porting mac on on Matebook X pro.
Almost everything that is necessary is workng. 

I was trying to open Apple tv app on big sur. But it is not playing any video. It opens up the app but when I play any video it just do nothing. Is there anything we can do to rectify that which will make an already perfect port even better.

Thanx

**Comment by profzei** [comment]
@cyberphen 
Hi, honestly Apple TV is one of the first apps I removed from Dock after a clean install... I never used it nor unlikely I don't even know how it should work... 

Have you find some Hackintosh project which reported a successful use for it? ...possibly with some details about enabling it?
