### ISSUE TITLE
OpenCore cannot boot windows

### ISSUE THREAD

**Issue by BigEmperor26** [profzei/Matebook-X-Pro-2018#206]
Hi there, first of all thanks for you repo, it is amazing.

Then, the problem I'm experiencing is that I cannot boot into Windows 11 through OpenCore. I can normally boot windows without OpenCore, through boot selection by `F12`. 

When I try to boot through OpenCore I get a Blue Screen Of Death that says `ACPI BIOS ERROR`. I think it has something to do with the ACPI patches, but I'm not really sure. I'd love to get OpenCore to boot windows, so I could use NVRAM to switch OS like a native Mac with BootCamp.

I'm using your release `3.2` and my bios is `1.29`

Do you have any suggestion on how to solve ? 

BTW Cheers for the new year ✨

**Comment by unverbraucht** [comment]
Not a solution but just a note: I'm dual-booting through OpenCore with Windows 11 successfully with release 3.2, although it was upgraded from Windows 10 after I already had a working OpenCore setup.

**Comment by BigEmperor26** [comment]
Found the culprit. The patches and SSDT-TB* related to get thunderbolt support on MacOS were causing an issue with them. Disabling them allowed me to boot fine.

**Comment by BigEmperor26** [comment]
I was able to pin down the problem to specifically the hot-patches in OpenCore. 
```
enable TB3: _GPE.NTFY,1,S to XTFY binary patch
```
```
enable TB3: RP9._INI,0,N to XINI binary patch
```
I was wondering if it was possible move these patches to `SSDTs` and adding a `if (_osi ( darwin ))` condition so the patches won't apply to Windows. 

Regardless, thanks for the help ✨ 👍

**Comment by profzei** [comment]
Unfortunately not, a binary patch could only rely on OC's `config.plist` and just as unfortunately binary patches are applied to **ALL OSes** (i.e. there is no `if` statement we could rely on...) since it is an OC's "feature"... (OC developers say so...)
