### ISSUE TITLE
Shutdown button from macOS doesn't work, computer restarts instead

### ISSUE THREAD

**Issue by giulioverazzo** [profzei/Matebook-X-Pro-2018#207]
Hi, first of all thanks for all the work done on this computer, the level of stability achieved it's amazing. Unfortunately, I'm having this issue with my matebook x pro 2018. When I click Shutdown on the apple button menu, the pc restarts instead of shut itself down. I'm on macOS Big Sur 11.6 and BIOS version 1.30.

I found this guide online https://dortania.github.io/OpenCore-Post-Install/usb/misc/shutdown.html and I tried to follow it but I don't know how to check the DSDT and the USB Controlled mentioned. I think I didn't have the right knowledge to understand what I'm doing.

If this guide is the right way to fix the problem, can you please help me to follow it? Do you think it can be something else instead?

Thanks

**Comment by profzei** [comment]
@giulioverazzo Hi, have you modified any SSDTs in `EFI/OC/ACPI` folder? What you described should not happen... i.e. current unmodified EFI is not affected by such issue since the standard patch you mentioned from Dortania's guide is present in `SSDT-PTSWAK.aml`

**Comment by giulioverazzo** [comment]
no, I did not modified any SSDT in EFI/OC/ACPI folder. The only thing I changed from your latest EFI release v.3.2.0 is that I replaced AirportItlwm with the latest alpha v2.2.0 version

**Comment by profzei** [comment]
Honestly, if `EFI/OC/ACPI` is untouched then, in my opinion, your issue could only be due by some software you installed...

**Comment by giulioverazzo** [comment]
The strange thing is that I noticed it happens on Windows too! The only thing that came in my mind can be that I tried to update the BIOS to 1.37 with no luck a week or so, the computer just restarted without updating anything. Could it be something left from the BIOS update process? How can I check it?

**Comment by giulioverazzo** [comment]
Problem solved after updating the BIOS from windows. Thank you for time!
