### ISSUE TITLE
No an issue, but a request 

### ISSUE THREAD

**Issue by yamyoume** [profzei/Matebook-X-Pro-2018#216]
Hi, I understand your frustration with other people copying your work, and I respect your decision to stop the releases.
I'm trying to sell my matebook-x-pro, and as I was trying to reset it (delete my personal data) I think I messed it up, and now I'm trying to fix it, but All I have is an old flash drive with Catalina, I was wondering if you could privately share the latest release please. 
I can be reached on this email "yamyoume@hotmail.com", thank you

**Comment by tlefko** [comment]
> Hi, I understand your frustration with other people copying your work, and I respect your decision to stop the releases. I'm trying to sell my matebook-x-pro, and as I was trying to reset it (delete my personal data) I think I messed it up, and now I'm trying to fix it, but All I have is an old flash drive with Catalina, I was wondering if you could privately share the latest release please. I can be reached on this email "[yamyoume@hotmail.com](mailto:yamyoume@hotmail.com)", thank you

just use mine. wipe the data, if you still have this issue.
