### ISSUE TITLE
Request for releases

### ISSUE THREAD

**Issue by sagar-chandarana** [profzei/Matebook-X-Pro-2018#217]
Hi Profzei,

I have used this project for past couple years, and made a couple comments on a few issues. I have never contributed much to this project other than thanking you a few times here and there. I really appreciate the hard work and willingness to share.

However, I do find a need to express my personal opinion on your decision to pull the release out. While I do think it is fair to share the anger, it is not fair for the people like me, who have experienced and cheered the fruits of your contributions so far, to suffer as a consequence of a third party. I am concerned of the un-lived potential of this project, and your contributions for it, especially if you keep working on them for your own usage. I wonder if the pain of not sharing your work might be the same or even more than being stolen of your work.

It's been awhile now since the incident and I would like to leave this issue as request to you to reboot this project and let go of any past situations that stopped you from sharing the fruits of your hardwork. I'd happily pay a contribution!

- with gratitude and for the goodwill of the community and their lovely devices.

**Comment by qosmio** [comment]
I whole heartedly agree with @sagar-chandarana. I am incredibly grateful for all the work you have contributed to this project, and have learned a lot from your write ups as well. I would be more than willing to contribute in donating if it would mean you would share your continued work (if you have been). 

With the recent updates, many of us have hit unforeseen roadblocks, and were wondering if you have too. I’m sure everyone would agree, your work was invaluable in helping get the most bang for our buck with these devices. And before Apple completely switches its attention to their ARM platform, we’d love to extend (with your help) this project as much as possible. 

Again, please reconsider.

**Comment by Charly1000** [comment]
> I whole heartedly agree with @sagar-chandarana. I am incredibly grateful for all the work you have contributed to this project, and have learned a lot from your write ups as well. I would be more than willing to contribute in donating if it would mean you would share your continued work (if you have been).
> 
> With the recent updates, many of us have hit unforeseen roadblocks, and were wondering if you have too. I’m sure everyone would agree, your work was invaluable in helping get the most bang for our buck with these devices. And before Apple completely switches its attention to their ARM platform, we’d love to extend (with your help) this project as much as possible.
> 
> Again, please reconsider.

I agree :)

**Comment by tlefko** [comment]
@sagar-chandarana @Charly1000 @qosmio regardless of whatever your opinion is on this matter.

If you do need help with the machines feel free to contact me or look over the docs here. This is updated for macOS ventura.

https://github.com/tlefko/Matebook-X-Pro-2018-Ventura

**Comment by gnodipac886** [comment]
Wow, I am late to the party, but isn't this a bit hypocritical? Your repo started by taking inspiration from some of my original clover work, yet you have never made a single pull request to my repo... I don't want to say too much, but wow...
@tlefko thank you for your continued work on this. I have since migrated to other platforms, but very happy to see someone continuing this hard work!

```I'm sorry but I decided to remove all my releases: in this way I wanted to make it easier for people who have already copied what is on this site stating they made 'significant and unquestionable original changes' (instead of collaborating by suggesting pull requests)!```

**Comment by tlefko** [comment]
@gnodipac886 I appreciate you my friend, I looked at much of your clover work too! let me know if you ever have any ideas for the project

--tlefko

**Comment by sagar-chandarana** [comment]
@profzei Hope you are well! What incentives/contributions are you open to from the community so that we can figure out a way to make everyone happy? Personally I would love to use my laptop with full macOS support from your contributions. I am also open to a private repo/release access to paid and authenticated individuals in order to avoid any future mishaps. The hopeful outcome I imagine is that we can get the final product of your work and get more life out of our devices. Thank you for your efforts.

**Comment by JasonDwan** [comment]
@profzei Hey,Much appropriated for your great work which makes me to utilize my matebook supporting Mac with a super smooth experience, I totally understand your choice to pull back your releases , but I would like to ask for a personal favor for a stable release supporting the latest Mac, as I am still using the Big Sur which doesn't support the app store anymore, I would like to donate on this project , Please let me know, my email address:  fantasylover@126.com
Again, thanks!
