### ISSUE TITLE
Kernel Panic when asleep 

### ISSUE THREAD

**Issue by auschanh** [profzei/Matebook-X-Pro-2018#22]
After the laptop is put to sleep for a while, kernel panics happen and the system reboots. Not sure if its related to having the laptop in clamshell mode, with 2 external displays attached. The laptop will sleep for a while, but sometimes the panics will randomly happen. 

On Catalina 10.15.2

![Screen Shot 2020-06-20 at 9 56 48 AM](https://user-images.githubusercontent.com/22928204/85203605-e43d6700-b2dc-11ea-84b0-9560fdabb9a0.png)

**Comment by PLTorrent** [comment]
Setting on bios „disable other wakeup sources” to disabled should help

**Comment by auschanh** [comment]
> Setting on bios „disable other wakeup sources” to disabled should help

Hey I tried this out and now I have a different kind of error report. I also updated to Catalina 10.15.5.

Something to do with the thunderbolt? I'm not very knowledgeable on Hackintosh, so not sure what to do from here

<img width="997" alt="Screen Shot 2020-06-23 at 6 29 35 PM" src="https://user-images.githubusercontent.com/22928204/85472443-d8250400-b57f-11ea-9849-20bfc6a4907c.png">

**Comment by profzei** [comment]
Hi @auschanh @PLTorrent , try [my latest release v. 1.2.0](https://github.com/profzei/Matebook-X-Pro-2018/releases): the issue should be fixed!
Please, don't set in BIOS the option "Other wakeup sources" as disabled otherwise waking up the machine opening its lid should not be possible!
Let me know your feedback!

**Comment by profzei** [comment]
I think this issue can be considered, atm, solved by [this feedback](https://github.com/profzei/Matebook-X-Pro-2018/issues/21).
