### ISSUE TITLE
Bluescreen when booting to windows!

### ISSUE THREAD

**Issue by barbarou** [profzei/Matebook-X-Pro-2018#25]
When I boot using OpenCore to windows 10 I got bluescreen with stopcode ACPI_BIOS_ERROR.

Mac osx Catalina works perfect, I think its DSDT problem and windows doesn't like the DSDT patch! any help to fix booting to windows using OpenCore 0.5.9?

**Comment by profzei** [comment]
Can I ask you which version of Windows 10 you have? Maybe 2004?

However I come back home tonight... A possible fix is to use refind as bootloader... I think it’s quite simple... I’ll submit a fix for tomorrow (other users and myself don’t have issues) so that we could have a “nice” GUI 😁

**Comment by barbarou** [comment]
I have 1909

I will press F12 at boot for now than setting up refind bcoz i really like OpenCore.
I hope there is a solution that I can use OpenCore for both mac and win, I need “nice” GUI too :'(

Waiting for your fix 💯

**Comment by auschanh** [comment]
Got the same issue. Did some research and added the path to bootmgfw.efi to blessoverride in config.plist and still no luck 🙁

**Comment by barbarou** [comment]
We hope that profzei can find a fix for that soon, 🙏

**Comment by profzei** [comment]
@auschanh @barbarou It should be fixed using **rEFInd** as boot loader: see [my guide](https://github.com/profzei/Matebook-X-Pro-2018/wiki/Converting-from-Clover-to-OpenCore)

**Comment by barbarou** [comment]
> @auschanh @barbarou It should be fixed using **rEFInd** as boot loader: see [my guide](https://github.com/profzei/Matebook-X-Pro-2018/wiki/Converting-from-Clover-to-OpenCore)

Ok, I'll check now, thank you so much for your hard work 🤟
