### ISSUE TITLE
Have Intel Auto Kext Loader load kext from directory that script is in

### ISSUE THREAD

**Issue by alexkim205** [profzei/Matebook-X-Pro-2018#26]
I really appreciate the work that you're doing here! Keep up the good work.

Problem:

- I would like to place the AppleIntelWifi folder that holds the kext and IntelKextAutoLoader in a folder other than ~/Desktop. Perhaps the script can be updated to `cd` directly into the directory that the script is located in, so that `cd Desktop/AppleIntelWifi` isn't hardcoded.

Suggestion:

In `IntelKextAutoLoader.sh`

```
#!/usr/bin/env sh
# Auto Loader for AppleIntelWiFi.kext
#

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

sudo chmod -R 755 *.kext

sudo chown -R root:wheel *.kext

sudo kextload AppleIntelWiFi.kext

```

It's a small suggestion, but would be nice for users who don't want a folder hanging around on their desktop. The Network README will also need to be updated.

**Comment by alexkim205** [comment]
I'd also be happy to make a PR if this is something you'd like to move forward with.

**Comment by profzei** [comment]
@alexkim205 Great idea and thank you very much for your suggestion! Since it's my first repo please make a PR but then explain me what I have to do... how do I synchronise my local folder to web repo (vice versa is done with command `git push -u origin master`)

**Comment by R-Teer** [comment]
I just copied the text directly from the IntelKextAutoLoader.sh and adjusted it using textedit. Save the file as a .command extension. I have all my home directories pointed at a separate partition allowing me to share desktop, documents, downloads etc between windows and mac with zero effort
