### ISSUE TITLE
Trackpad not working after waking from sleep after updating to OpenCore build

### ISSUE THREAD

**Issue by Talal916** [profzei/Matebook-X-Pro-2018#27]
Will try to switch to different version of Voodoo kexts to see if that resolves the issue

**Comment by Talal916** [comment]
I should clarify that it does not work on all fresh boots either. Having trouble reproducing issue on demand.

**Comment by voibit** [comment]
Try updating VoodooI2C and VoodooI2CHID to version 2.4.3. Needs more testing, but i am having good luck so far.

**Comment by BigEmperor26** [comment]
copy the OC and BOOT from last release( as long as you have the same hardware as OP). Fixed the problem for me.

**Comment by profzei** [comment]
Hi @Talal916 and @voibit , try [my latest release v. 1.2.0](https://github.com/profzei/Matebook-X-Pro-2018/releases): not only the issue should be fixed, but gestures should be smoother!
Let me know your feedback!

**Comment by profzei** [comment]
I think this issue can be considered, atm, solved by [this feedback](https://github.com/profzei/Matebook-X-Pro-2018/issues/21).
