### ISSUE TITLE
Brightness on lowest level turns screen backlight off

### ISSUE THREAD

**Issue by PLTorrent** [profzei/Matebook-X-Pro-2018#28]
When brightness is set to the lowest possible level the screen backlight is turned completely off. 

Expected behaviour: The lowest setting should set minimal brightness but not turn the backlight off.

Steps to reproduce: Manually set brightness to lowest possible, the screen backlight will turn off.

HW: MXP 2018 (MACH-W19), Intel Core i5-8250U, no dGPU, 8GB RAM, Liteon-ssd, Clover bootloader.

**Comment by barbarou** [comment]
Same here and I think all of us have the same thing. 

But my problem is the brightness on lowest level is very high and on max level its like a stadium light haha I do not know if it is a problem or should it be like this!

**Comment by yichebb** [comment]
That is the expected behaviour on MacBooks, where the lowest brightness setting completely turns off the backlight (but not the screen), so it doesn't seem like an issue here.

**Comment by R-Teer** [comment]
I am having the same issue. Back-light is basically at full brightness at about pip2 on the brightness meter.  From there til full brightness there is virtually no change

**Comment by benbender** [comment]
@R-Teer You most likely have an issue with your SSDT-PNLF (wrong UID for another Framebuffer-generation?).

**Comment by R-Teer** [comment]
> @R-Teer You most likely have an issue with your SSDT-PNLF (wrong UID for another Framebuffer-generation?).

Strange ill have a look at this tonight, everything was working great pre opencore conversion in regards to the brightness levels. 

I'll see what I can do to try and fix

**Comment by profzei** [comment]
@R-Teer @benbender @barbarou @yichebb Hi all, I fixed SSDT-PNLF.aml; I’ll make my first release for OC in a few hours... I’m writing a guide for using properly rEFInd as GUI bootloader and “fixing” ACPI_ERROR for dual booting Windows

**Comment by profzei** [comment]
@benbender @yichebb @R-Teer @barbarou See [my first release](https://github.com/profzei/Matebook-X-Pro-2018/releases)

**Comment by barbarou** [comment]
> @R-Teer @benbender @barbarou @yichebb Hi all, I fixed SSDT-PNLF.aml; I’ll make my first release for OC in a few hours... I’m writing a guide for using properly rEFInd as GUI bootloader and “fixing” ACPI_ERROR for dual booting Windows

Everything works as it should 💯 . Brightness levels works now as it does in windows. Thank you profzei again 😍 . 

But my question now is: If I use rEFInd, could it be an issue like in Clover when windows updated, which caused that windows always rewrite its bootmgfw.efi again and you have to rename it again to bootmgfw-orig every time to get dual boot again? or does rEFInd not have the same issue?

**Comment by profzei** [comment]
> If I use rEFInd, could it be an issue like in Clover when windows updated, which caused that windows always rewrite its bootmgfw.efi again and you have to rename it again to bootmgfw-orig every time to get dual boot again? 

@barbarou Unfortunately **yes**. The only safe way would be to use the "BIOS Boot Option Mode" described in [the guide](https://github.com/profzei/Matebook-X-Pro-2018/wiki/Converting-from-Clover-to-OpenCore#dualbooting-with-windows-bios-approach) where the two OS are virtually independent: in fact, in this mode, it is not necessary to rename `bootmgfw.efi` as `bootmgfw-orig.efi`

**Comment by R-Teer** [comment]
> @R-Teer @benbender @barbarou @yichebb Hi all, I fixed SSDT-PNLF.aml; I’ll make my first release for OC in a few hours... I’m writing a guide for using properly rEFInd as GUI bootloader and “fixing” ACPI_ERROR for dual booting Windows

excellent work man, working beautifully.  Just set up Refind loader and seems to be working well also, but will probably just stick to bios booting for now. 

Has any one had any luck in booting windows directly from opencore? I'm looking at the NDK opencore fork at  https://github.com/n-d-k/OpenCorePkg and it seems we can prevent opencore from patching additional operating systems on load

**Comment by profzei** [comment]
@R-Teer You are right! [n-d-k OpenCore fork](https://github.com/n-d-k/OpenCorePkg) seems to prevent OpenCore from patching other OS on load... but atm the project seems stalled: there isn't any update from 4th May, no answer in issues' section and, moreover, it seems that [OpenCore 0.5.9 release breaks N-D-K Build ](https://github.com/n-d-k/OpenCorePkg/issues/33)... So for now I prefer to concentrate to perfect our build with vanilla OpenCore.
