### ISSUE TITLE
Screen glitch after sleep

### ISSUE THREAD

**Issue by therealmrsymba** [profzei/Matebook-X-Pro-2018#3]
![image](https://user-images.githubusercontent.com/64728541/81521684-c99aca00-92fc-11ea-8642-31f533b712e8.jpeg)

Anyone else run into this issue? Not sure if I missed a fix for it in the repo.

**Comment by profzei** [comment]
I just updated a new config.plist (named Catalina-config.plist) for Catalina where this issue should be fixed... at least at software level.
Please see https://github.com/profzei/Matebook-X-Pro-2018/blob/master/Changelog.md
I committed many changes so please properly update.

I rewrote all Intel(R) UHD 620 Graphics card configuration... so some fixes could be needed in next days: for example a "better support" for sleep in clamshell configuration...

**Comment by therealmrsymba** [comment]
Sounds good! I’ll check it out, great work and thanks for the update.

**Comment by therealmrsymba** [comment]
I am a newbie and I was curious to know if I am only supposed to update the Clover folder or do I do anything with CPUFriend, Graphics, SSDT and Graphics folders

**Comment by therealmrsymba** [comment]
I actually done the answer. Thanks for your help!
