### ISSUE TITLE
Kernel panic while in sleep. Thunderbolt power on failed

### ISSUE THREAD

**Issue by Talal916** [profzei/Matebook-X-Pro-2018#32]
panic(cpu 2 caller 0xffffff7f87c5f399): "UPSB(MacBookPro14,1): thunderbolt power on failed 0xffffffff\n"@/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/IOPCIFamily/IOPCIFamily-370.100.21/IOPCIBridge.cpp:1398
Backtrace (CPU 2), Frame : Return Address
0xffffff82079fba60 : 0xffffff800711f5cd 
0xffffff82079fbab0 : 0xffffff8007258b05 
0xffffff82079fbaf0 : 0xffffff800724a68e 
0xffffff82079fbb40 : 0xffffff80070c5a40 
0xffffff82079fbb60 : 0xffffff800711ec97 
0xffffff82079fbc60 : 0xffffff800711f087 
0xffffff82079fbcb0 : 0xffffff80078c27cc 
0xffffff82079fbd20 : 0xffffff7f87c5f399 
0xffffff82079fbd40 : 0xffffff7f87c46fcf 
0xffffff82079fbda0 : 0xffffff7f87c4750e 
0xffffff82079fbdc0 : 0xffffff7f87c456f6 
0xffffff82079fbe10 : 0xffffff7f87c5001f 
0xffffff82079fbe30 : 0xffffff80078148a4 
0xffffff82079fbea0 : 0xffffff80078146aa 
0xffffff82079fbec0 : 0xffffff8007161565 
0xffffff82079fbf40 : 0xffffff8007161091 
0xffffff82079fbfa0 : 0xffffff80070c513e 
      Kernel Extensions in backtrace:
         com.apple.iokit.IOPCIFamily(2.9)[BE052F4D-9B80-3FCD-B36D-BACB7DEE0DF2]@0xffffff7f87c3e000->0xffffff7f87c76fff

BSD process name corresponding to current thread: kernel_task
Boot args: -cdfon -igfxmlr darkwake=1 gfxrst=1

Mac OS version:
19F101

**Comment by yichebb** [comment]
Similar issue with kernel panics while in sleep here with [release 1.0](https://github.com/profzei/Matebook-X-Pro-2018/releases/tag/v1.0.0) with rEFInd, but it seems that this has also been affecting quite a few genuine macs recently on Catalina. Resetting NVRAM and SMC is said to able to resolve the issue (on genuine macs), so it might be an issue with that?

> panic(cpu 0 caller 0xffffff801769167c): Sleep transition timed out after 180 seconds while calling power state change callbacks. Suspected bundle: com.apple.iokit.IOUSBHostFamily. Thread 0x34a96.
Failure code:: 0x00000008 00000014
>
> Backtracing specified thread
Backtrace (CPU 0), Frame : Return Address
0xffffff82183f3900 : 0xffffff80170458f8 
0xffffff820978bc40 : 0xffffff8016f413f1 
0xffffff820978bcb0 : 0xffffff8016f3fc2f 
0xffffff820978bd00 : 0xffffff80170429f9 
0xffffff820978bd40 : 0xffffff801704225b 
0xffffff820978bd70 : 0xffffff801762cae8 
0xffffff820978bda0 : 0xffffff801762f9f9 
0xffffff820978be00 : 0xffffff8017614d8a 
0xffffff820978bea0 : 0xffffff80176146b4 
0xffffff820978bec0 : 0xffffff8016f61565 
0xffffff820978bf40 : 0xffffff8016f61091 
0xffffff820978bfa0 : 0xffffff8016ec513e 
>
> BSD process name corresponding to current thread: kernel_task
Boot args: -cdfon -igfxmlr darkwake=1 gfxrst=1
>
> Mac OS version:
19F2200

**Comment by Talal916** [comment]
@yichebb I've opened a new issue since I've just encountered the same kernel panic as yours. #36 
Have you found a solution yet?

**Comment by yichebb** [comment]
@Talal916 Not yet, and I don't think I'll be of any help with troubleshooting since I don't have very extensive knowledge.

**Comment by profzei** [comment]
Hi @Talal916 and @yichebb , try [my latest release v. 1.2.0](https://github.com/profzei/Matebook-X-Pro-2018/releases): the issue should be fixed!
Let me know your feedback!

**Comment by profzei** [comment]
I think this issue can be considered, atm, solved by [this feedback](https://github.com/profzei/Matebook-X-Pro-2018/issues/21).
