### ISSUE TITLE
Processor speed limit. Not allowing to boost

### ISSUE THREAD

**Issue by jmalfara** [profzei/Matebook-X-Pro-2018#33]
Has anyone noticed the processor not hitting boost frequencies? 

<img width="1109" alt="Screen Shot 2020-07-06 at 10 57 52 PM" src="https://user-images.githubusercontent.com/9324299/86845336-55b83c00-c077-11ea-97a5-1f3c4a22e1d4.png">

Im assuming this is something to do with the "Balance" power management. Does anyone know how I could go about increasing the power limits? Im fine with the cpu hitting 80 degrees under load

**Comment by kxlv2000** [comment]
Hi, You may check [here ](https://github.com/profzei/Matebook-X-Pro-2018/issues/9) as an reference, It seems that you have reached the power limit wall, too, I used voltageshift.kext to unlock the TDP and here is the result.

![](https://user-images.githubusercontent.com/49295281/83387126-c63bbf80-a41e-11ea-8590-afa62bdf4f49.png)

**Comment by jmalfara** [comment]
Ah yes related to another issue. Ill close this one and reply back in the other. Thank you!
