### ISSUE TITLE
Disable the touch screen

### ISSUE THREAD

**Issue by DanteSung** [profzei/Matebook-X-Pro-2018#34]
Hey, thanks for all the efforts. I have a question about how to disable the touch screen. My screen has a crack on it and some random clicks may happen if I switch it on.

So how can I turn it off? Which kext file should I delete?

Thanks!

**Comment by profzei** [comment]
Hi, atm I’m on holidays... for disabling touchscreen you need a SSDT that I wrote before leaving but I didn’t update repo 😅... with improved touchpad behavior... just some patience, please!

**Comment by DanteSung** [comment]
thanks for the quick reply! I'll wait for the update!

**Comment by profzei** [comment]
Hi @DanteSung, please check [latest release (v1.1.0)](https://github.com/profzei/Matebook-X-Pro-2018/releases): touchscreen should be disabled with some other fixes!
Let me know if all is ok!

**Comment by DanteSung** [comment]
Thanks for all the efforts!
