### ISSUE TITLE
Trackpad not working after updated to 10.15.6 (solved)

### ISSUE THREAD

**Issue by barbarou** [profzei/Matebook-X-Pro-2018#35]
Trackpad not working after updated to 10.15.6

**Edit: Working now after updating VoodooI2CHID.kext and VoodooI2C.kext to latest versions.**

**Edit 2: Does not work after sleep again and fixed it by changing wakedelay to 10 in VoodooPS2Trackpad.kext located in plugins file in VoodooPS2Controller.kext**

**Comment by profzei** [comment]
Great!👍🏻

**Comment by barbarou** [comment]
> Great!👍🏻

But after waking up from sleep, it does not work: /
