### ISSUE TITLE
Re-enable touch screen functions

### ISSUE THREAD

**Issue by R-Teer** [profzei/Matebook-X-Pro-2018#37]
Hi Prof,  great work as always.  I have just updated to the new opencore setup and have successfully upgraded to 10.15. 6

Is there a way to reenable the touch screen whist keeping the track pad improvements? The track pad is working much better with multitouch but I use the touchscreen frequently in applications such as logic and other VST softwares for music production and it would be great to have the option to use it again

**Comment by profzei** [comment]
Hi @R-Teer , try the TPXX.aml attached file: I re-enabled touchscreen mode with GPI0 pinning mode -> so it should work better! You just need to replace the old one in OC/ACPI folder.
Let me know your feedback please!

N.B. I disabled touchscreen to satisfy [this request](https://github.com/profzei/Matebook-X-Pro-2018/issues/34): I'm sorry for the late reply!
[SSDT-TPXX.aml.zip](https://github.com/profzei/Matebook-X-Pro-2018/files/4994798/SSDT-TPXX.aml.zip)

**Comment by R-Teer** [comment]
![thumbsup](https://user-images.githubusercontent.com/46908533/89511068-b307f000-d7d1-11ea-8ae6-2b2a787c5c6e.gif)

Works fantastic man! Much appreciated!

**Comment by LavenderMP** [comment]
@profzei  Hi prof greate job for keeping this repo so useful
I'm a bit of newbie here may i ask where does SSDT file does? how to use it?
many thanks

**Comment by profzei** [comment]
An SSDT file is only an hot patch applied to original `DSDT.aml` for our machine... If you are using this repo, you only need to put it in your `/EFI/OC/ACPI` folder and active it in your `/EFI/OC/config.plist`

A very good starting point is the [Dortania Team Guide](https://dortania.github.io/OpenCore-Install-Guide/)

**Comment by LavenderMP** [comment]
@profzei Thanks man for a clear answer, I was trying to use SSDT-TPXX.aml by enable SSDT-TPXX-NO.aml while still enable SSDT-TPXX.aml and the result is trackpad and screen did not response.
Also I used a different way is to delete SSDT-TPXX.aml and rename SSDT-TPXX-NO to SSDT-TPXX also trackpad and screen were not responsing any ideals how to fix it?
Thanks in advance, and so sorry my english is not good

**Comment by profzei** [comment]
@LavenderMP Also my English is not good...
Try the following:
[SSDT-TPXX.aml.zip](https://github.com/profzei/Matebook-X-Pro-2018/files/5387817/SSDT-TPXX.aml.zip)
Put it in EFI/OC/ACPI folder and replace the existing file with the same name
