### ISSUE TITLE
Updating to 10.15.6

### ISSUE THREAD

**Issue by AshleyMiller9696** [profzei/Matebook-X-Pro-2018#38]
After the progress bar I get this message in the updater

Unable to install MacOs on the computer
An error occurred while generating the kernel cache
Then I have to do reboot

// using opencore
10.15.5 supplemental update

**Comment by profzei** [comment]
I’ll update my machine probably in a few hours...

**Comment by AshleyMiller9696** [comment]
used an offline installer and updated via usb stick

// hopefully yours worked via in system update

**Comment by AshleyMiller9696** [comment]
Same problem with the new Update

How do you guys update?

I load the update in MacOS the settings menu & click restart
in opencore I choose Update MacOs (external) (my MacOS Partition is completely on an external USB Drive)
-> After the Update process it gives me the error unable to generate kernel-cache

**Comment by profzei** [comment]
@AshleyMiller9696 As you said... It's quite weird since I updated my _dev version_ in external disk without any issue using OpenCore boot or rEFInd one
