### ISSUE TITLE
thunderbolt / egpu is not recognized

### ISSUE THREAD

**Issue by gitty8** [profzei/Matebook-X-Pro-2018#40]
I also tried the thunderbolt driver from the repo of the x1
https://github.com/Colton-Ko/macOS-ThinkPad-X1C6/blob/opencore/EFI/OC/ACPI/SSDT-TB3.aml

The SSDT-TB3HP.aml contained in this repo, in OC does not seem to work either.
Which files can I provide to get the egpu running?

![image](https://user-images.githubusercontent.com/19901796/89732796-7518ff00-da51-11ea-943b-5ffae5dd90fa.png)

**Comment by wiregen** [comment]
I tried plugging my matebook into my Mantiz EGPU with a Vega FE and it would not detect also. It would charge my Matebook but nothing would be detected system info.

However, I plugged in my External Samsung X5 NVME SSD and it works 100%.
