### ISSUE TITLE
Battery percentage not working on Catalina 10.15.6

### ISSUE THREAD

**Issue by chrissbg** [profzei/Matebook-X-Pro-2018#41]
Hi, I first tried the Clover version of your repo where the brightness control buttons were not working, then I switched to the OpenCore version, cleaned extension cache and nvram and used the cleaning sh file for Clover.

Brightness keys are working now but the battery always shows 100% and if connected to AC it always shows charging even if it is fully charged. Matebook X Pro 2018 i7 16GB RAM.

Did anyone else encounter this problem?
I am on OpenCore 0.6.0 and used the release 1.3.0 version of your repo.

**Comment by profzei** [comment]
Hi @chrissbg what you reported is very "strange": battery indicator should work flawlessly on each macOS release... I'm using now 10.15.6 without any issue

**Comment by chrissbg** [comment]
Thanks for your reply @profzei. I did not have this issue with the clover version of your repo and also the clover version of @gnodipac886 worked regarding the battery indicator. I just switched to the OpenCore version because I had some other issues, like the non working brightness keys.
I will try to update to your newest release 1.4.0 tomorrow and see if it resolves the battery indicator issue.

**Comment by jmalfara** [comment]
@chrissbg Yup i have this problem as well. Im using the 1.4.0 OC setup. Iv been having this problem on/off for awhile but a restart usually fixes it

**Comment by profzei** [comment]
@jmalfara @chrissbg : what are your BIOS revision?

**Comment by chrissbg** [comment]
@jmalfara @profzei I updated to revision 1.4.0 OC, did not fix the problem but I can confirm that a restart fixes the problem. Sometimes I need a few restarts.
@profzei BIOS revision 1.28

**Comment by jmalfara** [comment]
@profzei @chrissbg My bad forgot about this comment.
BIOS: revision 1.28
