### ISSUE TITLE
Is the OC method for Big Sur valid for 2019 MBXPro Version?

### ISSUE THREAD

**Issue by Hernanduno** [profzei/Matebook-X-Pro-2018#44]
Hi!

I was able to successfully install Catalina on my MBXPro 2019 i7 using your amazing  guide here https://github.com/profzei/Matebook-X-Pro-2018/wiki/Upgrade-to-macOS-Big-Sur but using the clover folder from the forked repo you did from laozhiang using the CLOVER method, but I'm facing ramdom kernel panic related with iGPU so now I'm wondering if it is possible to reinstall Catallina with OC proccess in order to fix it or at least have a better OS installation not prone to mess up on OS updates, since I read some drivers from Clover are not compatible with OC I'm posting this here due to your repo is the most active and complete on this days. 

Thanks for all your Work.

Regards

**Comment by profzei** [comment]
Hi @Hernanduno : the installation method is always the same! I'm trying to help also another Reddit user (u/CopPops) for 2019 MBXPro Version... try for installation the following:
[EFI_INSTALL_MBXP_2019.zip](https://github.com/profzei/Matebook-X-Pro-2018/files/5122987/EFI_INSTALL_MBXP_2019.zip)

**Comment by JustCarousell** [comment]
CopPops here, so I've tried using the new EFI folder but it still could not work for me maybe see what's @Hernanduno result is using the new EFI folder. I have attach a file which shows the data on my latest run that I did where I'm not sure if this will help to figure out what might have went wrong. 

[opencore-2020-08-25-105722.txt](https://github.com/profzei/Matebook-X-Pro-2018/files/5123357/opencore-2020-08-25-105722.txt)

**Comment by Hernanduno** [comment]
Thanks a lot man!
I will give it a try today, I will be posting my results ASAP.

Regards

**Comment by hudsonpaul** [comment]
I'll chime in here. Just installed using that efi on my 2019 i5 8250, 256 toshiba ssd unit. I could not boot in with clover, but I got in with this at least. 

No trackpad k/b or wifi, thats just of the basics I've looked at but I'm sure this query being for Big sur and the fact that I installed 10.15.5 catilina could be for that. Any ideas regarding wifi and kb? I have the same card listed as in the original post.

**Comment by JustCarousell** [comment]
@hudp16 I think we are looking at the option of OC instead of Clover and with OC things might be better to fix

**Comment by hudp16** [comment]
> @hudp16 I think we are looking at the option of OC instead of Clover and with OC things might be better to fix

Yes agree, OC was much smoother, even without a trackpad currently.

**Comment by Hernanduno** [comment]
Hi guys!

I tried use the new EFI folder, but it got stuck on a loop on this process :c y tried with Catalina and BS but I was unable to reach the installation assistant, also my OC.txt it's the same as @hudp16 so I guess I will keep reading even more an trying to get the correct files n.n
![Error1](https://user-images.githubusercontent.com/18127237/91346355-57180200-e7a6-11ea-809b-20dd5dba5907.jpeg)
![Erro2](https://user-images.githubusercontent.com/18127237/91346361-57b09880-e7a6-11ea-9ce6-b915e41f2b2c.jpeg)

**Comment by hudp16** [comment]
I in no way know what I am doing, nor do I know what that means but how did you make your installer? Reformat your disks using your original clover and then try again fresh with OC, resetting nvram. That is the steps I followed from my not working clover.

**Comment by Hernanduno** [comment]
This are the steps I followed on clover method: 
Create a booteable usb using a VM with Mojave using the guide Profzeir posted for BS
mounted the USB EFI partion with clover configurator pro
Paste the EFI folder from laozhiang repo
I redo this process since OC method not worked for me , I guess it will be easiest to stay on Catalina and fix the kernel panic issues i faced before and wait for upgraded guides for 2019 version (':

On this new try with Clover the trackpads stop working and I don't know why since I replicated the same steps as my previous installation 😅

**Comment by hudp16** [comment]
Good question, wish my trackpad worked on OC as well.

**Comment by profzei** [comment]
@JustCarousell : from your log-file I can't understand if the installation stopped at the message `34:776 00:038 AAPL: [EB|#LOG:EXITBS:START] 2020-08-25T10:57:56` or if it continued the process changing screen ...

"Changing screen" is a crucial point in "OC" installation...

**Comment by Hernanduno** [comment]
@hudp16  try to install one by one the newest  knext from voodoo2 I tried this for my problem on clover and now trackpad is working again.

**Comment by hudp16** [comment]
@Hernanduno do you have a link? I thought I did try the newest but maybe not.

**Comment by Hernanduno** [comment]
@hudp16  try using the kext updater barbarou posted on this issue thread from gnodipac repo I just used the app to download all the newest versions from my knexts, created a backup file from my current EFi fonder and then reemplace the knexts with the ones that app downloaded, the restarted and all was ok (:

**Comment by hudp16** [comment]
All up to date on kexts and still unfortunately not.

**Comment by JustCarousell** [comment]
> @JustCarousell : from your log-file I can't understand if the installation stopped at the message `34:776 00:038 AAPL: [EB|#LOG:EXITBS:START] 2020-08-25T10:57:56` or if it continued the process changing screen ...
> 
> "Changing screen" is a crucial point in "OC" installation...

@profzei I'll maybe send in another few of the log file when I had the time to see if it helps to figure that out

**Comment by Hernanduno** [comment]
Hi @hudp16  you could check this https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/troubleshooting.html#stuck-on-eb-log-exitbs-start 
Right now I'm working on create my own files based on my machine specs and using the guide from Dortania I'm learning a lot on the process, for your problem with the trackpad there is also a guide there to fix it based on your machine.
Hope this helps

**Comment by hudp16** [comment]
Appears voodooinput comes before ps2 and ic. I am just using what profzei provided, and given that everything else works it is strange the trackpad does not.

**Comment by JustCarousell** [comment]
![Image2](https://user-images.githubusercontent.com/66050990/91735574-102f6f80-ebdf-11ea-962b-ce7240ca3da0.jpeg)
![Image1](https://user-images.githubusercontent.com/66050990/91735606-1b829b00-ebdf-11ea-8d6d-f7af3d891d9f.jpeg)

@profzei here are some pictures and log file.
[opencore-2020-08-31-145410.txt](https://github.com/profzei/Matebook-X-Pro-2018/files/5151090/opencore-2020-08-31-145410.txt)
[opencore-2020-08-31-145934.txt](https://github.com/profzei/Matebook-X-Pro-2018/files/5151093/opencore-2020-08-31-145934.txt)
[opencore-2020-08-31-150042.txt](https://github.com/profzei/Matebook-X-Pro-2018/files/5151094/opencore-2020-08-31-150042.txt)

**Comment by Hernanduno** [comment]
Yeah, my logs file is the same stuck on -> [EB|#LOG:EXITBS:START]
I tried all the solutions proposed on troubleshoting area for that problem but not success installing OC :(
Also based on what I learned from the guide those problems are related with EC, maybe because this laptop already include a STAT method?  or maybe this could be related with power management. 
Any guidance will be really usefull :)
Regards
