### ISSUE TITLE
Is this working for my Matebook X Signature Edition (not the pro) (2018 -> i5-7200U & 256GB SSD)  

### ISSUE THREAD

**Issue by Vexcited** [profzei/Matebook-X-Pro-2018#45]
Hey !
I have this product
https://www.amazon.com/Huawei-MateBook-Signature-Ultraslim-Fingerprint/dp/B071VYDPF8?th=1&psc=1
(Huawei website -)
https://consumer.huawei.com/en/support/laptops/matebook-x/

and I want to know if this repo works with laptop. :/

Thanks!

**Comment by profzei** [comment]
Hi @Vexcited : OOB no... you need to modify some files to support your device...

**Comment by Vexcited** [comment]
@profzei whose files ? can you tell me what I need to change? i would be very happy cause I'm trying to do a hackintosh for so long now. ;-;

**Comment by Vexcited** [comment]
Ok I have found a repo where the specs are exactly the same as mine
It's in Chinese but Google Translate helped me to read the readme.md
And after its like this repo, I just need to copy the OC folder.

https://github.com/LEONLIIIIII/Hackintosh-For-Matebook-X
