### ISSUE TITLE
Audio shortcuts don't work.

### ISSUE THREAD

**Issue by huotarih** [profzei/Matebook-X-Pro-2018#47]
They've never worked for me but looks like they should (?)
I'm just using the Multi-output device.
Any advice is welcome :)

**Comment by huotarih** [comment]
I solved this with a few simple steps.
1: brew install soundflower
2: allow it to install a kext from system preferences -> security
3: restart
4: brew install soundflowerbed
5: open soundflowerbed and select multi output device

Now you have shortcuts working for your audio.

**Comment by R-Teer** [comment]
> I solved this with a few simple steps.
> 1: brew install soundflower
> 2: allow it to install a kext from system preferences -> security
> 3: restart
> 4: brew install soundflowerbed
> 5: open soundflowerbed and select multi output device
> 
> Now you have shortcuts working for your audio.

Hi @huotarih, hope your well!

Congrats on getting your audio shortcuts to work with Multi-Channel Audio

Which version of Mac OS are you running? I'm having issues getting home-brew to install on Big Sur.  I previously got my volume shortcuts to work using SoundSource but its unsupported in Big Sur.

**Comment by huotarih** [comment]
> > I solved this with a few simple steps.
> > 1: brew install soundflower
> > 2: allow it to install a kext from system preferences -> security
> > 3: restart
> > 4: brew install soundflowerbed
> > 5: open soundflowerbed and select multi output device
> > Now you have shortcuts working for your audio.
> 
> Hi @huotarih, hope your well!
> 
> Congrats on getting your audio shortcuts to work with Multi-Channel Audio
> 
> Which version of Mac OS are you running? I'm having issues getting home-brew to install on Big Sur. I previously got my volume shortcuts to work using SoundSource but its unsupported in Big Sur.

Hey @R-Teer, and sorry I missed this for so long.
I'm running Big sur 11.0 Beta 10.
I think I installed brew with just running `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"`
