### ISSUE TITLE
slow apple id, repeated sign ins required

### ISSUE THREAD

**Issue by Venipa** [profzei/Matebook-X-Pro-2018#49]
i've tried to remove the keychain, the method in the README.md but it still shows that i need to re sign in to use icloud.

macOS Catalina - 10.15.6

**Comment by Venipa** [comment]
![image](https://user-images.githubusercontent.com/17952364/91536181-2e3c5d80-e8c9-11ea-93c1-1b486babe654.png)

**Comment by homerostov** [comment]
Have a same problem
