### ISSUE TITLE
SSD Samsung PM981

### ISSUE THREAD

**Issue by sgutirodri** [profzei/Matebook-X-Pro-2018#5]
Is this SSD supported? I want to try hackintosh, but i don't know if exists kext for ssd Samsung PM981

**Comment by profzei** [comment]
As far as I know SSD Samsung PM81has still some issue with mackintosh in general: the fact is not due to this particular laptop.
For reference you can see: https://www.reddit.com/r/hackintosh/comments/evkljr/samsung_pm981_nvme_hackintosh_reboot_loop/
Some efforts for its support can be found here: https://github.com/acidanthera/NVMeFix/blob/master/Changelog.md

**Comment by sgutirodri** [comment]
Thanks for your effors @profzei! How can i put this kext in Clover? Copying it in CLOVER > kexts > others?

I have another question, how is the performance in Catalina? Best than Windows?

**Comment by juicypop** [comment]
Hey @sgutirodri don't waste your time trying to install it on pm981
I tried the past 5 days with absolutely no luck. Sometimes I got through the first stage to continue the install from my ssd but every time the ssd raises a KP. It's not worth the hustle. 

Tried last night with a transcend usb nvme and installed catalina in less than 30min on my USB, works so far without problems.

**Comment by profzei** [comment]
@sgutirodri: May be there is a last chance...
I found a "detailed guide" (you need to read all the discussion...) at https://github.com/tylernguyen/x1c6-hackintosh/issues/43
You can give it a try...

**Comment by sgutirodri** [comment]
Thanks for your information @juicypop and @profzei , I think that I will buy a new ssd.

**Comment by juicypop** [comment]
@sgutirodri I ordered a Kingston a2000 1tb, looked like the best value/gain in my opinion and is known to be working with osx. I will let you know later this evening or tomorrow if it's true or not.
@profzei I read this thread and it seems to be a bit too much work for a ssd that may still throw KP, i ended up in installing on usb and move later to my a2000

**Comment by juicypop** [comment]
Just to let you know, Kingston a2000 1TB works flawlessly :+1:

**Comment by FlasHRender** [comment]
> @sgutirodri I ordered a Kingston a2000 1tb, looked like the best value/gain in my opinion and is known to be working with osx. I will let you know later this evening or tomorrow if it's true or not.
> @profzei I read this thread and it seems to be a bit too much work for a ssd that may still throw KP, i ended up in installing on usb and move later to my a2000

So PM981 works perfectly after you get macOS installed. I have stress tested the drive and have dual boot running(Not a single crash due to the drive). No KP is observed. People who observed KP are the ones who couldn't follow the instructions.

**Comment by mehmetyukcell** [comment]
> > @sgutirodri I ordered a Kingston a2000 1tb, looked like the best value/gain in my opinion and is known to be working with osx. I will let you know later this evening or tomorrow if it's true or not.
> 
> > @profzei I read this thread and it seems to be a bit too much work for a ssd that may still throw KP, i ended up in installing on usb and move later to my a2000
> 
> 
> 
> So PM981 works perfectly after you get macOS installed. I have stress tested the drive and have dual boot running(Not a single crash due to the drive). No KP is observed. People who observed KP are the ones who couldn't follow the instructions. 
> 
> 

How works, clearly?
