### ISSUE TITLE
OpenCore not longer showing under EFI Boot Devices! (Solved)

### ISSUE THREAD

**Issue by barbarou** [profzei/Matebook-X-Pro-2018#50]
Hi,
**After updating windows 10 to v 2004 and config.plist to support OpenCore v. 0.6.1**
OpenCore not longer showing under EFI Boot Devices, its just showing Windows Boot Manager, and its booting now direct to windows. But when changing **bootmgfw.efi** to **bootmgfw-orig.efi**, OpenCore list appears again but only shows mac partition and can normally boot to macintosh. But windows partition disappears instead. What happened!, can anyone help me on what I can do to get OpenCore back to work as it was before, which I could select OpenCore for **Macintosh** and Windows Boot Manager for **windows 10** by holding **F12**.

****Solved** here**: https://github.com/profzei/Matebook-X-Pro-2018/issues/50#issuecomment-688203591 Thanks to **[R-Teer](https://github.com/R-Teer)**

**Comment by AshleyMiller9696** [comment]
Don't know why and how Windows 10 v2004 could infected this but both external MacOS Partition aren't able to boot
Holding F12 shows the device, but if selected - "Boot Failed" Error appears

**Comment by barbarou** [comment]
> // secure boot activated itself
> turning that off fixed this for me

Its already off, and I still have the same issue.

**Comment by R-Teer** [comment]
im having the same issue here, seems to be the windows update. Im still using 0.5.9 OC and cant see the options to boot into opencore.

Currently renaming to -orig is working to get into the mac os system

**Comment by barbarou** [comment]
> **FIXED:**
> 
> Pretty simple fix, seems the 2004 update has removed the OC boot entry
> 
> 1. Boot To WIndows and mount your EFI partition, open command prompt as an adminitrator and type the following:
> 
> `mountvol B: /s`
> 
> 1. Download and run BOOTICE as administrator [Download Bootice](https://github.com/profzei/Matebook-X-Pro-2018/files/5049205/BOOTICE.zip)
> 2. Click the UEFI tab, and edit boot entries
> 3. Create new boot entry and point it to opencore.efi in the OC folder on the EFI partion.
> 4. Save changes.
> 
> You will now have both opencore and windows boot manager on the F12 Menu.
> 
> Thanks to @profzei & @ycloud

Thank you very much, it now works perfectly by following your steps, even better than before as I can now boot into windows and macOs using opencore only, No longer need to press F10 every time I want to boot into windows.

**Comment by R-Teer** [comment]
> > **FIXED:**
> > Pretty simple fix, seems the 2004 update has removed the OC boot entry
> > 
> > 1. Boot To WIndows and mount your EFI partition, open command prompt as an adminitrator and type the following:
> > 
> > `mountvol B: /s`
> > 
> > 1. Download and run BOOTICE as administrator [Download Bootice](https://github.com/profzei/Matebook-X-Pro-2018/files/5049205/BOOTICE.zip)
> > 2. Click the UEFI tab, and edit boot entries
> > 3. Create new boot entry and point it to opencore.efi in the OC folder on the EFI partion.
> > 4. Save changes.
> > 
> > You will now have both opencore and windows boot manager on the F12 Menu.
> > Thanks to @profzei & @ycloud
> 
> Thank you very much, it now works perfectly by following your steps, even better than before as I can now boot into windows and macOs using opencore only, No longer need to press F10 every time I want to boot into windows.

You can indeed man, wouldn't really recommend using opencore to boot into windows at this moment, you will notice that under windows you will see that your system profiler shows that you are running a macbook pro.  Opencore injects the patches prior to booting the OS, so you will run into issues with things like your GPU etc.  Booting from F12 means you will be running windows on the correct settings.  We used to be able to bypass this using the NDK fork of opencore but we havent had any updates to that since 0.5.8 and we cant use it for Big Sur.  Im trying to find a workaround for this at the minute as i personally would love to be able to boot to windows from opencore and bypass the patching unless booting to OSX.  If I make any progress I will let you know!

**Comment by barbarou** [comment]
> You can indeed man, wouldn't really recommend using opencore to boot into windows at this moment, you will notice that under windows you will see that your system profiler shows that you are running a macbook pro. Opencore injects the patches prior to booting the OS, so you will run into issues with things like your GPU etc. Booting from F12 means you will be running windows on the correct settings. We used to be able to bypass this using the NDK fork of opencore but we havent had any updates to that since 0.5.8 and we cant use it for Big Sur. Im trying to find a workaround for this at the minute as i personally would love to be able to boot to windows from opencore and bypass the patching unless booting to OSX. If I make any progress I will let you know!

Thanks for saying that man. Let me know if you find a solution, I appreciate it :)
