### ISSUE TITLE
Matebook X Pro 2020 model

### ISSUE THREAD

**Issue by alexbiship** [profzei/Matebook-X-Pro-2018#51]
Hey, Thank you for doing such great work! I really appreciate it. I recently bought a new Matebook x pro 2020 model(green color) and tried to use this method but it didn't work.

CPU: Intel I7-10510u 
Graphics: Nvidia Geforce MX250/Intel UHD Graphics(No number like 620 or 630 etc)
3K display @ 3000x2000
16GB RAM
512 Gb WDC SSD

**Comment by hudp16** [comment]
Did not work is a pretty broad issue. going to need more than that.

**Comment by lory2k01** [comment]
> Hey, Thank you for doing such great work! I really appreciate it. I recently bought a new Matebook x pro 2020 model(green color) and tried to use this method but it didn't work.
> 
> CPU: Intel I7-10510u
> Graphics: Nvidia Geforce MX250/Intel UHD Graphics(No number like 620 or 630 etc)
> 3K display @ 3000x2000
> 16GB RAM
> 512 Gb WDC SSD

Hey. Have you found a working method? maybe using OpenCore?

**Comment by profzei** [comment]
@lory2k01 Try [this repo](https://github.com/Chilluminati91/Huawei-Matebook-X-Pro-2020-Hackintosh): it's quite updated and specific for your machine"
