### ISSUE TITLE
Error in Network Readme

### ISSUE THREAD

**Issue by brian-xu** [profzei/Matebook-X-Pro-2018#54]
Hello,

I noticed an error in the instructions for setting up AirportItlwm. Step 6 is currently:

6. Open `/EFI/OC/config.plist` and find the following code:
```
<dict>
	<key>Arch</key>
	<string>x86_64</string>
	<key>BundlePath</key>
	<string>AirportItlwm.kext</string>
	<key>Comment</key>
	<string>Intel Wi-Fi driver</string>
	<key>Enabled</key>
	<false/>
	...
```
and change to:
```
<dict>
	<key>Arch</key>
	<string>x86_64</string>
	<key>BundlePath</key>
	<string>AirportItlwm.kext</string>
	<key>Comment</key>
	<string>Intel Wi-Fi driver</string>
	<key>Enabled</key>
	<true/>
	...
```

However, it should be:

6. Open `/EFI/OC/config.plist` and find the following code:
```
<dict>
	<key>Arch</key>
	<string>x86_64</string>
	<key>BundlePath</key>
	<string>itlwm.kext</string>
	<key>Comment</key>
	<string>Intel Wi-Fi driver</string>`
	<key>Enabled</key>
	<false/>
	<key>ExecutablePath</key>
	<string>Contents/MacOS/itlwm</string>
	...
```
and change to:
```
<dict>
	<key>Arch</key>
	<string>x86_64</string>
	<key>BundlePath</key>
	<string>AirportItlwm.kext</string>
	<key>Comment</key>
	<string>Intel Wi-Fi driver</string>
	<key>Enabled</key>
	<true/>
	<key>ExecutablePath</key>
	<string>Contents/MacOS/AirportItlwm</string>
	...
```

As it currently reads, the instructions do not work and result in a softlock at the Apple logo. This fixes that.

**Comment by yamanadamnor** [comment]
I recently updated to the big sur beta and I have been experiencing some weird boot issues. I dont know if it is related to AirportItlwm but i updated to AirportItlwm with your recommended settings but it didnt help. The issue seem to be related to itlwm when looking at the verbose output on boot.

My latest boot logs

[opencore-2020-09-19-012409.txt](https://github.com/profzei/Matebook-X-Pro-2018/files/5251439/opencore-2020-09-19-012409.txt)
[opencore-2020-09-19-013153.txt](https://github.com/profzei/Matebook-X-Pro-2018/files/5251440/opencore-2020-09-19-013153.txt)

**Comment by profzei** [comment]
@brian-xu Hi, in actual `config.plist` we have both `itlwm` and `AirportItlwm` kexts with `Enabled` value set to `false`:
so if you want to use `itlwm.kext`/`AirportItlwm.kext` you need to change only its value to `true` leaving the other unchanged (i.e. set to `false`)

**Comment by profzei** [comment]
Just updated `Network/Readme` and `OC/config.plist`: we can force injection of `IO80211Family.kext` for `AirportItlwm.kext`

**Comment by brian-xu** [comment]
Oh, I must have not noticed the AirportItlwm option in the plist. Marking as fixed then.
