### ISSUE TITLE
Windows/Command Key

### ISSUE THREAD

**Issue by aruro91** [profzei/Matebook-X-Pro-2018#57]
Hi,
I have successfully installed Big Sur with OC 0.6.1. Currently, when I am using the window key for example copy/paste (WIN+C,WIN+V), it is not working and special characters are getting written in TextEdit. Is there anyway to make windows key work as apple's command key?

**Comment by profzei** [comment]
@aruro91 Hi, there are a lots of possible ways for switching command key... I always forgot to implement it!
Try to replace original `SSDT-FnKey.aml` with the following one and enjoy switching feature
[SSDT-FnKey.aml.zip](https://github.com/profzei/Matebook-X-Pro-2018/files/5322265/SSDT-FnKey.aml.zip)

**Comment by yamanadamnor** [comment]
How do I revert back to the original state. I have gotten used to using left-alt as command

**Comment by profzei** [comment]
@yamanadamnor : you need to put in OC/ACPI folder the SSDT-FnKey.aml from previous release 1.5.0 replacing the corresponding file from actual release 1.6.0

**Comment by yamanadamnor** [comment]
> @yamanadamnor : you need to put in OC/ACPI folder the SSDT-FnKey.aml from previous release 1.5.0 replacing the corresponding file from actual release 1.6.0

Thanks for the reply
