### ISSUE TITLE
My Surface Ergonomic Keyboard does not pair 

### ISSUE THREAD

**Issue by aswinstha** [profzei/Matebook-X-Pro-2018#59]
Surface Ergonomic Keyboard shows up as a Bluetooth device, but the loader keeps spinning when I try to connect it. No pairing code shown. Tried it on a MacBook and it instantly shows the pairing code and pairs flawlessly. Any fix for this?

**Comment by profzei** [comment]
No, it is related to [IntelBkuetoothFirmware](https://github.com/OpenIntelWireless/IntelBluetoothFirmware) and not to this configuration. Open an issue there...
