### ISSUE TITLE
CPU power limit when using battery

### ISSUE THREAD

**Issue by kxlv2000** [profzei/Matebook-X-Pro-2018#60]
Hi, there

I found that if the moment OC/Clover preboot with AC adapter plugged ,the CPU TDP can go over 15w. otherwise there will be a TDP limitation about 15w. It was decided at the Preboot stage, which won't change after macOS booted.

<img width="656" alt="image" src="https://user-images.githubusercontent.com/49295281/96278148-ba384f00-1007-11eb-83c9-55d2582bed18.png">
Img: These two values will be set to 1 if I using battery during OC/Clover preboot stage

Do you have any idea about this feature(not bug),I want to keep high performance mode no matter which power source I choose.

Thanks

**Comment by profzei** [comment]
@kxlv2000 : Honestly I don't know... Have you checked some variable inside BIOS?

**Comment by kxlv2000** [comment]
Ok, Thanks. Since I find nothing related to this issue in kexts or sstd, too,  I'll have a try !
