### ISSUE TITLE
Resolution

### ISSUE THREAD

**Issue by LavenderMP** [profzei/Matebook-X-Pro-2018#62]
Hi prof, first of all thanks for contribute a great project.
I have a question about resolution since my laptop is running natively HiDPI 1500x1000 but I find that is a little bit small to read (My eye is farmilar on 1440x900 on 15.6 inches) there is any way to reduce resolution a little abit for example 1200x800?
Thanks in advance

**Comment by jonescamilla** [comment]
SwitchResX is actually how I achieve the opposite (higher than the 1500x1000). So I'm sure you can set a resolution best fit for you in that software.

**Comment by R-Teer** [comment]
> SwitchResX is actually how I achieve the opposite (higher than the 1500x1000). So I'm sure you can set a resolution best fit for you in that software.

Have you been able to enable hidpi for 1920x1080? Can't for the life of me get it to work (if even possible)

**Comment by jonescamilla** [comment]
> Have you been able to enable hidpi for 1920x1080? Can't for the life of me get it to work (if even possible)

You'll have to 2x the desired resolution for hidpi to kick in. Apple's hidpi works (as far as I know) by taking a resolution and then giving a hidpi res you can select at half the original resolution.

In the case of `1920x1080` you'll set a resolution of `3840x2160`

**Comment by R-Teer** [comment]
> > Have you been able to enable hidpi for 1920x1080? Can't for the life of me get it to work (if even possible)
> 
> You'll have to 2x the desired resolution for hidpi to kick in. Apple's hidpi works (as far as I know) by taking a resolution and then giving a hidpi res you can select at half the original resolution.
> 
> In the case of `1920x1080` you'll set a resolution of `3840x2160` and see a `1920x1080 hdpi` option

Working perfect dude! 
Had a few snags getting it to work on Big Sur but was able to make adjustments inside /Library rather than System/Library.  All is working great Thanks a million
