### ISSUE TITLE
Add guide/script to enable TRIM (idea)

### ISSUE THREAD

**Issue by alex-spataru** [profzei/Matebook-X-Pro-2018#68]
I have previously used this bootloader configuration and found it very useful. However, I don't have a Matebook anymore. I now have an older [HP Spectre x360](https://github.com/alex-spataru/HP-Spectre-4101dx-Hackintosh) running macOS Catalina. Recently, I [enabled TRIM support](https://eclecticlight.co/2019/08/26/caring-for-ssds-trim-wear-levelling-and-apfs/) and gained considerable performance on my machine. 

You might want to check this out, however, I don't know exactly what are the differences between SSD and NVME disks. For this reason, I opened an issue and not a PR, since I cannot test or measure the effects of enabling TRIM on this computer model and its NVME drive.

Greetings, and thanks for this project!

**Comment by profzei** [comment]
@alex-spataru 
Thank you for your support and your hints!
I just run the command `sudo trimforce enable` in Terminal app and rebooted my machine...
How do I check a "considerable gain on performance"?

**Comment by alex-spataru** [comment]
Hi, in my case, my Hackintosh became very slow and unresponsive when executing disk-intensive tasks, such as copying files, booting, compiling, etc. This problems where somewhat reduced after running the `sudo trimforce enable` command and rebooting. I don't know how visible will be the changes on a Matebook X Pro (it still has way better hardware as my current computer, and probably mileage may vary depending on how you use your computer).

Unfortunately, I haven't really tried any macOS utility that measures disk R/W performance.
