### ISSUE TITLE
Not able to configure VoltageShift

### ISSUE THREAD

**Issue by kilgil27** [profzei/Matebook-X-Pro-2018#69]
from the instructions for setting up VoltageShift - "If you want to use this feature, enable it in your config.plist in Kernel -> Add section"

However, I don't see the VoltageShift entry in that section (or anywhere in the config file) Do I need to add it manually or am I missing it somewhere?

**Comment by profzei** [comment]
@kilgil27 Please refer to "latest release" i.e. (atm) v. 1.6.0
