### ISSUE TITLE
How to activate intel wifi card? 

### ISSUE THREAD

**Issue by juicypop** [profzei/Matebook-X-Pro-2018#7]
What should I do in order to test this awesome project? 
https://github.com/zxystd/itlwm

Did you disable the Intel wifi card so that I first need to enable it in order to make itlwm work? 

I'd appreciate a noob friendly step by step what to do so that my intel wifi is in working mode. 

Thanks for your hard work :)

**Comment by profzei** [comment]
It's very simple! You only need to delete SSDT-DRP11.aml: in this way intel wifi card come back. in working mode!

**Comment by juicypop** [comment]
Thanks, I'll report back as soon as I get back to my desk :)

**Comment by juicypop** [comment]
I had no luck in compiling this kext my self so I tried a Chinese kext and it actually really works, that's so awesome :smile:

Simply follow this guy's video, no need to disable SIP as it's already disabled by our config.plist
https://youtu.be/ICpgYtzbxP8
