### ISSUE TITLE
Using touchpad cause high cpu usage

### ISSUE THREAD

**Issue by paulokiim** [profzei/Matebook-X-Pro-2018#70]
When I use my touchpad suddenly the CPU usage of the process called "WindowServer" increases a lot. I don't know if this is the normal behaviour of the system or some problem, so I'm reporting it here to get more informations about it.
Anyone had the same issue or is it normal?

The next screenshot is without using the touchpad:
<img width="1500" alt="Screen Shot 2020-10-27 at 22 59 23" src="https://user-images.githubusercontent.com/43527938/97311920-3f452300-18a8-11eb-8dc8-b20eb6074e2e.png">

The next screenshot is using 1(one) finger on the touchpad:
<img width="1500" alt="Screen Shot 2020-10-27 at 22 59 04" src="https://user-images.githubusercontent.com/43527938/97312001-5b48c480-18a8-11eb-94e3-2ae407a6a2d4.png">

The next screenshot is using 2(two) fingers on the touchpad:
<img width="1500" alt="Screen Shot 2020-10-27 at 22 58 43" src="https://user-images.githubusercontent.com/43527938/97312047-656ac300-18a8-11eb-8a1d-7f17f8c4e9f4.png">

**Comment by profzei** [comment]
AFAIK it is a "known" VoodooI2C & satellites bug (now it is dramatically reduced respect to past releases...)
