### ISSUE TITLE
Question/Request

### ISSUE THREAD

**Issue by m0d16l14n1** [profzei/Matebook-X-Pro-2018#71]
Hey. I would like to ask you to dump your audio codec on linux, please. 

I also have a laptop on Realtek ALC256, upper speakers are node 20, lower are node 27, headphones is node 33 in my case. So, I tried all the layouts, almost all of them have working microphone + headphones + ONLY upper speakers (which are really bad), on the layouts that are made for your laptop - i have working microphone + 4 speakers, BUT the headphones don't work at all (don't see output option for them), although your nodes for headphones are the same as mine. 

That's why i ask for your dump to check with my own one and possibly understand and find the difference and fix it for my laptop. Thanks in advance and apologize for this request

P.S. - My codec files is in Tools > Audio - https://github.com/Ardentwheel/OpenCore-Hasee-X57S1

**Comment by profzei** [comment]
@m0d16l14n1 
Happy to help! Is the following file what you need?
[Codec0.txt](https://github.com/profzei/Matebook-X-Pro-2018/files/5448416/Codec0.txt)

**Comment by m0d16l14n1** [comment]
@profzei yeah, thanks!

**Comment by m0d16l14n1** [comment]
@profzei weird, but nodes from your dump are equal to nodes for my audio device, but on all layouts for your laptop (14, 19, 76, 97 - i have only speakers + internal mic/line-in working, no headphones) 
On windows all is working correctly. On Ubuntu i used hdajackretask to override pin for bottom speakers (0x1b) and headphones (0x21) and on ubuntu i have now all audio devices working (headphones working without autoswitch)

Weird...
