### ISSUE TITLE
Request: Add reference to XiaoMi-Pro-Hackintosh Repository

### ISSUE THREAD

**Issue by stevezhengshiqi** [profzei/Matebook-X-Pro-2018#72]
Hi guys, thank you all so much for contributing to this project and helping the Matebook hackintosh community.

I notice that in the wiki page, ALCPlugFix and Network parts, there're many similar parts as [daliansky](https://github.com/daliansky)'s [XiaoMi-Pro-Hackintosh](https://github.com/daliansky/XiaoMi-Pro-Hackintosh). Although we use a 0BSD license that does not mandatorily require a copyright notice, it would be very nice if you guys can put [XiaoMi-Pro-Hackintosh](https://github.com/daliansky/XiaoMi-Pro-Hackintosh) in the credits at [Readme.md](https://github.com/profzei/Matebook-X-Pro-2018/blob/master/Readme.md). [daliansky](https://github.com/daliansky) and I paid lots of effort on the wiki, documents, and so on.

Have a great day and keep going!✊✊

**Comment by profzei** [comment]
Hi, it's my pleasure!
Some time ago I opened a request [#205](https://github.com/daliansky/Hackintosh/issues/205) for Daliansky's [Hackintosh](https://github.com/daliansky/Hackintosh) repo... please, could you remind it?

**Comment by stevezhengshiqi** [comment]
@profzei Would u mind creating a PR? Issues in that repository are always be ignored, sorry for that.
