### ISSUE TITLE
Question - low score in geekbench ?

### ISSUE THREAD

**Issue by isuke01** [profzei/Matebook-X-Pro-2018#75]
Hey, 

I used OC Boot loader, 
I fallow all steps, (except undervolting) 
And my score for Geek Bench 5 is around 2.5k  in CPU bench it is 400 and 1.7k :P
https://browser.geekbench.com/v5/compute/1769320
https://browser.geekbench.com/v5/cpu/4564042

Catalina 10.15.7
During test temps were around 61deg, fans never went up, all time silent. 

What I did wrong/miss?

**Comment by profzei** [comment]
@isuke01 Question: are you on battery or plugged in ?

**Comment by isuke01** [comment]
Yes, i was, 
I also tried GB5 on the Windows and score looks fine.

**Comment by isuke01** [comment]
Any ideas what might happen?

**Comment by profzei** [comment]
@isuke01 Yeah, sorry but I forgot what I've done for getting the value I published... xD

You need to add in `NVRAM -> Add -> 7C436110-AB2A-4BBB-A880-FE41995C9F82` -> boot-args the option `-igfxnorpsc=1` ...(if I remember well... but I'm not totally sure) this quirk is documented in WhateverGreen FAQ.

Please let me know your feedback!

**Comment by isuke01** [comment]
@profzei Actually I see same results more or less, I'll look more what is happening, and why when I can find some time :)
