### ISSUE TITLE
Keyboardbacklight?

### ISSUE THREAD

**Issue by Hitchi20** [profzei/Matebook-X-Pro-2018#76]
I don't have the matebook x pro but non pro (not that different hardware specs)... sorry for that...

Don't know how to collaborate with you 

I've used ur EFI as a bases to fill my own... everything is working fine except the keyboardbacklight. Could you please tell me if its working for you and also the Fn+F3 key switch it off?  Don't know where to search for the right SSDT or where should I have a look into. 

Ur help would be very appreciated. 

Thx in advance

**Comment by huotarih** [comment]
No idea how the non pro version works, but on x pro the keyboard backlight works, also f3 works. and fn works, when i toggle fn, it works as normal f3.

**Comment by Hitchi20** [comment]
And that's the point... anyone knows which ssdt is responsible for this?

**Comment by profzei** [comment]
@Hitchi20 
As @huotarih said above, keyboard backlight is native, so there is no ssdt responsible for this!
