### ISSUE TITLE
Question about Dual-Booting w/ Partitioned Drive

### ISSUE THREAD

**Issue by hnlkaitan** [profzei/Matebook-X-Pro-2018#77]
So I was thinking of splitting the internal drive (currently using an SSD but performance is sluggish compared to my MBP). I'm game to just nuke the drive and then clean install both Windows and macOS. Do I just:

1. Make macOS and Windows 10 installers
2. Boot into macOS USB installer, erase entire drive & reserve space for Windows (what format for the drives: GUID Partition Scheme and then APFS for macOS and ex-FAT for Windows)
3. Install macOS onto APFS partition
4. Let it install, reboot into Windows installer, then install it onto the ex-FAT partition (installer makes it NTFS).
5. Anything else? Someone else on Reddit said to keep the macOS Installer just in-case a Windows update messes with the EFI partition? Do I follow [this guide](https://dortania.github.io/OpenCore-Post-Install/multiboot/bootstrap.html#preparation)?

**Comment by huotarih** [comment]
I left my windows as-is, and installed mac os big sur beta straight into the new partition. I wish i documented the steps back then but I didn't. I think I just split the disk in windows disk management, installed mac as I'd do to an external, choose the opencore as my default boot, then did some log thing to add an entry to opencore for windows. I'm sure there's a tutorial for that somewhere. I'm not sure if i've updated windows after installing this but I haven't had any issues. Maybe you can backup your efi partition so you can restore it from an installer usb if it gets broken. @hnlkaitan

**Comment by isuke01** [comment]
Hey, I did exFat partition under windows, like 250gg (for mac os) so mac installer can read it.
Basically I followed https://hackintoshpro.com/dual-boot-hackintosh/  from since step 3.
Now I have partition with installed Hackintosh and Windows. I also created backup of my Windows EFI directory. 

I  can boot into Hackintosh no problem but I'm not sure how to add Windows boot into OC settings. 
So to boot into windows I have to put pendrive with Boot EFI for windows ... xD

**Comment by profzei** [comment]
@isuke01 For example you could give a try to [this](https://github.com/profzei/Matebook-X-Pro-2018/wiki/Converting-from-Clover-to-OpenCore#how-to-dual-boot-macos-with-opencore-and-windows-10)

**Comment by isuke01** [comment]
@profzei Thanks! It worked :)

**Comment by profzei** [comment]
@isuke01 
At my knowledge, nope... what do I mean?
- if you use **rEFInd** boot you need to set (as stated in the guide...) `Misc -> Security -> BootProtect -> None`: this means that OpenCore Boot is not protected and therefore Windows 10 could overwrite it with its settings... in such a case you need to make a backup of your `\EFI\BOOT` and `\EFI\OC` folders before upgrading Windows and then restore them;
- if, instead, you select your OS pressing `Fn12` to access `BIOS Boot Option Menu`, this means that in your config.plist you should have `Misc -> Security -> BootProtect -> Bootstrap` which means that OpenCore Boot is protected against Windows 10 possible overwriting...
