### ISSUE TITLE
Airdrop Availability 

### ISSUE THREAD

**Issue by Diputsman** [profzei/Matebook-X-Pro-2018#78]
Is Airdrop currently available, or is that something that won't be possible?

**Comment by profzei** [comment]
@Diputsman 
Hi, as stated [in Dortania's today announcement](https://dortania.github.io/hackintosh/updates/2020/11/12/bigsur-new.html) , atm for **all Intel Wi-Fi** cards _Airdrop support currently is also not implemented, however is actively being worked on_
