### ISSUE TITLE
Undervolt via VoltageShift

### ISSUE THREAD

**Issue by Vatri91** [profzei/Matebook-X-Pro-2018#79]
Guys,

how to do this step?

"If you want to use this feature, enable it in your config.plist in Kernel -> Add section"

**Comment by dhjs0010** [comment]
Same question.

**Comment by Vatri91** [comment]
Last login: Mon Nov  9 19:48:27 on ttys001
adriann@Adrians-MBP ~ % cd /Applications/Utilities 
adriann@Adrians-MBP Utilities % ./voltageshift info       
adriann@Adrians-MBP Utilities % ./voltageshift offset -100 -50 -100
adriann@Adrians-MBP Utilities % ./voltageshift info                
adriann@Adrians-MBP Utilities % 

Nothing happens

**Comment by dhjs0010** [comment]
When I type ./voltageshift info I get "permission denied", so I can't do anything.

ivan@Ivans-MacBook-Pro Utilities % ./voltageshift info
zsh: permission denied: ./voltageshift

**Comment by Vatri91** [comment]
Try "chmod +x voltageshift"
then: "./voltageshift info"

**Comment by dhjs0010** [comment]
It works! Thank you!

By the way, for your question, I think what I did is what's correct then: I simply added this under the Kernel -> Add section:

<dict>
				<key>Arch</key>
				<string>x86_64</string>
				<key>BundlePath</key>
				<string>VoltageShift.kext</string>
				<key>Comment</key>
				<string>Undervolt settings</string>
				<key>Enabled</key>
				<true/>
				<key>ExecutablePath</key>
				<string>Contents/MacOS/VoltageShift</string>
				<key>MaxKernel</key>
				<string></string>
				<key>MinKernel</key>
				<string>12.0.0</string>
				<key>PlistPath</key>
				<string>Contents/Info.plist</string>
			</dict>

**Comment by profzei** [comment]
Just a question... Have you tried to use latest release?
@Vatri91 @dhjs0010

**Comment by dhjs0010** [comment]
I'm on latest release for everything in the repo, but now it works with the method I wrote above!

**Comment by profzei** [comment]
@dhjs0010 So you have found in `config.plist` in latest release the code you posted above, haven't you?

**Comment by profzei** [comment]
@Vatri91 

> Try "chmod +x voltageshift"
> then: "./voltageshift info"

When I uploaded `voltageshift` script, I added the attribute `x` which means _executable_... maybe this attribute doesn't persist when you download it from repo so you need to add it again! Honestly I didn't check it before... 
If this behaviour is confirmed by other users I'll fix relative instructions!

**Comment by dhjs0010** [comment]
> @dhjs0010 So you have found in `config.plist` in latest release the code you posted above, haven't you?

Nope! I had to add it manually. The `config.plist` from the latest repo doesn't have anything related to VoltageShift.kext as a search for "volt" yields 0 results.

**Comment by profzei** [comment]
@dhjs0010 You are right when you said that the `config.plist` from the **latest repo** doesn't have any reference to `Voltageshift`.

...I didn't make any reference to **latest repo** but to **latest release** which is present in the **right sidebar** of this repo.
I'm not sure if I'm clear...

**Comment by dhjs0010** [comment]
Okay, I feel like the stupidest person right now. I've been looking at/downloading from the wrong place all this time. I'm sorry, I'm new to github! You are totally right, the latest release has everything.

**Comment by profzei** [comment]
@dhjs0010 No problem! Important thing is only to be clear... this repo is not perfect... I'm not perfect! xD

**Comment by dhjs0010** [comment]
@profzei You can ignore the issue I opened about wake up kernel panic as well, I'm gonna try to update everything from the release. In my mind "latest release" just meant you updated the repo. 

Thanks for responding and for all the work! It's been amazing to use this laptop with macOS.

**Comment by Vatri91** [comment]
This helped:

<dict>
				<key>Arch</key>
				<string>x86_64</string>
				<key>BundlePath</key>
				<string>VoltageShift.kext</string>
				<key>Comment</key>
				<string>Undervolt settings</string>
				<key>Enabled</key>
				<true/>
				<key>ExecutablePath</key>
				<string>Contents/MacOS/VoltageShift</string>
				<key>MaxKernel</key>
				<string></string>
				<key>MinKernel</key>
				<string>12.0.0</string>
				<key>PlistPath</key>
				<string>Contents/Info.plist</string>
			</dict>

Thank you too @dhjs0010 :) and ofc @profzei for your work

**Comment by samwzlim** [comment]
![image](https://user-images.githubusercontent.com/74489037/101178021-6f3fcd00-3683-11eb-8cd2-6912be7aec0e.png)
@profzei I need help, I'm already at the last step of undervolting, but I get this error message. Have already saved the wakeup script as .wakeup and moved it to $HOME directory

**Comment by rohirrim27** [comment]
@samwzlim : Running into the same problem here. Were you able to find a solution?

**Comment by samwzlim** [comment]
> @samwzlim : Running into the same problem here. Were you able to find a solution?

sorry nope, i stopped trying to undervolt ever since…

**Comment by rohirrim27** [comment]
@profzei : Hope you're enjoying the well deserved holidays! Let us know if you have any suggestions for us on the above when you're back. Thanks again!
