### ISSUE TITLE
Can't boot

### ISSUE THREAD

**Issue by hdamico** [profzei/Matebook-X-Pro-2018#8]
I am using the last build but I'm getting stuck at the boot. [Verbose capture](https://i.ibb.co/qkv9Yx7/Whats-App-Image-2020-05-20-at-5-53-18-PM.jpg).
It seems to be a common error in Hackintosh, 'cause I found a lot of threads about this. There isn't a common solution, but it seems to be a problem with the map of the ports or something like that. So maybe an error on a DSDT file?

**Comment by profzei** [comment]
...Are you trying a clean Catalina install?

...or did you replace your previous EFI folder with mine? In such a case, I guess you are using config-catalina-locked.plist, right!?

**Comment by hdamico** [comment]
Well, it seems that this quarantine is killing me. I didn't check the .plist, thanks for the highlight. And btw great work!
