### ISSUE TITLE
Kernel panic after wake up, thunderbolt power on failed

### ISSUE THREAD

**Issue by dhjs0010** [profzei/Matebook-X-Pro-2018#81]
I already checked the other issues in which it is stated that v1.2 fixed this issue, however I am encountering it as it happens every night when I put the computer to sleep overnight. I'm on latest version of everything in this repo. Any help is greatly appreciated! Thank you!

panic(cpu 0 caller 0xffffff7f8c2d53c5): "DSB0(MacBookPro15,2): thunderbolt power on failed 0xffffffff\n"@/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/IOPCIFamily/IOPCIFamily-370.141.1/IOPCIBridge.cpp:1398
Backtrace (CPU 0), Frame : Return Address
0xffffff812fafb9e0 : 0xffffff800b51a65d
0xffffff812fafba30 : 0xffffff800b654a75
0xffffff812fafba70 : 0xffffff800b6465fe
0xffffff812fafbac0 : 0xffffff800b4c0a40
0xffffff812fafbae0 : 0xffffff800b519d27
0xffffff812fafbbe0 : 0xffffff800b51a117
0xffffff812fafbc30 : 0xffffff800bcc1a6c
0xffffff812fafbca0 : 0xffffff7f8c2d53c5
0xffffff812fafbcc0 : 0xffffff7f8c2bcfab
0xffffff812fafbd20 : 0xffffff7f8c2bd15c
0xffffff812fafbd60 : 0xffffff7f8c2bd303
0xffffff812fafbda0 : 0xffffff7f8c2bd4d8
0xffffff812fafbdc0 : 0xffffff7f8c2bb6d2
0xffffff812fafbe10 : 0xffffff7f8c2c6023
0xffffff812fafbe30 : 0xffffff800bc13794
0xffffff812fafbea0 : 0xffffff800bc1359a
0xffffff812fafbec0 : 0xffffff800b55c605
0xffffff812fafbf40 : 0xffffff800b55c131
0xffffff812fafbfa0 : 0xffffff800b4c013e
Kernel Extensions in backtrace:
com.apple.iokit.IOPCIFamily(2.9)[44472E6F-8DA0-3B46-ADEF-AFF76EC6C6DB]@0xffffff7f8c2b4000->0xffffff7f8c2ecfff

BSD process name corresponding to current thread: kernel_task
Boot args: -cdfon -igfxmlr darkwake=1 dart=0 gfxrst=1

Mac OS version:
19H2

Kernel version:
Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64
Kernel UUID: 05D51A3D-3A87-3FF0-98C3-9CF3827A3EDD
Kernel slide: 0x000000000b200000
Kernel text base: 0xffffff800b400000
__HIB text base: 0xffffff800b300000
System model name: MacBookPro15,2 (Mac-827FB448E656EC26)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 39068920509045

EDIT: I installed everything from *release* 1.6 and still have the issue.

**Comment by profzei** [comment]
@dhjs0010 Hi, honestly I didn't faced the issue you reported on Catalina... so I don't know how to help you. The only advice I could give is a fresh reinstall...
