### ISSUE TITLE
Installation aborting at about 5-10%

### ISSUE THREAD

**Issue by memeplex** [profzei/Matebook-X-Pro-2018#83]
I have a

```
	Manufacturer: HUAWEI
	Product Name: MACH-WX9
	Version: M14
```

I have used https://raw.githubusercontent.com/Broly1/tribeam/master/tribeam.sh to create a bootable usb (net installer) for catalina (tested with 10.15.6 and 10.15.7). Then I replaced the EFI folder with yours and followed the instructions to set AirportItlwm.

The installer starts, I'm able to create a partition to install the system, connect to my wifi and start installing, but at some point the installation always abort, the system reboots and I get and error like "Your computer was restarted because of a problem".

**Comment by profzei** [comment]
@memeplex I'm sorry but your machine is not a MateBook X Pro 2018, so actual releases are compatible with it

**Comment by memeplex** [comment]
Why do you think so? The case shows MACH-W29, what is that you call 2018? Wikipedia shows many W29 as 2018 models.

**Comment by memeplex** [comment]
These are some specs from my Matebook X Pro:

* Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
* NVIDIA Corporation GP108M [GeForce MX150]
* Intel Corporation UHD Graphics 620
* 3000x2000 screen
* 16 GB memory

Externally is exactly as the models listed in Amazon for 2018.

What am I missing?

**Comment by profzei** [comment]
@memeplex 

> Why do you think so?

Very simple... because **you** reported:

> I have a
> ```
> 	Manufacturer: HUAWEI
> 	Product Name: MACH-WX9
> 	Version: M14
> ```
and **MACH-WX9** is different from **MACH-W29**... moreover, at my knowlegde (but I may be wrong...) there is not a MateBook X Pro with version: **M14**

**Comment by memeplex** [comment]
It's just the output from dmidecode, maybe check what yours report:

```
dmidecode | grep -A3 '^System Information' 
```

The computer is certainly a Matebook Pro X and I bought it at the beginning of 2019, the model that is printed in the case is MACH-W29 (maybe the X in WX9 is intended to match W19 and W29).

**Comment by memeplex** [comment]
Also check this https://www.reddit.com/r/MatebookXPro/comments/amvqw5/new_mxp_update_biosme_firmware_now_detecting_as/

>  seemed to change and report the device as a MACH-WX9 rather than the MACH-W29 

> The X in WX9 probably means "whatever number".

**Comment by profzei** [comment]
Sorry, you are right! My fault... xD

Try to make a full offline installation i.e. not using `AirportItlwm.kext` during install process... I never tried whether it could work or not, but I prefer a failsafe process

For install macOS you can refer to [EFI stuff here](https://github.com/profzei/Matebook-X-Pro-2018/wiki/Upgrade-to-macOS-Big-Sur): it's not updated but still (imho) working...
Then you can download latest release (right sidebar menu) and put it in your EFI folder inside your PCI NVMe SSD
