### ISSUE TITLE
Battery completely dead after sleep [SOLVED]

### ISSUE THREAD

**Issue by JonnIEnglish** [profzei/Matebook-X-Pro-2018#85]
Laptop:
Huawei Matebook X Pro 2018
i7-8550U
16GB RAM
512GB SSD

Running:
macOS Big Sur version 11.0 Beta (20A5395g)

Problem:
Every few times I close the lid of the laptop after doing something, and the battery is still on a decent percentage, sometimes even above 50%, I will open it up a few hours later to find the laptop completely dead showing the battery low screen at boot and not booting up. 

I have also noticed that the laptop will suddenly die at 20% without warning and I will have to plug it in for it to boot again. 

I am not sure if anyone else is having this problem but it is quite worrying, and any assistance will be greatly appreciated. 

Many thanks,

Jonathan

[EFI.zip](https://github.com/profzei/Matebook-X-Pro-2018/files/5523870/EFI.zip)

**Comment by profzei** [comment]
@JonnIEnglish Atm, I've not done extended tests for long sleep periods on Big Sur for two reasons:
- it's still in beta phase even if RC2 (released today) is expected to be "very similar" to final version...
- it's installed on an external usb-device

However, I'm trying to get some time (from real life...) for finalize a new release with both OpenCore 0.6.3 support and renewed ACPI section (also for sleep-wakeup).

**Comment by JonnIEnglish** [comment]
@profzei Alright thank you for letting me know. Do you have any timeframe for when this issue may be able to be sorted out?

Also if you need me to do some real world testing for you I'd be more than happy to lend a hand.

Many thanks for everything!

**Comment by profzei** [comment]
@JonnIEnglish 
Do you have any timeframe for when this issue may be able to be sorted out?

I'll make a new release in a few days (weekend) so I'll check this issue by that date... Honestly I don't know if I'll be also able to fix it by that date... hope so!

**Comment by JonnIEnglish** [comment]
@profzei Alright great! I'll be looking forward to it. Many thanks!

**Comment by JonnIEnglish** [comment]
Okay so I seem to have solved the issue by disabling 'Other Wakeup Source' in BIOS. 
![IMG_20201113_073418](https://user-images.githubusercontent.com/24739247/99180656-be53ab80-2730-11eb-9d3f-4dc1aa3a5b1c.jpg)

I disabled this a few days ago and have not had the battery issue since. The battery percentage now stays the same or drops a percent or two overnight, which I think is the expected behaviour.

I would highly recommend fixing any battery issues one may experience as soon as possible because in the few instances of my battery dying completely during sleep, my overall battery health has been severely compromised and according to Coconut Battery I now only have 68% of my battery's design capacity, and my battery temperature now shows many hundreds of degrees below 0.
<img width="264" alt="Screenshot 2020-11-15 at 10 53 24" src="https://user-images.githubusercontent.com/24739247/99180667-ce6b8b00-2730-11eb-87d2-a9761216ae7c.png">

**Comment by samwzlim** [comment]
> Okay so I seem to have solved the issue by disabling 'Other Wakeup Source' in BIOS.
> ![IMG_20201113_073418](https://user-images.githubusercontent.com/24739247/99180656-be53ab80-2730-11eb-9d3f-4dc1aa3a5b1c.jpg)
> 
> I disabled this a few days ago and have not had the battery issue since. The battery percentage now stays the same or drops a percent or two overnight, which I think is the expected behaviour.
> 
> I would highly recommend fixing any battery issues one may experience as soon as possible because in the few instances of my battery dying completely during sleep, my overall battery health has been severely compromised and according to Coconut Battery I now only have 68% of my battery's design capacity, and my battery temperature now shows many hundreds of degrees below 0.
> <img alt="Screenshot 2020-11-15 at 10 53 24" width="264" src="https://user-images.githubusercontent.com/24739247/99180667-ce6b8b00-2730-11eb-87d2-a9761216ae7c.png">

I am suffering from the same issue. Is there any chance this problem can be solved without disabling other wakeup source? Reason is I want to be able to wake my laptop up from sleep by just opening the lid when its closed. As of the moment, I have to press the power button everytime I want to wake the laptop up from sleep (must be related to other wakeup sources)

**Comment by samwzlim** [comment]
@profzei, I believe there must be a way to prevent sleep discharge when the laptop is in sleep without turning off other wakeup sources? I don't know why but mine was sleeping properly until recently, have already tried troubleshooting with numerous guides online to no avail

**Comment by profzei** [comment]
@samwzlim @JonnIEnglish Hi, my experience is different also in this situation:
- in my `BIOS settings` the option **Other wakeup source** is **not disabled** since I like very much turning on my machine from sleep just opening the lid XD
- my discharge rate per night is about 1.5-2% every 4 hours
- therefore I didn't report any anomalous fast discharge rate during sleep (a such percentage is "normal" for a hackintosh)

See also my answer [here #107 ](https://github.com/profzei/Matebook-X-Pro-2018/issues/107)

**Comment by huotarih** [comment]
I also had this problem, haven't tested lately since I've only used it plugged in. Will leave my MBXP until the morning and check again in the morning. If I don't come back to this in 12 hours I've propably gone to 0 battery and forgot. at 36% rn.

Also @profzei thank you for your hard work on all aspects of our machine, just sent you a small contribution for your work.

**Comment by huotarih** [comment]
Seems like wasn't the case this time. Returned with 32%

**Comment by rohirrim27** [comment]
@samwzlim, @profzei: Apologies for temporarily reopening this issue but wanted to check if there was any resolution to this or if @profzei you've been able to replicate it? I've been facing this continuously for a while even with the recommended sleep settings. 

Issue #136 also recommends the same BIOS setting fix but I'd like to keep the wake up on opening lid functionality. Thanks for your help!

**Comment by profzei** [comment]
@rohirrim27 Honestly I'm not been able to replicate this... I'm sorry!
