### ISSUE TITLE
Bluetooth issue after latest release

### ISSUE THREAD

**Issue by jonescamilla** [profzei/Matebook-X-Pro-2018#86]
The bluetooth on the matebook no longer functions as intended for myself with the latest release and I am uncertain on how to proceed.

After the release `1.6.0` from this repo bluetooth remains "on" but is non-functional. Old devices that were previously pared are still present in the dropdown from the menu bar though a connection to the device can't be made when clicking `connect`. The icon gives the impression that a connection was made after clicking `connect` though the device doesn't work or appear as a usable audio output.
![Screen Shot 2020-11-13 at 11 11 32 AM](https://user-images.githubusercontent.com/61066815/99111445-017f1480-25a1-11eb-8ba6-fba7307bfbe3.png)

The ability to turn off Bluetooth is also non-functional and greyed out.
![Screen Shot 2020-11-13 at 11 08 19 AM](https://user-images.githubusercontent.com/61066815/99111213-8b7aad80-25a0-11eb-94d0-f5b840461b93.png)

In previous releases a fix for bluetooth connectivity issues were revolved by turning bluetooth on and off, at times including turning the device that I am trying to connect on and off and in the worst scenarios I would have to restart the computer. Those fixes were attempted in this release and none resolved my bluetooth issue.

I would appreciate any assistance in better diagnosing and resolving the issue.

**Additional information:**
- Wifi is enabled in bios
- Bluetooth is enabled in bios
- Fingerprint is disabled in bios
- I've reset the NVRAM to try to fix the issue
- What my bluetooth settings page looks like:
![Screen Shot 2020-11-13 at 11 18 56 AM](https://user-images.githubusercontent.com/61066815/99112183-22943500-25a2-11eb-876b-ce9ab7aeb390.png)

**Comment by profzei** [comment]
@jonescamilla 
Hi, you only need to enable in your `config.plist ` in `Kernel->Add` section the kext named (if I remember well... I don't have access now to my MBXP...) `IntelBluetoothInjector` (it's located just after `IntelBluetoothFirmware`)

Let me know if this fix it😉

**Comment by jonescamilla** [comment]
Thank you for the advice @profzei! Unfortunately all mentions of `bluetooth` are enabled and more specifically the `IntelBluetoothInjector` is also enabled.

![Screen Shot 2020-11-13 at 11 56 27 AM](https://user-images.githubusercontent.com/61066815/99115461-45751800-25a7-11eb-96ed-bb898538dfe4.png)

**Comment by profzei** [comment]
@jonescamilla 
I'm sorry... look better!
For `IntelBluetoothInjector` you have `Enabled` **field** set to `false` **value**... you need to put it to `true`
