### ISSUE TITLE
External mouse causes all system gets slower with Big Sur.

### ISSUE THREAD

**Issue by mmenendezg** [profzei/Matebook-X-Pro-2018#87]
Hello, I upgraded my matebook to Big Sur, and most of the system seems to be properly working, but after connecting an external mouse, I noted that there are some issues when using it. 

First, I noted that when using the external mouse all system gets slower. That includes stopping system animations when moving the cursor with the external mouse, stoping YouTube videos if moving the cursor with the external mouse, and the whole system gets a little slower when using the external mouse. 

Then, I noticed that when moving the external mouse, there is a weird sound like a beep really low under the keyboard. 

May you guys have any suggestions for this situation?

**Comment by huotarih** [comment]
I  have the same problem. Bluetooth Magic Mouse works, but USB mouse makes everything very laggy.

**Comment by deckarude** [comment]
I think this happen when you connect a wireless mouse, my wired mouse works fine. but when I connect an wireless mouse you can see the animation on dockbar get laggy

**Comment by profzei** [comment]
Honestly I'm using touchpad and for issues a wired mouse (Microsoft), so I never had a such issue with a wireless mouse... this need more investigation...

**Comment by jonescamilla** [comment]
I use my matebook almost exclusively as a "mac mini" with a monitor and peripherals (wired keyboard and wireless mouse) so I'll test it out once I have time with a wired mouse.

**Comment by deckarude** [comment]
Is very easy to replicate, you just have to turn on magnification on dock, then hoover it over the dock you can see the animation is very fast and smooth. Then connect wireless mouse and you will be able to notice the different.

**Comment by jonescamilla** [comment]
I experimented with this and found different results than you mention. I only encountered a difference in "performance" when I pairing my wired mouse and the Matebook used like a laptop.

The conditions for testing aren't perfect but this is what screen recording got me.

1. Laptop w/ trackpad
![laptop-trackpad](https://user-images.githubusercontent.com/61066815/99888911-43ddcc80-2c05-11eb-8e61-eec0ab542cf1.gif)

2. Laptop w/ wireless mouse `Logitech M330`
![laptop-wireless-mouse](https://user-images.githubusercontent.com/61066815/99888918-5b1cba00-2c05-11eb-9c87-211420b8a49c.gif)

3. Laptop w/ wired mouse `Logitech G403`
![laptop-wired-mouse](https://user-images.githubusercontent.com/61066815/99888953-9b7c3800-2c05-11eb-959e-ce17b43b7dd0.gif)

4. Docked `Philips 346B1C usb-c dock` w/ wireless mouse `Logitech M330`
![docked-wireless-mouse](https://user-images.githubusercontent.com/61066815/99888996-0f1e4500-2c06-11eb-8938-bc2131c58c8c.gif)

5. Docked `Philips 346B1C usb-c dock` w/ wired mouse `Logitech G403`
![docked-wired-mouse](https://user-images.githubusercontent.com/61066815/99888998-13e2f900-2c06-11eb-87f5-55a132f3ded7.gif)

This honestly looks like a mess but when compared `AB` I see no notable difference except for `3` compared to the rest. Both through the videos/gifs and real life when not screen recording. The rest of the computer wasn't perceivably different. If you want to compare through the original `mov` [here's](https://imgur.com/a/fbB0vDs) a link.

**Comment by deckarude** [comment]
Nice that you can test so many different kind of mouse.  i guess is not only related  to just wireless but to wired aswell. however as you can see the animation does get laggy when you connect and specific mouse.

**Comment by mmenendezg** [comment]
I kept trying with different wired mouses and the same results. I am currently using a Razer Viper Ultimate. 

[Here](https://imgur.com/uJI52yo) is the result with the trackpad, and [here](https://imgur.com/BfhgnV7) is the lagged system with the Viper connected. 

There are some times that the system is really slow with the mice connected.

**Comment by mmenendezg** [comment]
After verifying this [thread](https://github.com/profzei/Matebook-X-Pro-2018/issues/108#issue-759449366), dhjs0010 suggested to verify in [this reddit post](https://www.reddit.com/r/mac/comments/juqcrd/calling_all_big_sur_users_here_check_windowserver/). After verifying all the possible solutions, I found [this video](https://www.youtube.com/watch?v=f7GgwR991I8&ab_channel=MrYves) where the recommendation is to change the polling rate in the mouse manager. 

I have the Viper Ultimate, and downloaded Synapse 3, and change the polling rate to 125Hz , and now everything is butter smooth.
