### ISSUE TITLE
iMessage Not Working

### ISSUE THREAD

**Issue by jam396** [profzei/Matebook-X-Pro-2018#88]
It has worked in the past, but now whenever I try to sign in it says ''Could not sign in. Username or password was incorrect.'' I know for sure that they are correct as they work for iCloud.

**Comment by Vatri91** [comment]
Did u do this:

"Default SMBIOS settings of this repo is MacBookPro15,2 MacBookPro14,1

Launch Terminal app
Copy the following script, paste it into the Terminal window, then press Enter
git clone https://github.com/corpnewt/GenSMBIOS && cd GenSMBIOS && ./GenSMBIOS.command 
Type 2, then press Enter
Drag your config.plist inside the Terminal window
Type 3, then press Enter
Type MacBookPro15,2, then press Enter"

**Comment by jam396** [comment]
Thank you! I just tried it and it worked after the restart!
