### ISSUE TITLE
New AirportItlwm 1.2 works great

### ISSUE THREAD

**Issue by Vatri91** [profzei/Matebook-X-Pro-2018#89]
Hi friends,

i am testing new AirportItlwm 1.2 and it works great. I got full speed on my internet

My Score:
https://ibb.co/5kfKYwz
Download: 80 Mbps
Upload: 10 Mbps

Maybe it's worth adding this as the default enabled option to connect to Wi-Fi. I have not found any problems using the new version. How does it work for you?

**Comment by profzei** [comment]
@Vatri91 
I enabled `AirportItlwm.kext` in my personal config.plist some time ago (please, see [Changelog](https://github.com/profzei/Matebook-X-Pro-2018/blob/master/Changelog.md) on **11-01-2020**)... and it's working fine! No issue even after sleep/wake-up process.

I also created (on 11-01-2020) a stripped version of `AirportItlwm.kext` (2 MB weight instead of 16 MB), but atm I do not yet included all changes in a release.

I just finished to rewrite **almost all ACPI patches** in a new way... it should be a better way! xD ...a lot of work has been done!
I'm still testing all the changes in a controlled environment i.e. Catalina 10.15.7 Supplemental Update where I know everything (maybe except touchpad...) is working fine.
I'm still testing my last patch for **touchpad**... **'till now it's working fine**... but I'm not totally convinced...
The changes I'm working on are not still available in this repo since I'm checking their consistency before upgrading to Big Sur...

Thank you so much for reporting your feedback for `AirportItlwm.kext` 1.2... I'll test it this evening (after stripping it! xD)

**Comment by Vatri91** [comment]
Nice to hear that :) If you need help with testing, let me know. I'm currently using your latest available repos on Big Sur. The system works just like Catalina. However, I regret that I updated the system because 10.15 looks much better

**Comment by Vatri91** [comment]
*Is one small problem on Big Sur.  If u change the position of the tray icons, system does not remember after restart.

**Comment by profzei** [comment]
> If u change the position of the tray icons, system does not remember after restart.

Not good...

Btw, could you check if the current version of `VoltageShift.kext` is really working in Big Sur? ...I'm asking this since that kext was not built with `MacKernelSDK` so it should not work properly... but I'm not sure...

**Comment by profzei** [comment]
@Vatri91 
I have just tested the new (beta) version of `AirportItlwm.kext` and I confirm a significant speed increase (In my case a factor 1.5x) but above all a greater reactivity of the web pages.
I'll include it in next release as default option!

**Comment by Vatri91** [comment]
> > If u change the position of the tray icons, system does not remember after restart.
> 
> Not good...
> 
> Btw, could you check if the current version of `VoltageShift.kext` is really working in Big Sur? ...I'm asking this since that kext was not built with `MacKernelSDK` so it should not work properly... but I'm not sure...

It's works ok

```
Last login: Sun Nov 15 19:24:07 on console
adriann@Adrians-MBP ~ % cd /Applications/Utilities                 
adriann@Adrians-MBP Utilities % sudo ./voltageshift info
Password:
------------------------------------------------------
   VoltageShift Info Tool
------------------------------------------------------
WRMSR 150 with value 0x8000001000000000
RDMSR 150 returns value 0xf3800000
CPU voltage offset: -100mv
WRMSR 150 with value 0x8000011000000000
RDMSR 150 returns value 0xf9c00000
GPU voltage offset: -50mv
WRMSR 150 with value 0x8000021000000000
RDMSR 150 returns value 0xf3800000
CPU Cache voltage offset: -100mv
WRMSR 150 with value 0x8000031000000000
RDMSR 150 returns value 0x0
System Agency offset: 0mv
WRMSR 150 with value 0x8000041000000000
RDMSR 150 returns value 0x0
Analogy I/O: 0mv
WRMSR 150 with value 0x8000051000000000
OC mailbox cmd failed
RDMSR 150 returns value 0x500000000
Digital I/O: 0mv
CPU BaseFreq: 1800, CPU MaxFreq(1/2/4): 3400/3400/3400 (mhz) Turbo_Disabled PL1: 15W PL2: 44W 
CPU Freq: 1.6ghz, Voltage: 0.6698v, Power:pkg 2.74w /core 0.64w,Temp: 44 c
adriann@Adrians-MBP Utilities %
```

**Comment by Vatri91** [comment]
> I have just tested the new (beta) version of `AirportItlwm.kext` and I confirm a significant speed increase (In my case a factor 1.5x) but above all a greater reactivity of the web pages.
> I'll include it in next release as default option!

Good news. We will have a fully stable system soon. If Goodix also released the source code, that would be perfect. It would be nice to see a working fingerprint reader on Linux / MacOs. Without TouchID, MBX2018 is better for me compared to the early 2020 MacBook Air.

**Comment by profzei** [comment]
@Vatri91 
a little update for AirportItlwm.kext (1ec370f): this morning after a 8h long sleep wi-fi was not able to automatically attach my network... it didn't see any sources...
Maybe I was unlucky or maybe we need to wait some more commits... in fact I see 2 new commits which seem "important"...
Have you ever had this issue? The version I compiled some commits ago (during first days of November) was rock solid as capability of attaching known sources. even after sleeping without any issues...

Obviously I know it is in beta stage!

**Comment by isuke01** [comment]
@Vatri91 
Do you believe we will see working fingerprint reader?

**Comment by profzei** [comment]
@isuke01 
Not in the short term... right now there is a lot of development to at least make smartcard readers work... which are not present in our machine... but I don't think there is still particular interest in fingerprint readers! I'd love to be proved wrong though!

**Comment by luuknieuwdorp** [comment]
FYI bluetooth is broken for me on the 1.2 AirportItlwm beta. Issue seems to have already been created in the item repo.

**Comment by Vatri91** [comment]
@profzei 
"a little update for AirportItlwm.kext (1ec370f): this morning after a 8h long sleep wi-fi was not able to automatically attach my network... it didn't see any sources..."

I had the same problem today... Click on switch power on/off fixed it.

@isuke01 
zobaczymy :) Miejmy nadzieje, że tak - We will see. I hope so

@luuknieuwdorp
I connected the headphones via bluetooth and I don't see any problem. What's your problem?

**Comment by luuknieuwdorp** [comment]
@Vatri91 I click on my connected bluetooth device in the menu and nothing happens. Specifically I'm trying to connect to Galaxy Buds+. The issue I mentioned is here. https://github.com/OpenIntelWireless/itlwm/issues/381

**Comment by Vatri91** [comment]
A tested 4 bluetooth headphones and it works ok.

Did u:
1) Click one bluetooth icon on tray
2) Power on Bluetooth
3) Next go to preference and choose your head phones to connect
4) Switch audio devices - Click audio icon on tray and choose your headphones

**Comment by isuke01** [comment]
@luuknieuwdorp 
Hey I used previously 1.1 version. I have connected BT speakers. Then I just updated to version 1.2 (most recent 4h ago).
I was unable to reconnect to my previously connected BT device. I just went into BT settings and I removed this device, then reconnect again - now works correctly.

@Vatri91 
Tak :) - Yes

System: Big Sur 11.0.1 
Loader: OC: 0.6.3

**Comment by luuknieuwdorp** [comment]
> A tested 4 bluetooth headphones and it works ok.
> 
> Did u:
> 
> 1. Click one bluetooth icon on tray
> 2. Power on Bluetooth
> 3. Next go to preference and choose your head phones to connect
> 4. Switch audio devices - Click audio icon on tray and choose your headphones

Yes did all those. I tried to remove my device like @isuke01 suggested but afterwards it doesn't seem to appear again in the devices list. Keep in mind we could be on different builds of the Alpha as there was a build 20 hours ago which seems to have already been replaced by a build from 8 hours ago making the old one unavailable. Maybe an older build that you're using does not exhibit these bluetooth issues.

**Comment by isuke01** [comment]
@luuknieuwdorp
Yep you're right. 

BTW! Did any one faced issue when download speed is fine, but after some time it goes down to 100-200kb/s?
I tested it against my macMini with same DL links, and it repeats all the time. macMini DL is fine, but here i face issue with slow down after some time of downloading.

**Comment by Hanline** [comment]
> @Vatri91
> a little update for `AirportItlwm.kext` (1ec370f): this morning after a 8h long sleep wi-fi was not able to automatically attach my network... it didn't see any sources...
> Maybe I was unlucky or maybe we need to wait some more commits... in fact I see 2 new commits which seem "important"...
> Have you ever had this issue? The version I compiled some commits ago (during first days of November) was rock solid as capability of attaching known sources. even after sleeping without any issues...
> 
> Obviously I know it is in beta stage!

I am facing a similar (maybe identical?) issue with the Airportltlwm.kext (Based on your latest AirportItlwm_Big_Sur.kext I got from the thread regarding disabling the touchscreen). Upon waking up from sleep, the Wi-Fi is no longer connected to the previous network, and it is unable to find any wireless network as well. Although, it seems like that it is still possible to toggle Wi-Fi on/off. Only working solution is to reboot the computer (not re-sleep).

I am currently running Big Sur 11.0.1. Wi-Fi works great otherwise, with instant connection upon boot and better overall performance compared to the Heliport-approach.

**Comment by profzei** [comment]
@Hanline This "issue" occurred to me too yesterday: what I did to solve was not to reboot machine but toggling Wi-Fi off/on and then reconnect to my previous network...

I know this is not a "solution" but I'm not the developer of that kext... which is in beta stage. What I could suggest is to download latest commit (which is 1.2 beta) independently renaming it accordingly to `config.plist` and check if the **OpenIntelWireless team** had fixed that particular issue... or it has introduced others! XDXDXDXD

**Comment by Hanline** [comment]
> @Hanline This "issue" occurred to me too yesterday: what I did to solve was not to reboot machine but toggling Wi-Fi off/on and then reconnect to my previous network...
> 
> I know this is not a "solution" but I'm not the developer of that kext... which is in beta stage. What I could suggest is to download latest commit (which is 1.2 beta) independently renaming it accordingly to `config.plist` and check if the **OpenIntelWireless team** had fixed that particular issue... or it has introduced others! XDXDXDXD

Well, anything that improves is a solution in a sense! I'm going to try it out, thanks for the "workaround". 😂

**Comment by JonnIEnglish** [comment]
Hey, my down speed is only 20 mbs running big Sur, any ideas of why this might be?

**Comment by profzei** [comment]
@JonnIEnglish 
I just downloaded an iso file of about 2.94 GB at max speed for my home network (i.e. about 5 MB/sec... I know it's not so much but this is what we could have in Italy) without any dropping in speed rate...
What I could suggest is using my [latest release v. 1.8.0](https://github.com/profzei/Matebook-X-Pro-2018/releases) (released last night) where you could find latest commit for **alpha** stage AirportItlwm project

**Comment by JonnIEnglish** [comment]
@profzei Alright I'll give that a shot, many thanks!
I'll let you know my results.
