### ISSUE TITLE
performance of igpu(can not stick on 1.1 Ghz)

### ISSUE THREAD

**Issue by kxlv2000** [profzei/Matebook-X-Pro-2018#9]
Hi,
I'm the guy(i5-8250U+UHD620+MX150) from [gnodipac886](https://github.com/gnodipac886/MatebookXPro-hackintosh/issues/112) 's issues page. After trying your config, I found my other small issues such as usb_c as well as bluetooth now function well, which cannot work properly before. Thank you a lot!
But, the IGPU never comes to 1.1Ghz since 5days ago, what make me really confused is that, it do really reach 1.1G for 5 continues reboots after first install your config(I replace your CPUFriendDataProvider.Kext whit OneKey version), but it just disappear after 6th boot next day and never come back again. So does the power of cpu package, It can never goes over 15W since that,  Even though I didn't change anything. now what ever I do I can never reach 1.1G, including re_install clover, re_copy EFI, re_install MacOS, which really confusing me nowadays.
Do have any idea? what's the main reason that block the IGPU frequency, I guess there must be tiny difference between I7 & I5 's ssdt. Thanks~

**Comment by profzei** [comment]
Sorry for the delay in my reply... I just worked on other aspects till yesterday: support for Intel(R) WiFi 8265/8275 and (I hope) a better support for headset switch!

I'm very interested in optimise power management, so as first step I need to learn how to undervolt my machine and then injecting those values at bios level; at that point I think I'll be able(or brave!) to change TDP profile...

Could you address me to a very good guide for undervaluing, please? Which tests are needed to say that a machine is "stable"?
Thank you!

**Comment by kxlv2000** [comment]
Hi, [here](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/174) is a example of decreasing voltage to increase performance under a limited power by using VoltageShift.kext. and  [this](https://github.com/buliaoyin/VoltageShift)is guide of using it, But it may fail to change MSR on Bios leave sometimes on MBXP. you can simply use GB5 or IPG stress test to check weather under voltage works, here is a successful example(I also changed TDP to 30w) I have reached (but now I can never reach it again... maybe due to the conflict of cpufriend, ssdt or volteageshift) 
<img width="1500" alt="截屏2020-05-03下午7 33 13" src="https://user-images.githubusercontent.com/49295281/83387126-c63bbf80-a41e-11ea-8590-afa62bdf4f49.png">
Afaik, under voltage can hardly cause hardware damage, but it can cause fail to boot if you decrease too much and inject it into bios before system launchd. if you can pass the GB5 or IGP stress test, under voltage won't cause system failure during daily use.
May I ask a little question, could you read or speak Chinese? I guess most of Huawei user may be Chinese, If you can, I'll share you some Chinese webpage about unlock TDP. 
Looking forward to your reply, thanks!

**Comment by kxlv2000** [comment]
I just followed your Intel Wifi install guide it really works to me!!! thanks for your recently effort!

**Comment by profzei** [comment]
Hi,thank you very much for all the material you provided to me! I can use Google Translator for Chinese webpage: please share your resource!

**Comment by kxlv2000** [comment]
Hi, I've just tried to use Hackintool.app to unlock MSR, together with voltageshift.kext, it seems that TDP was unlocked perpetually(also stable), you can try to check the MSRs like the screenshot below. and see wether TDP change take efforts.
<img width="656" alt="image" src="https://user-images.githubusercontent.com/49295281/83425901-f60bb700-a460-11ea-8957-d37ac619856b.png">

here is a result of my i5_8250U after unlock TDP, together with under voltage(PL1: 15w -> 32w,PL2: 44w -> 60w, undervoltage: -90mv),GB5 multi-core cpu test score:2400 -> 3500, which is same to TDP unlocked win10's score.  
<img width="585" alt="image" src="https://user-images.githubusercontent.com/49295281/83427962-256ff300-a464-11ea-84b1-8834510972a1.png">

![7F13A8E4-036B-4D31-875C-A7E2A4BDDAC2](https://user-images.githubusercontent.com/49295281/83426531-dde86780-a461-11ea-899f-6f8abafe8216.png)

As to daily use, after unlock TDP, 4-core will run at full speed even facing a simple task, here is an example I open the safari and then I open a website, the power change.(power keeps 2-3w when stay on desktop unmoved)
![IMG_1060(20200601-232223)](https://user-images.githubusercontent.com/49295281/83426888-6f57d980-a462-11ea-8a0c-ab3b6fa4b7ab.JPG)

The system response much more faster when 4-core run at full speed and my previous problem about IGPU frequency was solved in the same time, but this may cause the decrease of battery life when AC unplugged, so I also use another app called Endurance.app to save power when unplugged, here is the result.
<img width="400" alt="image" src="https://user-images.githubusercontent.com/49295281/83427391-4257f680-a463-11ea-9431-a85b29118bae.png">

Till now, it seems that I have found a perfect balance between performance and battery life, it need some time to check wether I'm right.

**Comment by kxlv2000** [comment]
> Hi,thank you very much for all the material you provided to me! I can use Google Translator for Chinese webpage: please share your resource!

You may try the links I perviously shared first, I just flowed them together with Hackintool.app to  easily unlock MSRs and successes. The Chinese webpage guide use voltageshift.kext, too, but another difficult way to unlock MSRs, which I succeeded before but don't recommend now. you may take it as a reference. Here are the links:
http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1848205&page=1#pid50245611
http://bbs.pcbeta.com/viewthread-1847093-1-1.html
http://bbs.pcbeta.com/viewthread-1847097-1-1.html

**Comment by profzei** [comment]
Do you have a link for download a version of Endurance.app: it seems very interesting!

**Comment by profzei** [comment]
Give my some days to learn and do some tests (I have some deadlines to respect...for my work)

**Comment by kxlv2000** [comment]
[Here](https://xclient.info/s/endurance.html#versions) is an TNT version of Endurance2.0.app which I'm using, you may use translator to read the guide of crack and find download link in this Chinese webpage, and [this](https://enduranceapp.com) is Endurance3.0's official release page which will cost US$20.

After installing, you can easily switch power-saving-mode in your Task bar, like this. 
<img width="538" alt="image" src="https://user-images.githubusercontent.com/49295281/83471756-17e45880-a4b8-11ea-9e5f-3a2c8456cfee.png">

**Comment by kxlv2000** [comment]
> Give my some days to learn and do some tests (I have some deadlines to respect...for my work)
> 
> Your extensive test is quite impressive! It's an honour to speak with you!

OK, sure, I myself also facing the DDL of our university's final term project. XD Thanks for your concern about my issue and GOOD LUCK to you!

**Comment by kxlv2000** [comment]
Today, I finally found the mystery that block my eyes for two months about the unreproducible performance of the igpu. It’s pretty stupid. I’ve been confined to the system software, driver bios, hardware level,  I don’t know how many times clover has been reconfigured, the system has been reinstalled dozens of times, and I never expected that the charging cable is the root Course. 
I always thought that my two cables both support the PD2.0 protocol, so i usually mixed them up, but one of them is only QC3.0, and our motherboard also supports the QC3.0 protocol, so it is not observed to find out, and the power curve of IPG is not regular, probably about 12-15w, which is very close to the CPU's default tdp15w. Until today, I used a power meter to check the charging adapter and it only works under 9v2a. then did I find the root cause: if the battery or qc motherboard is turned on, the tdp will be locked and the frequency reduced.  Only when pd charging Top can be successfully unlocked.

**Comment by kxlv2000** [comment]
Hi,
Do your IGPU run at full speed(1.1Ghz) when using Final Cut Pro X? Or large media processing application such as Adobe PS, AE, PR? My IGPU only works at 300Mhz and there is a serious frame dropping when drag the video preview bar. even though this video is very small. Same things happened when using photoshop, when I drag or zoom a picture, it isn't really smoothy. It  seems that IGPU is not work properly. Is there some wrong with the hardware acceleration? Daily use is all right. This only happened when using large media processing application. Thanks

**Comment by benbender** [comment]
@kxlv2000 Had the same issue and it was fixed with this commit: https://github.com/acidanthera/WhateverGreen/commit/6a1990e5413f5323d24df4ed2a4c6a9ed5b41836

There is no official release with this commit yet so here is mine or you have to build it yourself.
[WhateverGreen.kext.zip](https://github.com/profzei/Matebook-X-Pro-2018/files/4874800/WhateverGreen.kext.zip)
