### ISSUE TITLE
Incorrect/outdated changelog & commit messages

### ISSUE THREAD

**Issue by luuknieuwdorp** [profzei/Matebook-X-Pro-2018#91]
I was browsing through the Changelog.md file when I noticed some changes mentioned on there never seem to have been committed to the repo. Most notably last update I noticed the following changes in the Nov 11 update that don't seem to actually have been committed.

**OpenCore**
  - Update `config.plist` to support OpenCore v. 0.6.3:
      - `Kernel -> Quirks -> ForceSecureBootScheme` set to `false`
      - `Kernel -> Quirks -> LegacyCommpage` set to `false`
      - `PlatformInfo -> CustomMemory` set to `false`
      - `UEFI -> Output -> ForceResolution` set to `false`

Another small thing I noticed is sometimes your commit messages aren't very descript, making it hard to keep track of the changes. This is just a bit nitpicky though but it'd be nice if not every commit message was `Update (day month year)` (:

**Comment by profzei** [comment]
hi @luuknieuwdorp  your answer is probably [here](https://github.com/profzei/Matebook-X-Pro-2018/issues/89#issuecomment-727602236)

Updates whose commit message was in the form `Update (day month year)` refer only to Changelog and Readme files so could be ignored... they are only for my tracking purposes...

**Comment by luuknieuwdorp** [comment]
@profzei I think we misunderstood each other but I found out why. I didn't realise you only released the newest version as a zip in the 'releases' tab in GitHub, without actually committing the changes to the repo. Now I'm using the new update without issues (:

**Comment by profzei** [comment]
@luuknieuwdorp Great!
...however I need to clean/update/synchronize my repo...
