### ISSUE TITLE
Big Sur Ambient Light Sensor

### ISSUE THREAD

**Issue by BigEmperor26** [profzei/Matebook-X-Pro-2018#96]
First of all, thank you for your work. Me and other owners of this laptop express our gratitude. 
Now, here the bug. 
I noticed on Big Sur there an issue with the brightness. Specifically it cannot be adjusted by the control center. The ambient light sensor will always have priority on adjust the brightness.
I believe is the ambient light sensor as this behavior does not happen when it is disabled in the settings. 
Using FN keys or using the settings under display do not trigger this issue.

**Comment by JonnIEnglish** [comment]
I also experienced this issue, I think, you just have to go to settings, displays and turn off the ambient light option.

<img width="669" alt="Screenshot 2020-11-23 at 12 58 13" src="https://user-images.githubusercontent.com/24739247/99954629-c0021c80-2d8b-11eb-8f7d-c3bd3d70ea5a.png">

**Comment by profzei** [comment]
Honestly, I didn't have a such issue...
In my **Display Settings** I have a tick on the option **Automatically adjust brightness** i.e. it is enabled, but anyway I could adjust my brightness levels using `F1` and `F2` shortcuts (without the need to simultaneously press the key `Fn`)
