### ISSUE TITLE
MacOS can't connect to Logitech MX Master/Anywhere Mouse

### ISSUE THREAD

**Issue by samwzlim** [profzei/Matebook-X-Pro-2018#99]
Anybody else having difficulties connecting their logitech mx master/anywhere mouse to a hackintosh via bluetooth? It just keeps connecting but never gets connected. MacOS can only detect the mouse when i use the usb dongle included with the mouse but thats so annoying as it leaves me with my only usb a port occupied. I have already tried everything i could, switching between the 3 bluetooth profiles that the mouse has, removing buetooth device and re-adding it, forget device and re-adding. I dualboot with windows and bluetooth works just fine on it. I connected the mouse to my ipad via another bluetooth profile and it works well too. Heck, it even works with my phone via profile 3. Basically it works with every device ive tried except macos. Bluetooth is working perfectly fine on my hackintosh, as im able to find other bluetooth devices and connect to them successfully (wireless earbuds, external speakers, keyboard, ipad, phone etc). Its just this mouse thats driving me crazy Ive searched online for this issue and some people are facing it as well but cant find a solution for it. I use a MX Anywhere 2S mouse and my laptop is the 2018 Matebook X Pro i5 model. For context, problem existed back in Catalina and is still present in Big Sur

**Comment by yamanadamnor** [comment]
I have a MX Master 2s with the same issues youre describing. I think its related to Bluetooth LE but im not sure. As far as i know there is no solution for this issue.

**Comment by AshleyMiller9696** [comment]
same problem for me
//mx anywhere 2

**Comment by samwzlim** [comment]
> I have a MX Master 2s with the same issues youre describing. I think its related to Bluetooth LE but im not sure. As far as i know there is no solution for this issue.

In that case, why does it only affect the MX Master/Anywhere product line? In my experience, all other bluetooth peripherals work perfectly with the hackintosh.

**Comment by profzei** [comment]
same here with my microsoft mobile surface BT mouse!

@samwzlim 
I tried to dig a little more into this **issue**: please see
[Comparability issue with Bluetooth 4.x devices](https://github.com/OpenIntelWireless/IntelBluetoothFirmware/issues/51#issuecomment-589949327)
[Intel BTLE 9460/9560 Module loses connectivity with mouse/keyboard with no reason](https://github.com/OpenIntelWireless/IntelBluetoothFirmware/issues/217#issuecomment-727535960)

**Comment by m2faridi** [comment]
i have problem for mouse mx master/anywhere s2
pls fix

**Comment by dmpanch** [comment]
Same here with MX Master 2, must use Unifying for now.

**Comment by profzei** [comment]
@dmpanch You are right! As reported in Readme in homepage **Intel Bluetooth** could not support some Bluetooth devices like some Bluetooth mouse since it is only a firmware injector; please, report any issues not here but only on [**OpenIntelWireless/IntelBluetoothFirmware Gitter Chat**](https://gitter.im/OpenIntelWireless/IntelBluetoothFirmware?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
